### ISSUE TITLE
Promotions still appearing when they shouldn't

### ISSUE THREAD

**Issue by Wheelchair2** [yairm210/Unciv#10045]
**Platform**
I am using OPPO A12e, Android 8.1.0

**Version**
4.8.0, from Play Store

**Describe the bug**
Even after the 4.7.18 update "Fix promotions appearing when they shouldn't", promotions are still appearing when they shouldn't. I am in the latest version as of 4th of September. The second screenshot shows how the promotion looks like with its proper needed prerequisite, Satori Race promotion, and the third screenshot shows how the code looks like for those promotions

![Screenshot_2023-09-04-20-32-26-60](https://github.com/yairm210/Unciv/assets/132828663/66c268cb-6193-4be0-8191-922185742536)
![Screenshot_2023-09-04-20-55-55-79](https://github.com/yairm210/Unciv/assets/132828663/69312928-d45d-4582-9c16-a1c13771a739)
![Screenshot_2023-09-04-20-36-24-00](https://github.com/yairm210/Unciv/assets/132828663/ac3bf0d9-0a5d-4fbf-a7a2-78f6c68da33c)

**Comment by SeventhM** [comment]
OP implies this is referring to #9986. However, the patch notes do not say "Fix promotions appearing when they shouldn't", but instead say "Fix promotions being available when they shouldn't". The prior issue being addressed was never promotions showing on the promotion but rather promotions being selectable and pickable in situations where it shouldn't be. The scope of that PR was never to address if the promotions was visible or not. As such, I believe this issue is better addressed to #9655, which is the PR that actually introduced promotions showing when they aren't selectable
There are at least some challenges regarding this issue that I'd want other contributor's opinions on before I felt like investigating addressing this:
1. There are genuine cases where promotions that are not currently available should still be visible. For example, if someone wanted a promotion to require multiple other promotions, it would likely be annoying that the promotion would hide itself by default
2. There's no way to figure out such cases with pure code as the intent of various situations may be entirely different from mod creator to mod creator. This would mean introducing more uniques, thereby making this issue a [modding request](https://github.com/yairm210/Unciv/issues/3242)

**Comment by Wheelchair2** [comment]
I see, thanks for the response

**Comment by Wheelchair2** [comment]
I thought it was a normal problem, since every other mod experiences this as well.
`[	//this is just how you normally do promotions`
`	{`
`		"name": "Promotion A",`
`		"uniques": ["First promotion"]`
`	},`
`	{`
`		"name": "Promotion B",`
`		"prerequisites": ["Promotion A"],`
`		"uniques": ["Second promotion"],`
`//All unit types are available here, it's unnecessary, it only appears in units with the unit type anyway`
`		"unitTypes": ["Sword", "Ranged", "Archery", "Gunpowder", "Mounted", "Armored", "Fighter", "Bomber", "Helicopter"],`
`	}`
`]`
You simply have to make two promotions like how you normally do where one prerequisites the other, and it will reproduce the problem, making it appear in every unit's promotion page despite not having the required promotion (as long as it has the unit type), as shown by the screenshots. I tested the extent of this problem and it seems that even if the Stab Third Eye requires Accuracy III, it still appears in the promotion page, and after adding "Sword" to the "unitTypes" line of Bombardment III and then making it require Satori Race, it also appears in the promotion page of a unit without Satori Race
(Note: row and column doesn't affect this, as I tested)

Link to my mod: https://github.com/Wheelchair2/World-Of-Gensokyo-Touhou-Mod/tree/main
Link to RekMOD: https://github.com/ravignir/RekMOD/tree/master

_Here's a screenshot from RekMOD showing the special promotion set for Prussia, it's supposed to only appear in Prussian units with the promotion "Gehorsam" and as you can see here, the whole promotion set appears in a unit without the "Gehorsam" promotion_
![Screenshot_2023-09-06-18-56-15-47](https://github.com/yairm210/Unciv/assets/132828663/c2435889-f993-46a1-90f1-c6567c070588)

![Screenshot_2023-09-06-18-56-10-30](https://github.com/yairm210/Unciv/assets/132828663/b0a3dc46-9c9c-4c19-966b-c5ac327734f9)
![Screenshot_2023-09-06-18-13-36-81](https://github.com/yairm210/Unciv/assets/132828663/f9e12f51-eaec-4fc0-8837-b12796ca53bc)
![Screenshot_2023-09-06-18-34-15-62](https://github.com/yairm210/Unciv/assets/132828663/66f9f800-4ce1-4d8e-96e9-90ef387eb655)
![Screenshot_2023-09-06-18-42-33-95](https://github.com/yairm210/Unciv/assets/132828663/50b9affb-f28e-45ae-9dfb-dcca0cdbe0ae)
![Screenshot_2023-09-06-18-20-49-18](https://github.com/yairm210/Unciv/assets/132828663/57afedfe-2f32-4e9b-b90e-1c6338c13ffe)
![Screenshot_2023-09-06-18-21-11-28](https://github.com/yairm210/Unciv/assets/132828663/b91c506a-85bb-44f0-a824-f7adfac22cd1)

**Comment by SeventhM** [comment]
> Yea the circular reference promotions of RekMod, I remember them being a nuisance.

??? This is completely irrelevant to that. This is not what this issue is about


> that flags mods as invalid when a Promotion has a prerequisite that is not allowed by unit type

1. Adding such a rule may affect many mods in a negative way. Nearly every mod that gates off promotions in some way by needing some special promotion (usually given by some building or policy) would suddenly by flagged as invalid. At best, that could be made a warning, but I don't really see the point because
2. Abiding by such a condition still doesn't really address anything. E. g., in the screenshot regarding Rekmod's special promotions for Prussia, All I'd have to do to avoid being marked as invalid there is given the base promotion `Only available <for [Prussia]>`. This still wouldn't address the issue at hand, though, as the promotion would still show for other civs who aren't Prussia. At best, all it would do is make it more clear that it requires a promotion you can't get
3. I'm concerned that adding such a rule to RulesetValidator might just add even more limits to mod devs unless you also added a `<never>` conditional

**Comment by SeventhM** [comment]
> Maybe compare how current, just-after 9655 and pre-9655 actually render that situation

Btw, I can give a summary if you want

Pre-9655:
- Get the list of promotions from `unit.promotions.getAvailablePromotions()`. This gets promotions that could immediately be bought, filtering out promotions that can't be gotten due to `Only available` uniques
- Filter out promotions with prerequisites who all fit outside that list
- Build a tree out from there, listing all promotions, available or not, that require a promotion already in the tree

Current:
- Get the list of promotions from the ruleset. Filter manually by stuff that matches the unit type or a promotion we already have
- Build a tree from there

This leads to 2 main differences
1. Pre 9655, if Promotion A listed all unit types, and if Promotion B had a blocking "only available" unique, Promotion B would only show if Promotion A **wasn't** gotten. Since promotions show pre 9655 without ever checking if it should be available, it would always show if there was a route to get there that wasn't direct. E.g., if you use the example given in #9982, the "Input" promotion would always show unless you specifically had Drill I but not Shock I. The current system shows all of the promotions regardless of situation
2. Pre 9655, if promotion A did not list all unit types, it would not show. Even if you already gotten the promotion if I'm reading it right. The current version does show Promotion A if we have gotten the promotion. The side effect is Pre 9655, assuming there is no blocking "Only available" unique, Promotion B would never never show unless you get Promotion A. The current situation still shows Promotion B regardless. This situation is the primary one this issue is concerned with
