### ISSUE TITLE
AI is terrible 

### ISSUE THREAD

**Issue by trentonk23** [yairm210/Unciv#10330]
Barely attacks, unit spam , uses no strategy, barely takes city's. Version 3-0-0 an up is peak unciv , had the best ai. It wasn't afraid to attack, does skirmish, does not unit spam ( putting units on every single place) feels different Everytime, had the best mods, and was fun

**Comment by tuvus** [comment]
I agree that the AI is not very good right now. The AI diplomacy is currently being reworked to use defensive pacts and to form teams. However, it's hard to balance the aggressiveness and peacefulness of the AI, especially as it should change from the early game to the late game. I have also seen that after the last AI update, the AI has been far too peaceful #10071. I am working on some more tweaks now that I have finished part of the AutoPlay feature #10315.

Please understand that it is not easy to balance AI and have it perform acceptably in terms of processing time.

Could you send some save files or just pictures of the politics graph to show the diplomatic status of the Civs in the game? I usually run the AI against itself to see how it does (because it is way faster) but some human examples might help.

**Comment by trentonk23** [comment]
I think the  diplomacy is good, ai just needs to trade for gold more

**Comment by tuvus** [comment]
From the little investigation I have done, I think the AI's gold evaluation should be looked at again. They don't scale the value of gold in the later stages of the game. E.G. a luxury resource always costs 50 gold even if the AI has 700 gold per turn. 
But yeah, they don't offer to sell extraneous luxury resources.

**Comment by hackedpassword** [comment]
> Please understand that it is not easy to balance AI and have it perform acceptably in terms of processing time.

@tuvus I read this as a self-imposed limitation that's making AI development harder than it needs to be. What's the difference if the AI calcs make me wait another 2.0 seconds on an already 10 second (or whatever) turn break? I'll happily give up whatever extra CPU/GPU/Battery for a more coherent AI.

_I'm making no complaints against the current AI._ It's not perfect by far but the amount of sophistication and complexity it grinds to make the next play is dizzying.

I propose an Advanced option that calls in any number of additional AI considerations, routines, resources, etc: Potato | Unlimited

Some players, especially after having played the game for a while, will find themselves at a graduation point where the ultra clever efficiencies you strive to implement are no longer conducive to the desired gameplay.

**Comment by trentonk23** [comment]
agree with hacked password

**Comment by yairm210** [comment]
"please better UI" is a constant, like "better performance". Nothing in this specific issue makes it particularly actionable, therefore closing
