### ISSUE TITLE
Icons missing in research and production

### ISSUE THREAD

**Issue by TheKingOfLight** [yairm210/Unciv#10375]
**Platform**
Linux Mint 21.2, 4.8.14, 64bit.

**Version**
From Flathub, Build 924

**Describe the bug**
Sometimes some icons of units and buildings may be missing. The icons are missing in research and production. If they are missing, they are always the same icons.
The icons of the units are displayed correctly on the map.

This can be fixed by often rejoining the game (Exit and reload save).

**To Reproduce**
1. Start a game
2. Icons can be missing (in about 4/5 cases?)
or
1.  Leave a game (with missing or existing icons)
2.  Start the game again
3.  Icons can be missing (in about 4/5 cases?)

**Expected behavior**
The icons should not be empty

**Screenshots**
![grafik](https://github.com/yairm210/Unciv/assets/72839891/cf2b75a0-7c0a-4d2a-9103-dc96ee76adad)
![grafik](https://github.com/yairm210/Unciv/assets/72839891/2dde8ec0-91c9-4b6e-ad94-7461c06678de)
![grafik](https://github.com/yairm210/Unciv/assets/72839891/705352fe-ab3e-4692-88da-f11bd18fac96)
![grafik](https://github.com/yairm210/Unciv/assets/72839891/9b4a3ed9-52fa-4150-a340-b99205bd7675)
![grafik](https://github.com/yairm210/Unciv/assets/72839891/120f1222-ff40-43cc-a0e1-5f6aff0f3ad1)

**Additional context**
Happens in single and multiplayer
Happens in all the languages I have tried (English, German)
Some friends have also missing Icons

Missing icons: Shrine, Composite Bowman, Terracotta Army, Amphitheatre, Petra, Grear Mosque of Djenne, Grand Temple, Galleass, Alhambra, Leaning Tower of Pisa, Privateer, Gatling Gun, Great War Infantry, Triplane, Great War Bomber, Neuschwanstein, Machine Gun, Landship, Marine, Recycling Center, Bomb Shelter, CN Tower, Hubble Space Telescope.

**Comment by Anon177013** [comment]
I'm having this issue right now. It appeared after loading a manual save from 200 turns before (turn 347 back to turn 147). I'm not sure what exactly triggered it though. 

Basically some units and buildings icons are missing everywhere they should be (tech tree, city screen, overview, civilopedia etc), some luxuries have a white background (instead of yellow), and some civilizations and natural wonders icons are missing in the civilopedia. (I'll try to add some screenshots) 
It seems it's only the ones from G&K though, not the Vanilla ones (and I think all of them, not sure though).

Also, if I reload the same save, the issue is still there. If I go back to the main menu, then load it again, it's still there. But if I go back to the main menu, go to start a new game, go back, then load the save, the icons are back. Then if I go back to start a new game, change rulesets from default G&K to Vanilla, then load the save, they're missing again.

It's on Android, version 4.12.6-patch1, no mods, G&K rulesets, on a map created and slightly modified with the editor.
