### ISSUE TITLE
StatPercentFromReligionFollowers counts wrong Religion?

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10384]
Definition: `StatPercentFromReligionFollowers("[relativeAmount]% [stat] from every follower, up to [relativeAmount]%", UniqueTarget.FollowerBelief),`

Wording implies nothing about **_which_** followers, but context does: ***I*** would expect this to count the followers of the Religion the Belief carrying the Unique is bound to. But it actually uses getFollowersOfMajorityReligion, which determines the winning Religion per city - which if you're losing the indoctrination war isn't your Religion...

This goes back all the way to #4890

Q: Am I right? This should read the civ's Religion, not the city's?
~Q: I see a potential quirk in getMajorityReligionName: If a city has exactly half its population believing shit and the other half believing crap, then getMajorityReligionName will get a nondeterministic choice of either shit or crap, and that could change anytime due to a HashMap operating under there... Anyone can comment - or has seen something weird like that in-game?~
Q: What's the actual working target scope of `city.getMatchingUniques`? It does include Nation-level stuff, right? I'm so behind on these local/global scope mechanics... But it does look like StatPercentFromReligionFollowers would actually work on a Policy or somesuch too...

~Q: Does anyone have any RekMod game where the effect of choosing Mithraea as founder Belief could be tested - at best something where "Found Religion" is on the NextTurn button and the Belief is free?~

**Comment by SeventhM** [comment]
> Am I right? This should read the civ's Religion, not the city's?

Correct, but this is a bit weird. As noted in the comment, Mithraea intentionally uses it incorrectly. Under normal circumstances, you cannot use a follower belief unless it's the majority religion of a city. As such, under normal circumstances, using the city's religion should be a fine assumption. As you noted, this let's the unique work on policies when it probably shouldn't. I'm not sure if the severity of the warning in the ruleset validation should be upped to make Rekmod not work here but¯⁠\\⁠_⁠(⁠ツ⁠)⁠\_⁠/⁠¯
Note: in the source material (the civ 5 mod "Lekmod"), Mithraea does actually function as a follower belief despite being on a founder. That's why I'm just leaving it like this for now. If there's a unique to adopt beliefs as a triggerable, then I'll probably fix it that way

> What's the actual working target scope of `city.getMatchingUniques`

`civ.getMatchingUniques` plus the follower-style beliefs and all uniques from buildings tagged as having a local effect. So, yes, nation uniques, policy uniques, global uniques, tech uniques, etc.

**Comment by SeventhM** [comment]
Yep, I see, will get on it tomorrow
