### ISSUE TITLE
Feature request: city UI prevents city attacks on some hexes

### ISSUE THREAD

**Issue by Cwpute** [yairm210/Unciv#10457]
**Is your feature request related to a problem? Please describe.**
I ran into a situation in which my city was able to bomb a nearby unit, but i couldn't as the UI prevented me from accessing that hexe's touch area entirely.
![20231103_003258](https://github.com/yairm210/Unciv/assets/80604512/4ef70a8b-9168-41b6-bcd7-03ae5d9de5c0)
In the atached Screenshot, the unit i couldn't bomb is in tge top left, behind my archer's selection button.

**Describe the solution you'd like**
Tie city bombing to a special button that only appears when that action is available. When pressed, the rest of the city UI disapears and highlights enemy units in range of the attack.

**Comment by topincirler** [comment]
![20231211_075535](https://github.com/yairm210/Unciv/assets/146531399/9daaf319-2c07-44ee-ac3c-db3d6f95b3a4)
Same problem here but this is worse I think because enemy is in bottom tile and City UI blocks attacking -almost- completely. I can still attack as there is so little place to touch. Yet, it is really so hard. But it really seems lots of work to fix, though.

**Comment by SeventhM** [comment]
This is a much smaller problem than before. Can close?

**Comment by yairm210** [comment]
Various solution have been tried over the years, since failed and were abandoned, some succeeded and we're incorporated
I'm open to new solutions not an not excited to try attempt number 5 myself
