### ISSUE TITLE
Feature request: Buying cities of AI civilizations

### ISSUE THREAD

**Issue by AXYEPO** [yairm210/Unciv#10472]
Buying cities from civilizations introduces an imbalance. Yes, I lose a lot of resources in the transaction, but the resources are given for 25 turns and I keep the city forever. Logical scenario: when dominating a war to achieve peace, the AI can offer you a city. This scenario is used in the Civilization computer series. Thank you!

**Comment by tuvus** [comment]
Before my PR #10370 was introduced in build 4.8.15  the AI mistakenly valued every city at a maximum of 1000 gold instead of at a minimum of 1000 gold.
Please tell me if this keeps on being the case with build 4.8.15  and up. If it isn't can you tell me how much you are giving and how big the city is?

Thanks!

**Comment by yairm210** [comment]
@AXYEPO Still a problem?

**Comment by SeventhM** [comment]
Closing as completed
