### ISSUE TITLE
Unable to upgrade some units. 

### ISSUE THREAD

**Issue by Dark0-04** [yairm210/Unciv#10603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.9.1

### Describe the bug

Units requiring a building cannot be upgraded, even when the required technology is unlocked and the necessary building is constructed. The bug only affects the Alpha Frontier mod. 

### Steps to Reproduce

1. Create a game with Alpha Frontier
2. Train a Rover Explorer
3. Research “Robotics” technology and build a Rover Storage. 
4. Upgrade the already existing Rover Explorer : the upgrade button does not exist. 
5. Note that you can still train Combat Rovers, but existing Rover Explorers cannot improve. Also note that the bug seems to affect all units that require a building, almost half of the units. 

### Expected Behavior

The button “Upgrade to Combat Rover” should appear 

### Screenshots

![Screenshot_20231127_211618_Unciv](https://github.com/yairm210/Unciv/assets/104214100/240e13fa-e8ec-4935-9bf9-9f72d7
![Screenshot_20231110_220826_Unciv](https://github.com/yairm210/Unciv/assets/104214100/7073b9b7-0d97-4ae1-b508-2da8a16abce3)
bfc09c)

![Screenshot_20231114_114443_Unciv](https://github.com/yairm210/Unciv/assets/104214100/21c641c5-8742-4d34-b724-cde5c22bf216)

### Operating System

Android

### Additional Information

Bug already reported on discord and also spotted by other people

**Comment by Dark0-04** [comment]
On the screens, I also used the "Deciv in Alpha Frontier" mod, but the big also appears on the original version of Alpha Frontier. 

![Screenshot_20231127_211618_Unciv](https://github.com/yairm210/Unciv/assets/104214100/f8343ffd-102f-4414-bd0e-4054f9301c08)

**Comment by SeventhM** [comment]
...Or Alpha Frontier can use the ``Unbuildable`` unique. There's a slight bug there too, but it's definitely a faster PR to parse

**Comment by SeventhM** [comment]
For the record, imo the better solution is for the upgrade logic to know that city based should be considered irrelevant. Probably the easiest way actually should be that conditionals that relies on city data maybe should pass as true (as if they were never there). Idk if that'll have any consequences elsewhere. Though in this case, we happen to just have an alternative unique to make this a nonissue

**Comment by hackedpassword** [comment]
> We have no declarative compatibility matrix which Conditionals can work on which UniqueTypes

Wow, the post I needed! Spent hoursssss deciphering unique-conditionals that look like they should work...

In general, a compatibility matrix would be a godsend for compatibility reference. These unwritten rules are doing neither the modder nor player any good. The Unciv documentation is great, but uniques behavioralisms could use a serious documentation injection. Idea:

The uniques page lists all individual uniques. As efficient and neat as it is to list each unique one time, because of fuzzy overlaps between uniques and conditionals (plus everything else), is it possible to have a drop-down compatibility revealer that then lists each specific compatible unique, for that unique?

Or:

Activate the wiki feature in the Unciv repo here, do the above, but in the form of say, [Minecraft compatibility tables](https://minecraft.fandom.com/wiki/Enchanting#Summary_of_enchantments_by_item). Please look at that link, at the several tables shown. Unciv uniques have complexities that I believe can be mapped similar to how Minecraft has disambiguated N-dimensional assets and entity relationships.
