### ISSUE TITLE
Feature request: Worker automation to stay within borders

### ISSUE THREAD

**Issue by The-Talik** [yairm210/Unciv#10701]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

I find automating workers to be pretty much useless, because they immediately head off to some other city and get captured by barbarians on the way.

### Desired Solution

I'd love a setting for workers to never leave your borders when finding a new job.

### Alternative Approaches

Alternatively stay focused on the city they are working on.

**Comment by The-Talik** [comment]
Huh?

**Comment by The-Talik** [comment]
Yeah, In early game I spread my cities out quite a bit, so maybe that exacerbated the problem while a dense cluster of cities wouldn't be prone to it.  I've even had them try to cross oceans.  In any case, having workers never leave population border seems like it would be an easy, and clean fix.

**Comment by itanasi** [comment]
The problem is that isn't desirable behavior. Especially early game you want your Workers to move outside your borders to help new cities and build Roads outside your borders to connect cities.

We already have code to try and avoid enemies, but it's a tough mix of conditions. We try to only work tiles at least 3 tiles away from an enemy and while moving there's code to avoid enemies in movement distance, but it isn't fully robust. Maybe prohibit movement to within 3 tiles of an enemy could help.

**Comment by SeventhM** [comment]
Probing for relevancy. Probably should ping @tuvus. Wouldn't know the solution and I kinda don't use automation enough to know when this is no longer an issue. Though, tbh, I feel like this often feels more like the problem also may be to do with poor attempts by automation to protect units. The few times I do use automation (such as to test a bug or to watch the AIs play... again usually testing stuff), it feels like the AIs struggles to keep enough units alive to protect against barbs, where a good player can fight off barbs with a shockingly low number of units

**Comment by itanasi** [comment]
The actual solution is AI should guard their Workers and Workers shouldn't wander without protection. Which isn't the most straightforward thing in the world

**Comment by tuvus** [comment]
> The actual solution is AI should guard their Workers and Workers shouldn't wander without protection. Which isn't the most straightforward thing in the world

I agree. I have been thinking of how to implement this but it seems difficult. We need a few military units to do like a guard/fog busting around the most dangerous areas with workers.
The first problem is getting only a few military units to do this.

**Comment by itanasi** [comment]
Right. Alternatively we need to have a new layer that coordinates or allows the units to communicate so that they move in tandem. Worker says I want to go to X, determines it's dangerous, gets assigned a guard to walk with them as escort.

We have code that tries to cover up unprotected Workers, but since right now Units act serially if a Worker mives and there's no Military unit after it, they maybbe uncovered or one isn't in range because there's no coordination.

**Comment by tuvus** [comment]
> We have code that tries to cover up unprotected Workers

We do? There's `tryAccompanySettlerOrGreatPerson()` and `tryFogBust()` but those don't do that much.

**Comment by itanasi** [comment]
Hm must have been thinking of the Settler/GreatPerson code off the top of my head. We probably can extend that to cover Workers outside/near edge of borders if an enemy is in vision/range
