### ISSUE TITLE
Polynesia cannot immediately embark on turn zero

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

from source

### Describe the bug

Polynesian units should be able to embark on turn 0, right?

### Steps to Reproduce

- Start a new game as Polynesia, 1 other civ, 0 city-states, on this map:
```
H4sIAAAAAAAA/7VZ0W7aMBT9FeSnTUoqEhIqeNuQ2DS1WjVQ+zD1wUs8YinYyHY2GOLfd0NYy5Q42MaVeAiGe3xzzvG9drJHa7x5wAKviSJCoukeMbhGU7QkUg02WBU/KcspW6EAqd2m/mVWScXX8F0W+DjwjWQKs1VVYgGjALigf0gNJXBOKwBNA/Sb5qpA02gcoILQVaGOo6e5ToiHAGWCYEXyJ6qKR8iHcgY/JzeTm+g2hGSyIhq8+1jRMh9M0uR9nQMhOcDeDhP4xGkcDScAo2hJ7qiESb7v0YZLqo5Ie7RF0zhAOzQNx/C3H1iSJREC03qaZcVygQFTEMkrkdWZzSsgBVIGLC4gbF/nyJmijDBAjw5BC3/U4Kct/E8CS1lillsCJg1g4g0wbQBHvYCqGZ2DHhUQAkyiOYcLhZ7tZhs3s8Xe0o9NCO5I/x4LWdhmP/JNfmJCvoOa/vg9CRb1Ap6tkQUtfxFhOUnke5XEJkJ5M/VIp+KMY0D7D0xvgrZm/8LPSxAF114CTE00c9DHms4vFVuVxJbO+Do6R76XQKKj0ywfT672W3ii6ziOdRzf84qp+tJQJX8etTbnZ1qWVta8hrDojfqeP/789aBmvfjLLNSa9WtG8AWr9VdWI9H0C9+2MBuV+KcCl0QaLiDXohRqDWnIaXtig8BtV8JmcbHmds2iG7KcbrYmS1vuDOO1RtLEOxF7FUGxF4Lc3egSeIX9I83t2nQ/11YQalvfy5lTVx2Hndxr8+hoeh8Ub3U9vWPdangry06qNeeHGVYKtox2HEQaQZyy3TofyLrl8VGn3fYNXUJYn/Mv7+H1irzB+auTY7d9cbfyPo3/qr9rqQlNrK3b3AYufF6UzU4Z33TqOrnxwSPUVW/nlEy8bkO/24GxM7XUN/2JQTnyVkROYnsvxv1SnT/MUpzZ9qKTHbyL6KkFvIros13a0TrjCoh10876Qa+j9RoV2+8FzDiC2aTCAgZWdzzDNbDsev1w9qyK4WYcPfByx4ikGPVXr5eAxaZ+5QKZoMPz4S8TVbn6xBkAAA==
```
- Try to embark that Warior

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/63000004/3c6b46c9-387a-4a08-b806-a5f945decf22)

### Operating System

Windows

### Additional Information

... Works fine on turn 1...

**Comment by SeventhM** [comment]
I'm probably a bit slow on understanding what's going on, so typing things out as I try to understand it

gameInfo.setTransients already runs civ.setTransients. That should've already run tech.setTransients, which should've fixed the era. So by default I kinda don't understand how running setTransients a second time fixes things

Trying save... NPE in TileMap.setTransients. Actually, I noticed things weren't working because there somehow there was no civs by this point in the process either. Guess I'll create my own game. Let's see... civ is at era -1 because it has no techs... Ah... And the ruleset gets it an era via the starting tech of Agriculture. ~~Huh, haven't thought about this before but should we allow a system where mods have no starting tech?~~ Still... that should set the era correctly... AH...

10897 is likely the wrong approach. issue is TechManager is likely doing stuff out of order. `moveToNewEra` should happen much earlier, after `addTechToTransients`

**Comment by SeventhM** [comment]
> ... but without Agriculture that fixes the era at -1

Just thinking... Is "aloud" the right word? More accurately, if add technology is functioning properly, you shouldn't need to redo its transients after its done. That should work by default. So reordering addTechnology to function correctly seems like a given, whether we need to repeat civ.setTransients or not

> It says "on this map"

Whoops. I even noted the wording and still thought nothing of it

> Perfectly valid if they know their era number is -1

Do we have a way for mod creators to check for column number or era number? Pretty sure we don't, but I could be wrong. And even if we did, I doubt most modders or players would expect to start of in the "not an era" era

> fixed by simply moving

Hold up, let's slow down and think about it: which scenarios needs the eras to be correct? In theory that's
- Any triggerable, except for ones without trigger conditionals (see 10893)
- Any cached value relying on uniques. Pretty sure outside of my reorder of addTechnology, mapUnitCache is the only thing that actually matters here. So maybe we put addCivTechs before addCivStartingUnits. But also, how come addTechnology doesn't already address this? It comes up mid game too sometimes
- Or any misc. unique we happen to check. That almost exclusively means starting techs/policies. The former can't be adjusted for unless we just set the starting era ahead of time and called it a day (actually, why don't we just do that?) The latter... I mean... I guess, but now I'm wondering how common mods adjust starting techs/policies manually with your era choice. Besides that... I don't really think there's too many other examples of it mattering. Maybe starting units too, I suppose
