### ISSUE TITLE
Instead of automatically launching city attacks at the end of each turn by default, a switch for "initiating city attacks" should be added.

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#10938]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Automatic city attacks are beneficial in most cases, but in some special scenarios, such as in CoeHarMod, where cities without walls have -100% attack power, it means that every automatic city attack is pointless. In online multiplayer games, this bug has even been exploited as a way to unfairly gain experience for units, which is an unhealthy gameplay practice. Therefore, I propose adding a switch for "initiating city attacks" instead of having them occur automatically at the end of each turn by default.

### Related Issue Links

Nothing.

### Desired Solution

Nothing.

### Alternative Approaches

Nothing.

**Comment by AutumnPizazz** [comment]
Adding a switch seems to be a more reasonable solution.

**Comment by yairm210** [comment]
Sounds to *me* like attack power 0 bombardment should be disallowed entirely. Don't tell you you 'can bombard' if you have 0 power, that's nonsense regardless of automation.

**Comment by AutumnPizazz** [comment]
I apologize for the confusion in our previous responses. It seems there was a misunderstanding about the focus of your request. I specifically asked about adding a button to toggle automatic city attacks, and our discussion about zero-damage attacks not giving experience was tangential to that.

**Comment by SeventhM** [comment]
> then your original problem would be gone too, right?

Idk. I've heard of people complain about this outside this context as well

**Comment by yairm210** [comment]
Okay, now we've established these are 2 separate issues - THIS capital-I Issue is for the *user's* ability to turn off auto-bombard

Regarding the other issues that arose:

I think *City.canBombard()* (not CityCombatant.canAttack()) should contain the getAttackingStrength() > 0 check, but for that to happen the getAttackingStrength should go in City and not in CityCombatant 🤔 
Otherwise we get a weird situation where "can bombard" is true but "can attack" is false and that's both confusing and potentially messes up code

Regarding "should cities be able to bombard at health 1" I think the answer is yes but I'd rather we check in original Civ - @ravignir

**Comment by SeventhM** [comment]
> "should cities be able to bombard at health 1"

Should definitely test in Civ 5 (I don't have a way to play it currently), but I vaguely remember people saying cities attack at full strength even with 0 hp
