### ISSUE TITLE
Clearing a barbarian camp on a tile you own leaves the "improvement" behind

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#10963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

from current source

### Describe the bug

See title?

### Steps to Reproduce

1. Found a city 2 tiles from a barbarian camp
2. Buy the tiles around the city including the camp
3. Buy a Knight and use it to clear that camp next turn
4. You get the clear notification and the gold, but the tile "improvement" stays.

### Screenshots

![image](https://github.com/yairm210/Unciv/assets/63000004/f3d2332f-62a7-4f22-8940-771b678fedfc)

### Link to save file

Will need to try to repro on a smaller map

### Operating System

Windows

### Additional Information

Found #6560, but I doubt there's a connection.

The bogus improvement disappears on save/reload or next-turn. Console `tile removeimprovement` has no effect. Aha! That nasty lastSeenImprovement again! `selectedTile.getOwner().lastSeenImprovement[selectedTile.position]` - there it is.

**Comment by SeventhM** [comment]
I wonder if this lastSeenImprovenent problem is related to a similar issue: if you place an improvement via console, it won't update correctly unless you reload/go to next tirn

**Comment by SeventhM** [comment]
> And why does it seem to work **_at all_** when you "normally" clear a camp??????

I suspect it has something to do with unit movement. It's normally supposed to call `MapUnit.updateVisibleTiles` upon moving anywhere. Let's see, yep, there you find
```kotlin
// Don't bother updating if all previous and current viewable tiles are within our borders
```

**Comment by SeventhM** [comment]
> feels like a kludge.

Well, similar to improvement triggers, if you're only updating for 1 civ, rather than all civs, you don't need hasGameInfo. Hence me wondering why your patch does it when none of the other places that update improvements currently do. Probably a bigger discussion to be had about updating viewable tiles though. Probably stuff needs to be double checked, but I doubt there's that much harm in using the high level version instead of directly setting the improvement. It's not like addTechnology where we need to update eras and multiple caches

**Comment by SeventhM** [comment]
Given its impact as a console bug, I'll unstale this here. I need to look over this again, But like I said before, Trog's patch, albeit edited a bit to not update everyone's vision unnecessarily and to work (or, uh, not work) with tile clones should be fine enough
