### ISSUE TITLE
Effect "<for [amount] turns> <upon being defeated>" not working

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.11

### Describe the bug

I attempted to give a unit a temporary civ-wide effect that kicks in when the unit gets defeated: `"[+100]% Strength <for [Military] units> <for [50] turns> <upon being defeated>"` It isn't working. After the unit is defeated, the strength boost fails to take effect.

### Steps to Reproduce

This mod contains a simple unit that has the specified effect. 
[TestUponDefeat.zip](https://github.com/yairm210/Unciv/files/14353690/TestUponDefeat.zip)

### Operating System

Windows

**Comment by SpacedOutChicken** [comment]
In that case, is there a functional way of doing what I'm trying to do? I'd love to be able to kick-start other temporary effects by expending units. Imagine something like `"[+2 Science] [in all cities] <for [10] turns> <by consuming this unit>"`. Can that be done with existing uniques? If not, I'll make it a modding request.

**Comment by SpacedOutChicken** [comment]
Sorry for not including a saved game, but the setup is easy enough. You build the Sacrificial Lamb unit, which has a strength of 1 and the specified unique, and then you send the Sacrificial Lamb out to get killed by a Barbarian unit. I can attach a saved game later if you need one.

**Comment by SpacedOutChicken** [comment]
> Aside: If we get that working it will be quite probably cumulative - lose 20 units in one turn -> have +2000% bonus.
Sounds like fun to me. It's not likely to come up in what I'm working on, but it would be interesting to have an OP faction that just gets stronger and stronger as wars progress...

**Comment by SpacedOutChicken** [comment]
I swear that I'm not proposing these things to be difficult. I'm just trying to come up with something cool.

**Comment by SeventhM** [comment]
I would probably need to read this further to fully understand what Trog is saying (kinda busy rn), but something tells me Trog is over complicating things
`<for [amount] turns>` currently only adds a unique to the Civ's global uniques. If the unique for the unit doesn't check global uniques, it won't seem to work. Maybe the solution is to allow someway to allow units themselves to have temporary uniques? Sounds complicated but potentially doable, would need to check later and see if it creates any weirdness regarding assuming where a unique comes from

**Comment by SeventhM** [comment]
> Imagine something like `"[+2 Science] [in all cities] <for [10] turns> <by consuming this unit>"`

I believe this already works. Would need to double check

**Comment by SeventhM** [comment]
Completely missed the patch. Why doesn't `getTriggeredUniques` work with `ConditionalTimedUnique`? Because it adds to civ uniques? Not sure that's reason enough

Actually, I need to check... Does that patch do... Anything? Seems like a refactor more than anything wait... Did I accidentally break conditional timed uniques further? Needs testing

**Comment by SeventhM** [comment]
Would edit last message, but I'll be annoying and double post

> because MapUnit.getTriggeredUniques doesn't see the entire Unique long before that code (the civInfo.temporaryUniques.add(TemporaryUnique... line) has a chance

Not true. The reason it's not seen is because apparently `UniqueMap.addUnique` strips out all uniques with timed conditionals. usually a good idea, fails us here because we actually want the unique this time. Your patch works because `getAllUniquesUncached()` has the uniques before they are added to the UniqueMap. I suspect we should still find a way to cache both the map and the objects in MapUnit.


That said... that is an interesting way that `getTriggeredUniques` fails us, not just here. Probably there's a better way to cache this and use this within `UniqueMap` itself

**Comment by SpacedOutChicken** [comment]
> > Imagine something like `"[+2 Science] [in all cities] <for [10] turns> <by consuming this unit>"`
> 
> I believe this already works. Would need to double check

I tested it out and it doesn't work. The game doesn't give you the option of expending the unit to create the temporary effect.

**Comment by SeventhM** [comment]
> (likely point 4 below)

Yeah. That's neat. Willing look into setting it up at some point. Didn't even know that the blockquoting had a diff mode
