### ISSUE TITLE
Exploit with pillage and repair tile improvement on enemy's lands

### ISSUE THREAD

**Issue by NoobTutorial** [yairm210/Unciv#11174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

Current from flatpak, Gods and Kings

### Describe the bug

At first, thanks for authors/developers for this great game.
I found now how I can cheat opponents with some sort of bug.
Workers can repairs looted improvements on enemy's land. And player can use it as infinite heal resource for battle units.

### Steps to Reproduce

1. Go to battle or siege on enemy land, move syncronously your workers on same tiles where you move your warriors. These tiles must have improvements for looting.
2. When your warrior takes damage – loot the improvement on tile where warrior stays. Warrior takes some heal. This is normal game logic.
3. But, next starts some sort of cheating: give an order to worker to repair the improvement under warrior. It takes 1 turn only, so on next turn you can heal warrior one more time.
4. Repeat this combination as many times as possible. Your warriors become forever healed while he stays on tile with improvement, and worker with him. Opponent can't kill workers, he can only try to kill virtually immortal warriors.
5. In most cases you can do this indefinitely. Beat the opponent's unit, take some damage – heal – repair source of healing.

### Operating System

Linux

### Additional Information

Of course, this cheat only works if your workers can repair looted improvements in 1 turn. Though, they do this in 1 turn in most cases.

I think there should be some restrictions for such cheat. For example, workers can't repair improvements on enemy land. Or should the repair take more than 1 turn in time.

**Comment by yairm210** [comment]
Pillage should be allowed *only* in enemy land! The repair should be limited, and I thought it was, we'll need to check this

**Comment by SpacedOutChicken** [comment]
> As in - current Unciv, older Unciv, or original Civ5?

Current Unciv. I don't know if it works in the original Civ V. 

> Repair in own - YES, repair in friendly (including allied and neutral CS, or open borders???) - yes, repair in neutral - no, repair in enemy - NO.

I can think of one case where you'd want to repair improvements in neutral territory: if you've got a road outside your borders and someone pillages it, you should be able to fix it. This might also apply to forts and roads within enemy territory, because you want to be able to fix those for your own sake.

**Comment by SpacedOutChicken** [comment]
At the very least, since it is possible to build roads and forts in neutral territory, it should be possible to maintain roads and forts in neutral territory. If you have to do so by building a new road or fort, that's fine, as long as you have some way of fixing things. I think that's both fair and realistic.

As for fixing pillaged improvements in enemy territory, it makes sense to disallow that, but would doing so complicate the code for the repair action?

**Comment by yairm210** [comment]
I think you can only see that because of your repo privilege 😜
A comment will suffice :)
