### ISSUE TITLE
'Cannot move' cannot be added with some filters

### ISSUE THREAD

**Issue by AutumnPizazz** [yairm210/Unciv#11193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.10.11

### Describe the bug

![Image_1708829989099](https://github.com/yairm210/Unciv/assets/114050365/6257ad0a-d05e-4f81-ac1f-f041b8b7f82e)
![Image_1708829987963](https://github.com/yairm210/Unciv/assets/114050365/ead458ec-aa60-4a81-9873-1ddf3999318e)

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

Android

**Comment by SeventhM** [comment]
Between discord and here, this is suspiciously the second time hp conditionals aren't working. Shouldn't the unit also have more sight in this screenshot. I need to go check something

**Comment by yairm210** [comment]
This unique is *documentedly* cached, and therefore may not update according to circumstances.
![image](https://github.com/yairm210/Unciv/assets/8366208/aea222e7-b3a0-458d-b473-513be14fc2fa)

**Comment by SeventhM** [comment]
@yairm210 Pretty sure the issue was closed prematurely. Conditional [erroneously assumes combatant ](https://github.com/yairm210/Unciv/blob/72fa2a3f48231d9573b907cfbfa2129caa89a153/core/src/com/unciv/models/ruleset/unique/Conditionals.kt#L206). It wouldn't have worked even if it wasn't cached. Hence my comment regarding the sight unique also seemingly failing in that screenshot

**Comment by yairm210** [comment]
Ohhh interesting!
