### ISSUE TITLE
Feature request: AutoPlay needs to be made concurrent

### ISSUE THREAD

**Issue by tuvus** [yairm210/Unciv#11269]
### Problem Description

Using AutoPlay in the later game causes the game to freeze since the AI play is being done on the same thread.

### Related Issue Links

#10315

### Desired Solution

The solution to the problem is to move the AutoPlay to another thread. However I believe this will cause a problem if we allow the player to continue making clicks and movements to the game. Therefore, I am led to believe a more elaborate movement-locking feature would need to be implemented.

**Comment by yairm210** [comment]
Let's talk about next turn, since it had the same problem

How does next turn work?
- clone game state
- change worldscreen to be "read only" state - players can explore the current world but cannot take action
- process next turn for clone in another thread
- when other thread finishes, replace the world screen

Sounds like you want something similar - only in your case you can replace the world screen on every turn, but keep it "read only"

**Comment by yairm210** [comment]
That is to say - add a onTurnComplete callback parameter to next turn
NextTurn should not be aware of UI directly, it just clones the game state on every turn end and calls the function - which can be on another thread
The latency cost of cloning the game state every turn is the major cost here

**Comment by tuvus** [comment]
The way we made it "read only" in the past was by changing the viewing civ... Could we set the viewing civ to none and set the selected civ to the original civ like in Spectator? 
The spectator needs to view each civ as if they were them without being able to modify them. We might be able to reuse this to apply the locking mechanism.

**Comment by yairm210** [comment]
No, we just set isPlayersTurn to false
https://github.com/yairm210/Unciv/blob/86f0ed6e85aae28aea6ccd3fc45e311dad793f38/core/src/com/unciv/ui/screens/worldscreen/WorldScreen.kt#L584

**Comment by tuvus** [comment]
Why did I not realize this? AutoPlay already does that in order to lock the screen.
