### ISSUE TITLE
Resource spawn rate dwindled

### ISSUE THREAD

**Issue by GeneralWadaling** [yairm210/Unciv#11411]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4.11.1

### Describe the bug

The resource spawn in mods seem to have affected after updating the main game.
This is discovered when running mod Alpha Frontier, generating new random maps with abundant resource settings.
The used to be rich resource spawn is no longer recreate-able in newest version.

See the image section for contrast. VERY OBVIOUS CONTRAST.

### Steps to Reproduce

Run it on 4.10.21 compared to current version with mod Alpha Frontier. You'll see the MASSIVE difference in resource spawn.

### Screenshots

The resource spawn now
![image](https://github.com/yairm210/Unciv/assets/57716526/4c0ccfec-5192-4a28-8713-6c7e48c7b641)

The resource spawn then
![image](https://github.com/yairm210/Unciv/assets/57716526/2dd22a92-da41-416f-ac06-d3cc9afcc52b)

### Link to save file

Not applicable

### Operating System

Windows

### Additional Information

Not applicable

**Comment by GeneralWadaling** [comment]
Further tested with latest 4.10 compared to current 4.11, pretty sure something must have happened with 4.11 update causing this

**Comment by yairm210** [comment]
Thanks for investigating this!
Found the problem - Alpha Frontier uses multi-parameter uniques for placing resources (`"Generated on every [28] tiles <in [Featureless] [Tundra] tiles>"`) which has been deprecated in favor of multifilter (`"Generated on every [28] tiles <in [Featureless] [Tundra] tiles>"`)

Checking the mod checker, I can see that these were indeed NOT caught, so that's on us

So the fix is in two places:
- Alpha Frontier should convert their resource placement uniques
- We need to ensure that mod checker catches uniques on resources

**Comment by yairm210** [comment]
AHA
This is actually better than I thought - turns out we don't check deprecation of conditionals AT ALL
So that's on us

**Comment by yairm210** [comment]
Our side is solved in 773d996b, now Alpha Frontier needs to change their resource uniques
