### ISSUE TITLE
RFC: Fly-by observations (and mini-bugs) concerning Espionage

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#11569]
One for @tuvus , maybe even @ravignir if still listening, but any voice welcome (and sorry for the label mix - this **is** a mixed bag):

### UX
* A spy in surveillance will pop the mandatory espionage screen visit **_every darn turn_**
* Notifications *could* open the espionage screen, might be nicer
* Column "spy present" for the "hideout" row could show idling spy(spies)
* Those Move buttons are _F A R_ too big
* Which spy is to be moved could be clearer
* Spy icon could indicate rank
* Interaction on city name - show on map?

### Rules / bugs
* National Intelligence Agency gives the extra new spy two ranks not one
* If a spy fails and is killed during a tech spy attempt - the tech is rewarded anyway without notice
* Tech steal success rate seems too high - because minimum rank already shifts probs???
* Cannot station spy for counter-intelligence
* Fixing that - they do "establish network" for the same duration as abroad which maybe they shouldn't

I'm currently partitioning into readable commits - but any input would be nice on:
* establish network duration: I changed it to 3 for abroad 1 domestic - could be zero? as in just 1 turns in the moving state when going from hideout  to counter-intelligence??? The fandom wiki is not clear - someone got other sources?
* Success/fail probabilities: I haven't coded or tested it - but I'd tend to make rank 0 have zero "skill modifier", shifting outcome to 0% unnoticed success | 33% noticed but unrecognized success | 33% victim-knows-whodunnit success | 33% fail+kill. **Unnoticed** success chance is then directly proportional to levelups, capping at ~20% overall, and fail+kill chance is never virtually zero, an overall ~13% remaining at rank 3 without counteragents. Yes, Oscar's math is linear throughout, and I haven't checked the DLL sources on whether that general model is even close to the original - playable it certainly is.
* Vague idea - show modifiers from uniques somehow. The numbers are easy, but their effect and thus presentation is not. Rank influences tech steal success rate while Uniques influence tech steal speed, completely independent from each other - unintuitive by definition. "Success modifier: X%, speed modifier: Y%"??? Maybe, but effect on other tasks is entirely different......

<details><summary>appetizer</summary>

![image](https://github.com/yairm210/Unciv/assets/63000004/6825dba7-2f07-431b-be92-fefb527d2f07)

</details>

### Related Issue Links

#11557, #11077, #7665... And the mothership: "Implementation of Espionage - Roadmap #7610" - some of these checkboxes could be toggled by now via tuvus's work, and one half by my upcoming PR.

**Comment by tuvus** [comment]
<details><summary>Replies</summary>

> If a spy fails and is killed during a tech spy attempt - the tech is rewarded anyway without notice

Oops, I though that I had fixed that in one of my PRs.

> establish network duration: I changed it to 3 for abroad 1 domestic 

I believe counter-intelligence should commence immediately, so that would mean 0 domestic.

Feel free to change the chances. I think I took the stealTech() random chance from the DLL but might have guessed at a few numbers.

> Notifications could open the espionage screen, might be nicer

I meant to do this and it looks like I forgot.

> A spy in surveillance will pop the mandatory espionage screen visit every darn turn

That was mostly intentional, although on second thought it might not be as good. What should the solution to this be? There is a notification if the spy no longer has tech to steal.

> Spy icon could indicate rank

Do we want to make the spy rank moddable? In that case an image might not be as good.

> Interaction on city name - show on map?

I was thinking about this. If we add an alternative move button that allows the player to select cities on the map instead of using the table.

> Another one: I guess spies are ordered by age on the left side, initially, but deaths keep their place and are filled in - is that for the best?

I haven't touched that yet. Xander Lenstra did a lot of the foundation work.

> Oh - forgot one: How to operate that screen via Keyboard... Do we need "cursors", a moveable highlight depending on context??? Or is there some easier way?

I use espionage on my phone and it doesn't seem to have any problems if that is what you are wondering.

</details> 

Also I think we need to keep in mind that the move to button associated with each city will need to open a panel which allows the player to choose which action the spy will take. Moving a spy to a city-state for example would have the options of rigging the election and executing a coup which happens immediately (we might want to change that to be next turn for save scumming reasons). The coup option needs to show a success rate percent I think.

How much of this were you planning to fix? (So we don't double fix a problem)

**Comment by tuvus** [comment]
I think that looks good, A rank 1 spy has a %76 chance of success with no defender. While at the same time having a defending spy has value so players should want to defend their biggest cities.

> Next - speed

This seems like you are calculating an extreme case here. From what I read each Constabulary, Police station, National Intelligence Agency should cancel out a single spy level.

Also, the AI isn't very good at scouting right now so it isn't as good at finding city-centers to put spies in later.
