### ISSUE TITLE
Escorted movement crash

### ISSUE THREAD

**Issue by MitjaCernko** [yairm210/Unciv#11562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.9 (build 993)

### Describe the bug

Game crashes when trying to proceed to the next turn, due to a scheduled movement of an escorted pair of units (Great General and Mechanized Infantry).

### Steps to Reproduce

1. Load save attached below and proceed to next turn (crash).
2. Reload and find the only unit with a "Moving" action (last Mechanized Infantry unit).
3. Either break the escort or cancel the move to prevent the crash.

### Link to save file

Error report and save:
https://pastebin.com/J0m26VZN

### Operating System

Android

### Additional Information

After encountering the crash scenario (post-win state), I narrowed down the problematic movement orders until only one unit remained and still triggered the crash.

The only noteworthy hints might be that I remember linking and unlinking the pair of units multiple times in the preceeding turn(s), possibly while embarked. Also, I noticed that the "Moving" action is listed with only one of the units (not sure if it's intentional).

**Comment by tuvus** [comment]
Ooooh, that's an annoying bug. I see what the problem is now. 
The mechanized infantry along with the great general are trying to reach the destination (-31, -13). Both of them try and find their own path to the tile to move to this turn (-30, -13). However, because the mechanized infantry has 3 movement and is directing the movement it can move through the hill at (-29, -13) with no problem. The great general on the other hand moves there and uses up all of it's movement so it can't move to (-30, -13) when the mechanized infantry wants to, so it raises an error.

Now to try and work out a fix...

**Comment by tuvus** [comment]
For a report on this bug, I did try out a solution but encountered some serious errors on the way. I would estimate that fixing this would take a lot of time which I don't currently have. Considering that the AI doesn't use it, most players probably won't encounter this and that players can keep on playing by unlinking the units, I am going to be putting it on a low priority. I'll see when I have time to look into it farther.

Thanks for reporting this though!
