### ISSUE TITLE
"when below [amount] [resource]" causing crash with city-level resources

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#11674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.11.16

### Describe the bug

If you create a building with a unique like `"Provides [1] [Coal] <when above [-2] [Stuff]>"` and that "Stuff" is a city-level resource, it crashes the game.

This file includes the stack trace: 
[StackTrace.txt](https://github.com/user-attachments/files/15515706/StackTrace.txt)

### Steps to Reproduce

1. Create mod with city-level resource and building that includes the "when below [amount] [resource]" unique
2. Build or purchase that building in a city
3. Game will crash

### Screenshots

![Screenshot (195)](https://github.com/yairm210/Unciv/assets/58439827/f0a6b189-01f5-4e93-930b-e7b20e020697)

### Link to save file

This mod includes a city-level resource called "Stuff" and a "Check" building that provides 1 Coal when below -2 Stuff.
[CityLevelTest.zip](https://github.com/user-attachments/files/15515645/CityLevelTest.zip)

### Operating System

Android

### Additional Information

Changing it to "when above [-2] [Stuff]" causes the same error.

**Comment by yairm210** [comment]
Aha
So the problem here isn't of the *conditional* or of the *unique* - it's a problem of *recursion*

To figure out if this unique applies, it needs to get the local resources of this city, for which it needs to evaluate all resource-providing uniques, for which it needs to figure out if this unique applies!

That is to say, the conditional would work well on all other uniques
I'll add a doc warning and a ruleset check for this situation, it's not something that I can think of a good permanent fix for - the only other alternative is calculating local city resources every time something would change for them, which is both a big change and a lot of CPU work for this edge case

**Comment by yairm210** [comment]
Added a check for it here https://github.com/yairm210/Unciv/commit/834567170ea616bcbe8053026a3d0515a5d0ab90

**Comment by yairm210** [comment]
Don't like that solution tbh.
Once we reach that recursion level, we return what? Zero? 
I'd rather tell modders outright "wait, that's illegal" rather than return a not-real answer for an unanswerable question

**Comment by yairm210** [comment]
Going back to this again, I don't think there's anything we can do about this other than warn
Since the warnings are in place, I'm closing this
Thanks for detailing this @SpacedOutChicken , sometimes there just is no good resolution :(
