### ISSUE TITLE
Weird unit unselecting bug after update

### ISSUE THREAD

**Issue by 3009dudestop** [yairm210/Unciv#12027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.12.14

### Describe the bug

Before the update, it used to be that when a unit uses up all its movement points, it unselects the unit and automatically selects the next unit, and when the unit moves but still has leftover movement points, it remains selected until you either use up all points or manually unselect the unit.

But since the update (version 4.12.14 Android) it seems like it happens the other way around now, weirdly. When you use up all points, the unit remains selected, whereas when you move the unit and still have leftover points, it decides to unselect it/select the next unit, which is quite annoying.

### Steps to Reproduce

1. Select any unit in game
2. Move the unit until all movement points are used up
3. You shall see that the unit remains selected

4. Select another unit
5. Move it, but not fully (e.g. if the unit has 4 total movement points, move it only 1 tile so you still have 3/4 points left)
6. The unit will automatically unselect itself

### Screenshots

https://github.com/user-attachments/assets/57c36a23-4a9a-4d70-b70d-9d50a110d0b6

https://github.com/user-attachments/assets/9e98b74b-0c3f-4f0a-830f-d49e0192f15b

### Operating System

Android

**Comment by vincemolnar** [comment]
It was this commit: https://github.com/yairm210/Unciv/commit/fe9ba086908537cc6c569914646190b990be1457
It seems the helper function was inserted with find and replace which caused a syntax error due to the negation inserted into the middle of the name. The replace broke other identifiers, too, and this one was also fixed the same way - without keeping the negation.
So the good news is that it is really just an exclamation mark and it's fixed!

**Comment by yairm210** [comment]
Nice hunting!!!
Yes, that looks like it, will fix tomorrow :)
