### ISSUE TITLE
Iroquois UA The Great Warpath does not grant Railroad production bonuses as it does in civ 5

### ISSUE THREAD

**Issue by legacymtgsalvationuser69544** [yairm210/Unciv#12261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.13.13

### Describe the bug

Iroquois treat forest as roads in civ 5 and in game once you research railroads any cities connected only by forests will receive the Railroad production bonus.

In unciv you do not receive the bonus until you build railroads on all of your road network.

NOTE: This behavior is not well documented in the civ 5 text but is how the ability works in game.

### Steps to Reproduce

1. play as iroquois and build two towns connected by forests
2. complete railroads research and pass turn

Results:
Cities with only forest/jungle road connections do not have the Railroad Production bonus

Expected Results:
Cities connected with only forest roads now get a 25% Railroad connection production bonus

### Screenshots

![PSX_20241003_121534](https://github.com/user-attachments/assets/01a2c7bb-7634-41ef-bcfb-a8a459834201)

### Operating System

Android

**Comment by yairm210** [comment]
This sounds like a discrepancy in Civ V rules - if all jungles are like roads then they _shouldn't_ be considered railroads for production purposes!
The idea is that if you can quickly transport goods with railroads that yields a production bonus - moving fast through jungles may be possible, but not with industrial amounts of goods
If this is indeed the case in Civ V I'll explicitly add it to [intentional departures](https://yairm210.github.io/Unciv/Other/Intentional-departures-from-Civ-V/)

**Comment by legacymtgsalvationuser69544** [comment]
The game screenshot here is one I made to specifically test if this was true in Civ 5 as I had found some 11 year old forum post saying that this was how it worked.
