### ISSUE TITLE
Brazil default city names render with corrupted characters.

### ISSUE THREAD

**Issue by Joeputin100** [yairm210/Unciv#12403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.0

### Describe the bug

![Screenshot_2024-11-02-18-12-18-290](https://github.com/user-attachments/assets/c97fb255-7033-4be5-bc2b-b9afdc1b1412)

When I play as Brazil, the default city names have garbage characters in them. 

For example, São Paolo is rendered as seen in the screenshot above.

### Steps to Reproduce

1. Play any game as Brazil.
2. Found Rio de Jañeíro.
3. A few turns late, create a new settler.
4. Found the second city, see the default name is corrupted.

### Operating System

Android

**Comment by yairm210** [comment]
This is a *mod* issue - Brazil is not an Unciv nation.
It uses characters incompatible with your default font.
Option 1 is to change your font (Options > Advanced > Font family)
Option 2 is to tell the mod owners that this happens and ask to remove non-ascii characters from city names
I would personally go with 1 because the mod owners probably felt that the native city name is important
