### ISSUE TITLE
Feature request: 32 Native American Nations Expansion

### ISSUE THREAD

**Issue by Eye4anEye** [yairm210/Unciv#12517]
### Before creating

- [X] This is NOT a gameplay feature from Civ VI, BNW, or outside - see Roadmap
- [X] This is NOT a gameplay feature from Vanilla Civ V or from G&K - If so, it should be a comment in https://github.com/yairm210/Unciv/issues/4697

### Problem Description

Im new to github, im just trying to reach out with a request, but cant find out where im supposed to go! lol sorry
Im playing unciv on android and noticed the mods section and wouldnt ya know it, ive almost downloaded everything. But whats missing is Native Civis! It would be so cool if someone could make it

### Desired Solution

The Creation of the 32 Native American Nations expansion.
1. Apache 2. Abenaki 3. Aleut 4. Arapaho 5. Cherokee 6. Chickasaw 7. Choctaw 8. Creek 9. Crow 10. Cheyenne 11. Chumash 12. Iroquois 13. Inuit 14. Lenape 15. Massachuset 16. Miami 17. Navajo 18. Nez Perce 19. Natchez 20. Paiute 21. Pawnee 22. Pomo 23. Pueblo 24. Powhatan 25. Pequot 26. Sioux 27. Shoshone 28. Shawnee 29. Seminole 30. Tlingit 31. Ute 32. Yakima

### Alternative Approaches

None?

**Comment by SeventhM** [comment]
Mods are not handled by us directly, but by our amazing community. If you want to request someone make a certain mod, you can definitely ask around our discord. I don't know where on GitHub you can ask someone to make a mod, though (unless you want to help make such a mod)

However, I will have to close this since we have no plans of making mods directly in this repo
