### ISSUE TITLE
Defensive pact involve the 4th nations in the war

### ISSUE THREAD

**Issue by DeStup** [yairm210/Unciv#12564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.12-patch2 (Build 1079)

### Describe the bug

Byzantium has defense pacts with China and Siam. 
I expect that India will fight with Siam and Byzantium when attacking Siam. But for some reason, when an attack is launched, war is declared on the China too. 
Although the goal of the war is Siam, the China joined the chain to Byzantium. 
Such alliances work in a chain, and you can fight with the whole map, although it has nothing to do with it.

### Steps to Reproduce

Declare war on Siam.
file bellow

### Screenshots

![image](https://github.com/user-attachments/assets/ebab9845-78ac-4820-8a87-4ff6cc249bdb)
![image](https://github.com/user-attachments/assets/5936a130-395b-4a72-9da1-c43e7e435305)

### Link to save file

[test2.txt](https://github.com/user-attachments/files/17998696/test2.txt)

### Operating System

Android

**Comment by czyh2022** [comment]
I looked at the code and found that the mechanism of the defense pact chain was intentionally written into it. However, in civ5, it seems that defensive pacts should not work in a chain reaction (see https://www.reddit.com/r/civ5/comments/956ui0/do_defensive_pacts_work_in_a_chain_reaction/). 

According to the link above, a defense pact should only work if war is declared on one of the parties, at which point the other party should be considered to have actively joined the war, rather than also being declared war on. Therefore, the party assisting in the war in a defense pact should not trigger further chains.

I support removing the chain triggering mechanism from the defense pact because it would cause the signatories to fight for a civilization they did not anticipate having to protect. The current defense pact is only signed bilaterally, not multilaterally. As a result, when a new defense pact is about to be signed, the other parties in the existing defense pacts can neither know nor influence it, so they have no reason to fight for it. Perhaps a new feature could be added in the future to achieve a multilaterally signed military alliance.

**Comment by yairm210** [comment]
We polled this and it is scheduled for removal, haven't gotten around to it yet

**Comment by DeStup** [comment]
Thanks guys, this is an important fix for multiplayer ffa games
