### ISSUE TITLE
tileFilter unique failing to take effect when provided with multiple parameters

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#12572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.14.12

### Describe the bug

The `"[stats] from [tileFilter] tiles [cityFilter]"` unique is not kicking in when the tile filter is supplied multiple parameters. Even when the tile in question matches all the parameters, the effect won't kick in.

### Steps to Reproduce

I tested this out by creating a global unique of `"[+1 Gold, +2 Production] from [{Desert} {Farm}] tiles [in all cities]"`. It failed to have any effect on Farm improvements made in Desert tiles.

### Operating System

Windows

**Comment by abaddon431** [comment]
I think uniques with [tileFilter] would calculate from either only [terrainFilter] or only [improvementFilter], but not a combo of it.

**Comment by yairm210** [comment]
This is caused by a anciliarry problem...
When determining stat bonuses we need to divide them into "bonus from improvement" and "bonus from tile" because of e.g. "doubles improvement stats", so when you have a tilefilter *on this particular unique* that combines both it will fail.
You've caught a hell of an edge case
