### ISSUE TITLE
Itanasi to be fired and accounts set to zero.

### ISSUE THREAD

**Issue by 4ff0rdsUn1c0rns** [yairm210/Unciv#12702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Version

4.7.5

### Describe the bug

@yairm210; @itanasi to be terminated and accounts given to players; for malicious Discord management in # offTopic.
It's ***my gold*** being given away.
Others; use: Ghidra for your own confirmation.

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

It's logged.

### Operating System

Android

**Comment by yairm210** [comment]
I saw exactly what you wrote on Discord and here, you are making less than zero sense
Please get out of my house

**Comment by touhidurrr** [comment]
The issue looks dire indeed but sadly termination of GitHub or Discord accounts is a feature out of scope for this project. Kindly read readme https://github.com/yairm210/Unciv?tab=readme-ov-file#will-you-implement-feature for a better understanding of the scope of the project. Also, settings **accounts** to **0** looks like an interesting feature to be discussed. But I don't know how you are planning to implement that. You can try to implement it and open an pr. I hope the community will like it.

Also, some links you might be interested in are:
1. https://support.github.com/ (For help with termination of Bad actors in GitHub)
2. https://support.discord.com/hc/en-us (For help with termination of Bad actors in GitHub)

**Comment by SeventhM** [comment]
Are we jokingly pretending to take this seriously? I'm pretty sure even if something like this was in scope (there's almost an argument to claim that it is, tbh. Management of our discord/github probably should be in the scope of this project), the core issue is that it would be relatively impossible for us to actually do. I believe transferring a user account to a group of users likely would have plenty of legal concerns. If this issue was even remotely worth taking seriously, then as touhidurr suggested, the recommendation would be to terminate the accounts instead. However there is no good reason to do so in this case as discord moderators are granted some level of freedom (for good reason) on how they manage their servers, and as these actions happened purely on discord and is out of scope for any sort of github action

What I'm especially disappointed in is that lack of mention of how there is no statement of what to use Ghidra on, making the suggestion meaningless and technically meaning that it would be impossible to confirm what specifically is being referred to here
