### ISSUE TITLE
Display current total gold owned on City View screen

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#1637]
Users are allowed to purchase using gold while in the city screen, yet users are forced to exit the city screen to view their total gold. Having total gold shown on City screen is a quality of life issue.

**Comment by r3versi** [comment]
This is a good observation, the issue here is that this would need a change in the CityScreen UI (that is already pretty cluttered for lower resolutions. Maybe we could show only the first line of the WorldScreen (the one with Turn info, gold, science, etc) in the CityScreen too? It wouldn't take too much space

**Comment by JoshDM** [comment]
To the right of the "Buy for xxxx gold" oval can be a gold oval showing the current gold.

Alternately keep the bar at the top of the screen, but remove the elements that give it two rows of length (the options button and the menu button).  Then increase the width and positioning of the lower left rectangle to match the width and left positioning of the upper left rectangle, which should clear vertical space inside that rectangle, which can be used to give you back vertical clearance for the new half-header bar.

**Comment by r3versi** [comment]
I can try to fit this into #1479.

**Comment by JoshDM** [comment]
You can remove "from Queue" from the button and just make it add/remove, to
fit the gold amount there.

**Comment by r3versi** [comment]
Tbh I prefer the second option, but let's wait for @yairm210 opinion about this

**Comment by yairm210** [comment]
I didn't realize this was waiting for me 0_0
The 'add to queue' and 'remove from' texts should stay
Which leaves the question, 'so where do we fit this into the already crowded UI'

![image](https://user-images.githubusercontent.com/8366208/73750129-5154c380-4765-11ea-972f-26d53e850db1.png)

I suggest, instead of adding it into the UI, we add it into the confirmation popup.
![image](https://user-images.githubusercontent.com/8366208/73750180-66315700-4765-11ea-8564-e39a14f7f482.png)

We can add a line like 'You will have X gold left after purchasing'

**Comment by JoshDM** [comment]
As an FYI, "Add to Queue" is redundant.

"Queue" itself is a noun and a verb; the verb basically means "get in the
queue".  You can easily remove the "Add to"; also (dare I say it) the
"Buy", especially if there is a confirmation.
