### ISSUE TITLE
Bug report: The Oracle Cometh

### ISSUE THREAD

**Issue by shaness1** [yairm210/UnCiv#165]
If you complete The Oracle wonder on the same turn that you would get a social policy choice the *free* unlock takes the place of the one you earned. This probably means that the *free* unlock actually affects the cost of future unlocks all the time (my culture countdown went from 1 turn to 8 while it should have been 30+ for the next unlock)

**Comment by Am-per-Sand** [comment]
I confirm: instead of the policypicker window, policies countdown advanced after completing the Oracle.

BTW is `currentPlayerCiv.policies.freePolicies` and `civInfo.policies.freePolicies` the same property in the relevant files:

https://github.com/yairm210/UnCiv/search?q=freePolicies&unscoped_q=freePolicies

?

**Comment by yairm210** [comment]
If confirmed then we'll reopen and recheck

BTW, yes :)

**Comment by yairm210** [comment]
For me, building the oracle popped up the policy picker screen (pick free policy) and actually decreased the turns to next policy, because of the 3 culture it brings.

Is that what you meant?

**Comment by yairm210** [comment]
Everything works fine for me, awaiting your response

**Comment by yairm210** [comment]
I'm reclosing this, if you have more data you're welcome to reopen it again
