### ISSUE TITLE
Automated explore still trespasses city-states

### ISSUE THREAD

**Issue by lyrjie** [yairm210/Unciv#1814]
**Describe the bug**
Automated explore trespasses if the tile it can explore is located behind the city-state territory.

**To Reproduce**
1. Load [the save game](https://pastebin.com/raw/5UUaucDn)
2. Press "Next turn"
3. Warrior is in Kathmandu

**Expected behavior**
Autoexplore doesn't trespass.

**Screenshots**
![image](https://user-images.githubusercontent.com/26433289/73541318-2f94cd00-4443-11ea-9988-4c46514dcd26.png)

**Additional context**
The problem is `UnitAutomation.automatedExplore()` call. Algorithm only considers City States when choosing the destination tile, but not when deciding which route to take.

**Comment by yairm210** [comment]
Okay so apparently we had 2 similar functions in UnitAutomation, tryExplore() and automatedExplore()?
Not sure why
We fixed the problem in one but not in the other
I'll try and unify them

**Comment by yairm210** [comment]
HMMM
Even that wasn't enough, and the problem lies in pathfinding.
We can stop automated units from heading towards city state owned tiles, but how do we make them not move through city state owned tiles when pathfinding?
You'll have to 'discourage' units to do so, because if you disable it entirely, well, then you won't be able to have them enter city state territory even when you want them to... =/

**Comment by lyrjie** [comment]
We could add `respectCityStates` parameter to the `UnitMovementAlgorithms` and instantiate is locally in `automatedExplore` instead of using the `unit.movement` one.
Then just add checks in `UnitMovementAlgorithms` where needed

**Comment by yairm210** [comment]
That's not a bad idea!

**Comment by Kentalot** [comment]
Because of my work on #1736, I've been looking at pathfinding.  I'm thinking of implementing the A* algorithm to do the pathfinding instead since it's smarter and faster than the simple algorithm that's currently implemented.  

Another approach would be to have the cost of city state movement be artificially higher so that the path finding prefers it, though there might be other repercussions of that like not correctly calculating where the unit will actually end up if they do take the route through the city state. 

One way is to calculate with the extra cost and then if the path that is still best is through the city state, recalculate with the normal costs to find the real route.
