### ISSUE TITLE
It is not obvious to players that all policies, not only the branches, are pickable

### ISSUE THREAD

**Issue by stevekinoshita** [yairm210/Unciv#1831]
![Screenshot_20200202-080148](https://user-images.githubusercontent.com/51230554/73611091-329ed300-4593-11ea-82d7-a815443e92a0.png)
**Describe the bug**
it is impossible to exit the policy screen after being awarded free policy. 

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yairm210** [comment]
You can click on the green icons, they are also policies and can be picked.

Before anyone else comments here, I want to say: this is a real problem.
Many people seem to have this mistake.
A perception problem is also a problem, and we should fix this somehow.

**Comment by yairm210** [comment]
How could we solve this?
Perhaps by making the pickable policies 'pulse' into another color when they can be picked, but what of the battery saving option?
If anyone has any other ideas I'd be glad to hear them

**Comment by Whistler11** [comment]
The current light blue on dark blue isn't the easiest to discern the edges of the button.
Maybe change the colour scheme to make it more clear what _can_ be selected. a brighter green? Yellow? Inverted colours (e.g. white background, dark image)?

**Comment by alextfish** [comment]
I hate to say it because I know it's unfashionable, but: bevels. Beveled buttons are the single best affordance for showing that something is clickable. The modern "flat" design without delimiting edges of any kind just makes interfaces harder to use. 

In a case like this where you really want to indicate some things (policy tree headings) work like other things (policies with icons) but differently to yet more things (the tree completion bonuses), I think the really strong "I'm clickable" affordance of pseudo-3D bevels are exactly what you need.

**Comment by r3versi** [comment]
How about having a little circle on the left of each selectable button? The circle could be grey if the policy isn't pickable, white if it pickable and green if it is already adopted.

**Comment by KingCoolBreeze** [comment]
I do not want to beat a dead horseman, but I beg to differ about this being only a perception issue. I spent 10 minutes and a couple of reboots trying everything. I touched every millimeter of my screen, watching for either option to be available (adopt policy or close). I was effectively stuck on that screen with no recourse. There was no going forward and no backing out. I uninstalled it and will soon reinstall it (because it is truly impressive and fun). Please let me know if I really am still missing something. 
![Screenshot_20200326-215438_UnCiv](https://user-images.githubusercontent.com/62733443/77717927-9b149a00-6faf-11ea-94d7-59a6daf52854.jpg)

**Comment by yairm210** [comment]
Recent changes in c8c2bbb make the policy screen NOT auto-popup, but only open when you click on the 'next turn' button - should probably solve this issue entirely, and if not, will allow you to send us broken save files so we can see what's going on =)
