### ISSUE TITLE
Escorts

### ISSUE THREAD

**Issue by coolrobloxguy** [yairm210/UnCiv#198]
Being able to link two troops for transport would be a nice UI improvement. (Sorry if it's a thing)

**Comment by yairm210** [comment]
Hey, sorry for the late response.
First of all, thanks for the suggestion!
It turns out that this is not simple at all (what if tiles in between have space for a military unit but not a civilian? If they have different movement speeds, or movement bonuses/penalties?)
And since it's not a core feature, I'm going to have to skip this (at least for now) to focus on core gameplay mechanics (like Diplomacy, that old fiend)
I hope that once the game is complete enough, I'll start tackling difficult non-core features =)
