### ISSUE TITLE
You can nuke your own cities?

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/Unciv#1980]
It's not really a bug, but it's something that happens to annoy the hell out of me. How is it that I can nuke my own cities as well?

![image](https://user-images.githubusercontent.com/41149920/75044860-99444c00-54c2-11ea-949b-aa79de4b8e1e.png)

**Comment by JackRainy** [comment]
This is expected behavior according to the feedback #1375 

> Nuclear missiles should be able to target and bomb ANY tile within their 12 tile radius, not just units and cities, and irrespective of line of sight.

Also, it is quite natural: the nuclear explosion (in the real life) does not care whose cities are near by.

One of the possible scenarios when you may want this: you large city (one city challenge?) is going to be surrounded by swarm of enemies and it's better to wipe them out in one turn and lose 5 population, rather to lose whole city.

**Comment by Smashfanful** [comment]
But what if I lost my one city due to an excess of nukes?

**Comment by JackRainy** [comment]
What do you mean by "excess of nukes"?
Did you nuke your city by accident? If so, load an autosave, and be careful pressing that big red button.
Or make a cool story when a drunk colonel has slept on his duty, and fallen on the alarm button, which was a false call to launch the missile. :)

**Comment by yairm210** [comment]
Not a bug. If you want to nuke your own city, who am I to stop you?
