### ISSUE TITLE
font size and button size should be changed with resolution setting.

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#2063]
i have tested that font size can't ＞ 12 if we want it shows normal in 750*500 in russian.

**Comment by r3versi** [comment]
I don't understand what's the issue. Currently the font size is fixed because when changing resolution it changes the number of pixels the viewport is wide. So a 12pt font in a low resolution will appear bigger than the same 12pt font on a higher resolution (simply because the whole viewport have a higher number of pixels, hence the font appears smaller because it is using a smaller ratio of pixels). Can you describe what's the issue properly?

**Comment by lishaoxia1985** [comment]
for example,  in 1500*1000, table and table will be good, but in low resolution 750*500 one table will be overlap another especially russian in city screen,  because the size of button or table is relative with content, so make font small will solve the overlapping problem.
on the other hand, if your physical resolution is very high, then you set resolution in 1500*1200, the button is too small to see, in this condition,  we can make font large than usual.
of cource, i have not found how to change button size when font size changes automatically, i only know restarting app can make effect.
my English is not very good, thanks.😁

**Comment by stoupa007** [comment]
i'm using lower resolution to get more readable buttons and texts .. :)

**Comment by yairm210** [comment]
I think that this is not a real problem, and that it can certainly be circumvented in other ways for those that feel it's problematic for them
Certainly better than dynamically changing button sizes
