### ISSUE TITLE
Display allocated resources from trade offers during multiple offers

### ISSUE THREAD

**Issue by JoshDM** [yairm210/Unciv#2111]
When negotiating more than one trade on the same turn, for example two simultaneous peace treaties with two different nations, if you offer a luxury resource to one treaty, it is not unavailable for the second treaty.

I have Furs(2); I offer peace with America and give them a Furs.

I offer peace with the Ottomans. Furs(2) is listed, but should be Furs(1) because one has been allocated on offer to America.

**Comment by yairm210** [comment]
I think it's fine that we double-bid this, since we haven't given it away yet.
Worst case scenario, the first civ will take us up on our offer, and the offer to the second civ will no longer be relevant.

**Comment by JoshDM** [comment]
How does one know which one is "first"?

**Comment by krijnsent** [comment]
> I think it's fine that we double-bid this, since we haven't given it away yet.
> Worst case scenario, the first civ will take us up on our offer, and the offer to the second civ will no longer be relevant.

I guess there is a more fundamental solution needed, because trading away too many copies of your luxuries can make your empire unhappy (dropping to zero) and have big consequences. There is a safety built in for dropping below zero (indeed "Our proposed trade is no longer relevant"), but that's not good enough IMHO.

And in the same category are research treaty offers: I only get them offered when I have enough gold, but can accept as many as I like which can lead to negative gold. In Civ5: if you have minus gold, you will stop gaining science, and eventually your units will start disbanding...
Both cases are undesirable from a players perspective.

**Comment by yairm210** [comment]
In the latest version, offering resources in trade means that they will not be available on that turn, which among other things deals with this
