### ISSUE TITLE
Some technologies issues

### ISSUE THREAD

**Issue by Roumaan** [yairm210/UnCiv#215]
I was trying to copy technologies Russian translation from the official localisation to civ 5 and found out that arheology is placed in Renaissance Era but it should be in Industrial Era and that Arhitecture doesn't have any translations yet.

**Comment by Roumaan** [comment]
Ooh it's so mixed up at last three eras. Why did you add Future era and deleted atomic era?

**Comment by Roumaan** [comment]
No no wrong word. It's not mixed up it's displaced.

**Comment by yairm210** [comment]
Short answer: there are 3 versions of Civ v: vanilla, gods and kings, and brave New world
Each has its own tech tree and eras
The current eras are according to vanilla Civ
But you're right, there's a bit of a mess towards the end because not all techs exist, because many of them are for purely military purposes, I need to straighten out the tech tree
