### ISSUE TITLE
About Android Mod

### ISSUE THREAD

**Issue by tianshidoubi** [yairm210/Unciv#2197]
**Is your feature request related to a problem? Please describe.**
While browsing through Android files, I found that unciv has a folder called mods. In fact, when you add a mod file similar to desktop, you can display this mod in the game. However, it's frustrating that these mod files don't seem to work at all - or that they don't fit Android at all. Therefore, I hope to add the mod function of Android. After all, most of the players of unciv are Android.

**Describe the solution you'd like**
Add an Android mod function.

**Describe alternatives you've considered**
Or... Allow players to edit civilized projects in the game?

**Comment by rh-github-2015** [comment]
Example mods were broken a few days ago. Re-download. Snow is now in master and obsolete, and Incas had a bug which masked another bug - the first causing the mod to load but not include the nation object, the second to crash the loader due to nation unique having changed from string to an enumerated constant. See my blah blah on #2200. Methinks with #2191 in the code - probably in the upcoming release - you should see exception messages caused by mod errors in logcat.

**Comment by rh-github-2015** [comment]
Note when I say broken I don't imply yairm wrote crap, but that he didn't keep up updating those examples to match the development of unciv itself. Generally, this whole project is a little miracle.

**Comment by tianshidoubi** [comment]
> Note when I say broken I don't imply yairm wrote crap, but that he didn't keep up updating those examples to match the development of unciv itself. Generally, this whole project is a little miracle.

I noticed that this unciv-mod was updated two days ago. Is this related to your contribution?

**Comment by rh-github-2015** [comment]
Yes. Unless you use the updated mod you won't get far.

**Comment by tianshidoubi** [comment]
> Yes. Unless you use the updated mod you won't get far.

OK,Thanks.Can I close this Issues?

**Comment by rh-github-2015** [comment]
Of course you can.

**Comment by tianshidoubi** [comment]
> Of course you can.

OK,Thanks.
