### ISSUE TITLE
Implementation details for effects (includes comments on the new regex magnitude parsing)

### ISSUE THREAD

**Issue by rh-github-2015** [yairm210/Unciv#2206]
While pondering about 'I might need different magnitudes for that withdraw-from-melee effect' yesterday I stumbled over a few code lines parsing numbers out of strings and using different approaches: Regex/capture group here, startswith + a regex to isolate the number there.

I think - no particular order, more like brainstorming:
* String parsing of this kind could and should be done at load time, not in UI-triggered or next-turn code (maybe except if every single effect is cached at the business object like that unit's double movement in forests flag is). *1
* Separating the numbers out in the jsons and using string formatting instead of parsing might be safer
* Lookup should always be a simple hashable lookup never a loop. 
* Aggregatable effects should use the same aggregating code - Only one such loop in the whole project. Choose either Float then round for e.g. Carrier capacity or choose Int and express everything else as percentage e.g. growth bonus.
* Effects should be atomic, no flag should have several meanings (e.g. Great Andean Road would contain separate effects for hill movement and road maintenance)
* unit uniques/promotion effects and civ uniques/policy effects would then have the same abstract relationship and could be built into a single framework instantiated on the CivInfo and MapUnit level (not sure I'm remotely hitting the correct names)
* when building such a framework, I'd suggest separating keys from display strings completely, always having the formatting string go into the translator never the assembled result, and never having the actual formatting string in the rule jsons, only in the translation .properties even the english one. There's people with literary skills and there's people with coding skills, not always in the same skull. Is #2205 doing this?
* Follow-up to *1: Load time is also a better place to catch and log json errors. Yesterday I had a case discrepancy in a promotion name between declaration and reference, and it crashed the civilopedia - with the ideas here that would have been caught at load time where it could even have been reported in a recoverable way (yes the withdraw from melee effect already works in draft quality).

Just food for thought.

**Comment by JackRainy** [comment]
> Is #2205 doing this?
I am not sure, I understand the question, however, the idea is to get rid of the hard-coded strings which are added to `template.properties` manually, just in order to cover a translation of the same strings from the rule sets (jsons). The developer adds a new building, unit, promotion in a JSON - and that's it. One does not bother about its translations; the framework sends it into the language files for the translators automatically.

**Comment by yairm210** [comment]
Can you provide an example for something that would require a different approach than the current one?

**Comment by SomeTroglodyte** [comment]
I see parts of this idea are getting implemented. policy.hasEffect()...

Now imagine
```
    fun getTurnsToBuild(civInfo: CivilizationInfo): Int {
        var realTurnsToBuild = turnsToBuild.toFloat() * civInfo.gameInfo.gameParameters.gameSpeed.modifier
        if (civInfo.containsBuildingUnique("Worker construction increased 25%"))
            realTurnsToBuild *= 0.75f
        if (civInfo.policies.isAdopted("Citizenship"))
            realTurnsToBuild *= 0.75f
        return realTurnsToBuild.roundToInt()
    }

```
could be
```
    fun getTurnsToBuild(civInfo: CivilizationInfo): Int {
        return (turnsToBuild.toFloat() * civInfo.gameInfo.gameParameters.gameSpeed.modifier
            * civInfo.getEffectMagnitude("Worker construction increased") ).roundToInt()
    }
```
And you could mod the effect into building, wonder, policy or nation unique with impunity and they'd all work. Add a call for the unit and you could have the same effect on modded units or promotions for free... And 10% or 50% instead of 25% would also work immediately without modifications to the code. And knowledge how an effect stacks is part of the effect definition not at the use site (multiplicatively here, rules could demand additive elsewhere).

**Comment by yairm210** [comment]
This is already the case for some of the promotions, but I wouldn't put this as a priority as long as it isn't needed =)
