### ISSUE TITLE
Leader portraits

### ISSUE THREAD

**Issue by RobertGine** [yairm210/Unciv#2237]
I think it would be good to add leader portraits to Unciv, since they were fundamental in making Civilization the legendary game series it has become.

Of course I'm not asking for animations like in V and VI, but I'm sure there are talented artists that would love to design portraits, and if not, there are plenty of copyright-free pictures we could choose from.

**Comment by Smashfanful** [comment]
Excellent idea! I saw some of fanmade leader portraits on Discord!

My idea is that there should be three versions of the same portrait: angry (when we're at war or we demounce them), normal (when our relations with them are just negative but no war) and happy (they greet us for the first time or our relationship is positive, and also when we declare a friendship with them)

**Comment by refola** [comment]
> My idea is that there should be three versions of the same portrait: angry (when we're at war or we demounce them), normal (when our relations with them are just negative but no war) and happy (they greet us for the first time or our relationship is positive, and also when we declare a friendship with them)

Sounds good, but to be fully generic (especially for mods that want to add different levels of detail than vanilla Unciv) there should probably be numerical diplomacy levels which trigger portrait changes. Genericized thusly, your suggestion for vanilla Unciv becomes: start at "normal", but at +30 or higher switch to "happy" and at -30 or lower switch to "angry". Mods with 5 or 7 levels of detail could, for example, add additional thresholds at ±15 and ±45 instead of just ±30.

**Comment by yairm210** [comment]
I'm glad to announce that you can (finally) add leader portraits through mods!

[See here](https://github.com/yairm210/Unciv-leader-portrait-mod-example) for an example on how to do this
