### ISSUE TITLE
Mod manager

### ISSUE THREAD

**Issue by Naprogramuji** [yairm210/Unciv#2238]
As number of mods is increasing, number of questions about mods installing on android is increasing as well. What about simple mod download manager?

**Comment by rh-github-2015** [comment]
Still not feeling I know enough to tackle this. But getting closer. At least, I now have otherwise unused hardware to debug on.

If you have time, how about fleshing out the proposal? Required features, nice-to-have ones, detailed enough to start coding? UI ideas, maybe sketched visually (or even here in markdown)?

**Comment by Misterodd** [comment]
Sadly the downloaded mods via the experimental mod manager are not staying in the mods folder. Only mods download to the downloads folder and moved in the mods folder. They stay. It's weird.

**Comment by yairm210** [comment]
Okay this was done a while back but I forgot to mark it as done
