### ISSUE TITLE
Add symbols for colorblind unit recognition

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#231]

**Comment by yairm210** [comment]
To be honest I'm not quite sure what to do with this.
I'm not sure that the game can even be changed to be colorblind-friendly without a massive change in UI because both civ and tile type recognition are color-dependent...

**Comment by L314** [comment]
One Idea I had for this is to have different Civs have different shapes as their bg shape. Another easier fix is to label all tiles with who it belongs to. Like the units are right now.

**Comment by theodorthegreathe** [comment]
I beleive UnCiv is playable even on E-Ink screens. I can  provide you with a YotaPhone 2 for tests. Obviously, the terrain is not the biggest problem, one just have to issue monochrome Tileset which only requires cosmetic changes on Default or ThorfMaps.
An elegant solution to distinguish ownership is the usage of geometric 🚩🔰📍 or symbolic ($£@₪₹¤¥) flags on an occupied tile.Right part of the hexagon is vacant for that  at the moment.
When decreasing scale, one may want to make this flags larger.

**Comment by kfish610** [comment]
In order to not clutter up the display for non-colorblind users, maybe the changes would be an option in the settings?

**Comment by i-need-to-tell-you-something** [comment]
## Solution 1: 
You can use something like [this](https://www.colorhexa.com/68bf26#blindness-simulator) to test your color scheme for different types of color blindness. There are probably even better tools somewhere. I can ask around if need be.

## Solution 2:
### For tile types:
The tileset should have ever so slightly more details to it than just the color. Similarly to e.g. [these](https://duckduckgo.com/?q=civ+6+strategic+view&t=canonical&iar=images&iax=images&ia=images&iai=http%3A%2F%2Fi.kinja-img.com%2Fgawker-media%2Fimage%2Fupload%2Ft_original%2Fduhy5ncusnlkinkmrr6h.png).

### For tile ownership:
I think a more aesthetically pleasing alternative to having [flags](https://duckduckgo.com/?q=dominions+5&t=canonical&iar=images&iax=images&ia=images&iai=https%3A%2F%2Fmegagames.com%2Fsites%2Fdefault%2Ffiles%2Fgame-images%2FDOMINIONS5.jpg) at every tile would be to have systematically varied patterns to each nation. So the borders will be a line which consists of a pattern of 2 or 3 colors, instead of having a dashed line of 1 solid color (like Unciv currently) or 1 solid color line and a solid color gradient to alpha (like Civ 5). If the colors would be distinct enough, I think the Civ 5 solution might work as well. 

I can produce a mockup if need be.

Still, since the color-blind mode would probably require slightly wider borders, it might have to be a toggleable option in settings. Though the downside of being an option would be that it is easier to accidentally break it in development. More simple/elegant design is more robust generally.

**Comment by logicminimal** [comment]
outdated?

**Comment by yairm210** [comment]
I think this has become less and less feasible with every new civ, so guess into the "not happening" pile

**Comment by will-ca** [comment]
Android has colourblindness simulation in Developer Options. Linux DEs/WMs have extensions/modes for tinting. Most graphics programs (including GIMP) have tools for simulating different types of colourblindness. If this becomes a concern again, could quantify needed changes by just playing a game in greyscale and writing down anything that's annoying to do.

That said, I'm not personally sure why this would be an issue. FantasyHex, unit icons, and civ icons on city labels all have distinctive silhouettes and brightnesses. Clicking units shows who they belong to as text, and clicking tiles shows what's on them as text. The only information that's potentially hue-dependent AFAICT is when you can see an empire border but not any cities or units (and thus no empire icon or unit ownership text).

But even that still leaves the often quite different civ colour brightnesses to go off of. Here's two empires and a city state, all completely distinguishable, even before taking into account the helpful red (I.E. darkened) circles that are drawn under enemy units:

![image](https://user-images.githubusercontent.com/37680486/143496404-a963f41f-401c-47d7-8a04-5ebf87dc8db5.png)

And here's several dozen civs. Some are indeed possible to mix up, but not nearly as many as you might think.

With nation icons:
![image](https://user-images.githubusercontent.com/37680486/143501597-69c15bd6-2d21-495e-a281-287a83a215aa.png)

With units (`viewEntireMapForDebug = True` seems to break nation icons):
![image](https://user-images.githubusercontent.com/37680486/143501895-37ea725b-3b27-4346-af4b-53cff758b876.png)

For reference, AFAIK the vast majority of people with colourblindness still have more than one type of functional cone cell, so this monochromatic test case is an extreme.

(Simple fixes just based on above image:
1. Make enemy unit circle blend multiplicatively, so it always darkens the tile under it.
2. Make sure all empire colours have slightly different combinations of colour-blindness-simulated brightness. If we limit ourselves to using 11 distinct shades of "grey", then that still gives us 121 possible combinations, which is sufficient.)

I'm not saying this should be re-opened, just leaving a note in case anyone else decides to say that.
