### ISSUE TITLE
Natural Wonder Tile is not removable or replaceable in Map Editorr

### ISSUE THREAD

**Issue by Alkeif** [yairm210/Unciv#2456]
**Describe the bug**
In the map editor, when a natural wonder tile is placed on the map, it's not possible to remove or replace it with a normal terrain tile. It is however possible to replace the natural wonder with another natural wonder.

**To Reproduce**
1. Open map editor
2. Place any natural wonder
3. Try replacing it with another common tile type (except another natural wonder)
4. It will not work

**Expected behavior**
It is possible to replace a placed natural wonder with another tile type in the map editor.

**Comment by SomeTroglodyte** [comment]
Select the blank in the second column - the terrain features - then click on the wonder.

**Comment by Alkeif** [comment]
Ah, I see thanks. Still, the regular tiles in the first column cannot replace the natural wonder riles. It can be quite confusing as the natural wonder tiles are in the first column while the blank tile is on the second column. Anyway thanks for the heads up.

**Comment by SomeTroglodyte** [comment]
Yeah, not a solution just a workaround - but since that's something I found out first time in the editor I couldn't keep quiet. 

Map editor still needs to be made to work with modded terrain, and that code I had working a while ago but shelved it. When I dig it out maybe I'll see to this inconsistency, too. [Maybe](https://www.youtube.com/watch?v=_lU0pRakBmQ).

**Comment by JackRainy** [comment]
I have changed editor UI a bit #2462 , so this tool for removing is more obvious.
