### ISSUE TITLE
Show city name option

### ISSUE THREAD

**Issue by CSharpDeveloperss** [yairm210/Unciv#2499]
I think that an option for displaying city nsmes is essential.

**Comment by yairm210** [comment]
Where? What are you talking about?

**Comment by CSharpDeveloperss** [comment]
Sometimes in the fantasihex screen of game , selecting units behind the city name label is hard (in my android cell phone). Therefore please provide an option in the display option group of options page that allow to user to select displaying/not displaying city names

**Comment by yairm210** [comment]
But then how would you enter the city?

**Comment by SomeTroglodyte** [comment]
We all felt this some way or another, and that's why considerable effort has gone into the behaviour of the city label. And IMHO it's admirably solved.

Tip: Tapping the corner of a hex will still select the hex and units in it even if they're 'under cover'. Can sometimes help.

@yairm210 : Maybe not toggle them via menu but rather like the worked tile / resource display minibuttons left of the minimap? On a timer, so they reappear after 3 seconds? Not worth it IMO but - just an idea.

**Comment by yairm210** [comment]
I'm not sure there's anything actually actionable here... I understand you want it to be better, but it needs to be better in a specific way.
