### ISSUE TITLE
Worker's icon stays "dimmed" after waking up from sleep

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#278]
Happened to only one unit upon waking from a sleep state in my capital city.

**Comment by yairm210** [comment]
How exactly did you "wake him up" from his sleep state?

**Comment by flecheapolinienne** [comment]
Simply clicked on him to move him around. The unit couldn't do improvements anymore

**Comment by yairm210** [comment]
I couldn't replicate this...?
Are you sure it wasn't because he was in a city, and in a city you can't make improvements?

**Comment by yairm210** [comment]
A worker will be dimmed if either
A. It is sleeping
B. You moved it to a tile that has an improvement under construction
C. It ran out of movement points

Are you sure it's not one of the above?

**Comment by Crit-Cee** [comment]
I openwd a new thread about this. It's not just workers. Any unit put to sleep is being treated as though it's still asleep even after moving or doing other actions.

This means these units no longer show up in the active unit queue for selecting new actions (I've accidentally left many units idle for many turns due to this).

I have not had an issue with a worjer not being able to improve a tile after being put to sleep, however. I can do any action available to a unit, it appears they just do the action while still in a sleep state.

**Comment by yairm210** [comment]
Solved (see #285 )
