### ISSUE TITLE
Cities with no health should not grant XP to attacker

### ISSUE THREAD

**Issue by halloamigos** [yairm210/Unciv#2819]
Right now the player will gain great general points and unit XP by continuing to attack a city with ranged units after it has been reduced to 0 health. This exploit does not exist in civ v and should be removed

**Comment by ravignir** [comment]
Not only that. When city is at 0 health it should still damage unit attacking it, altho it won't be able to kill it, even if you attack it with scout.

**Comment by yairm210** [comment]
@ravignir Nope, it should not.

**Comment by refola** [comment]
The old "bug" behavior matches Civ V with G&K. I distinctly remembering using defeated-but-not-captured cities to farm experience for advanced promotions and having to rotate out units because the cities continued to fight back. The only significant change when the last bit of city defense falls is that melee units can just walk in without taking damage.

Unless it's different in vanilla Civ V or with BNW, please consider reverting this "fix".

**Comment by yairm210** [comment]
Nope
If there are obvious problems in Civ V, there's no reason to replicate then as well in Unciv.

**Comment by SafarotH** [comment]
It should be like this. I have like many others I think have exploited this. Just in my current game I had an archer with just 3 promotions left just by attacking a city b2b. This in turn makes starting troops too fat that they are hard to kill for AI.

**Comment by refola** [comment]
It's not obvious to me that it's a problem. If it's overpowered against AI, then the bug is not in the mechanism but in the AI failing to use it. (Aside: it would be great if someone could figure out how to train a neural network AI to play this game with automatically-discovered tactics and then just add the pretrained AI to the game.…)

It's also a risky tactic because the city's owner might be able to buy strong units there and suddenly start killing off your ranged units. I've actually done that against the AI when I've inadvertently gotten it to XP-farm my cities. I was strong enough to kill their melee units before they could capture my cities, but I had to bring in some serious resources from other cities to finish off its leveled-up crossbowmen.
