### ISSUE TITLE
Sync Between Desktop and Mobile / Synced Notifications and Gameplay

### ISSUE THREAD

**Issue by seniorm0ment** [yairm210/Unciv#2825]
**Is your feature request related to a problem? Please describe.**
Currently to my knowledge, there is zero way to sync progress between desktop and mobile clients.

**Describe the solution you'd like**
The ability to sync progress between desktop and mobile clients, would be very nice to be able to also just hop on the phone and continue playing where you left off from the desktop and vice versa. Also would be cool if you play on desktop, to have it sync in real time with your mobile client to provide notifications on your phone if you wish.

The ability to have autobackups of your saves would be nice too, so I can just Rsync it to my server and ensure even on reinstalls my progress never gets lost.

**Additional context**
Slightly related to #2679 which suggested changing off Dropbox for multiplayer, a peer to peer solution was recommended if possible. If possible, a similar system could be implemented with this as well.

**Comment by refola** [comment]
I use Syncthing to sync my phone's entire "storage" folder to my computer, and I can see my phone's Unciv data in the `Android/data/com.unciv.app/files/SaveFiles/` folder. From there it's trivial on Mac and Linux to create a symlink from the desktop Unciv config folder (`"$HOME/.local/share/Unciv"` on Linux; not sure about MacOS) to the synced copy of the phone's config. This should work pretty smoothly as long as you keep roughly the same version on both systems and only run Unciv on one device at a time.

The problem is Unciv itself is oblivious to this setup, so it may be possible to create a race condition where both systems are trying to save a game to the same file. Comparing the output of `tree` for the config folder when Unciv's running vs not shows that there's no lock file / directory (double-checked by running two copies of Unciv at once). So expect conflicts with multiple copies of Unciv running with the same config folder. How conflicts are handled depends entirely on how you do the syncing. Syncthing decides which version wins the file conflict and saves the other with an extra extension like `.sync-conflict-X8VA790ZZDZO`.

**Comment by yairm210** [comment]
Okay, so - we have a solution, using the same premise as the current multiplayer.

Basically, you create a multiplayer game, **but where you're the only human player.**

This means that every turn your game will be uploaded, you can sync specific games between whatever devices you want by having the same player ID, and best of all the multiplayer sync is tried and tested :)
