### ISSUE TITLE
Luxury ressources don't always count towards happiness

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/UnCiv#283]
Whales in my case don't provide happiness even though being exploited. I never got the tutorial message when first founding a city near the ressource nor is it accounted for in the "Luxury ressources" line under Overview - Statistics - Happiness

**Comment by yairm210** [comment]
How odd.
Could you send me the game data?

**Comment by flecheapolinienne** [comment]
How may I do that? I'd also try to send you data for Issue #278

**Comment by yairm210** [comment]
Menu - save game - copy to clipboard - paste into email to yairm210@hotmail.com

**Comment by Crit-Cee** [comment]
I noticed this too, but it could be for a numbe of reasons. First, I've only seen it with whales. All other luxury resources effect happiness for the whole nation. Whales are not a luxury resource, so there may be an issue with the code not counting the happiness provided because it's not a luxury resource. Or maybe it's supposed to count to the cities happiness and perhaps the city info screen jus isn't showing it.

It could also be an info updating issue. With all things I've noticed that resource info both on the city screen and world screen don't auto-update within a turn. So if I use a workboat to create fisheries on a resource the values won't update unless I end the turn or go to the city screen and tap the citizen off and back onto the tile.

**Comment by yairm210** [comment]
Whales ARE a luxury resource, and are treated as such, even in the save files that flecheapolinienne sent me.

If only based on that, I would close the issue, but you've encountered it as well? Do you have a saved game as such?

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/48971994-8e360e00-f02a-11e8-9a9b-54be8d3c662a.png)

The color indicates what yield they improve - in this case food. The smiley indicates that they are a luxury resource

**Comment by Crit-Cee** [comment]
That makes sense now. As far as if it adds happiness or still bugged I haven't had the time to test it due to work. If you haven't been able to replicate it I'd just close this feed and if I or anyone notices it again we can reopen a new feed.

**Comment by yairm210** [comment]
Sure thing, let me know if you reproduce it!
