### ISSUE TITLE
Rebelling cities can be bought from the AI for extremely cheap price

### ISSUE THREAD

**Issue by gdanskleme** [yairm210/Unciv#2838]
**Describe the bug**
When a city is captured by the AI and is rebelling you can buy that rebelling city from the AI for very cheap price no matter the city's population or yield

**To Reproduce**
1. Go to the trade screen
2. Click on a city owned by the AI that is in resistance 
3. No matter the city pop or yield,buy with 500 gold or 2 luxuries
4. The AI will always accept the trade and you get a huge city for a very cheap price
**Expected behavior**
The AI will not accept what is basically just giving the city away.

**Comment by halloamigos** [comment]
@yairm210 please reconsider removing the ability to trade captured cities. I understand the decision to remove it entirely because the ai in unciv would accept small amounts of gold in exchange, but it is possible in civ v to simply give away recently captured cities to the AI if you wish. you can also buy cities from the AI that are still in rebellion however they will typically demand very very large amounts of gold and luxuries.
