### ISSUE TITLE
Very slow response to Load/Save

### ISSUE THREAD

**Issue by 1kotas** [yairm210/Unciv#2853]
**Describe the bug**
When Load or Save game is selected, it takes about 70 sec to response

Samsung S9, Android 10, UnCiv 3.9.10 (version 3.9.9 has the same behavior)

**Comment by yairm210** [comment]
This is probably because you just have a really huge game, no?
Does this happen to you in smaller maps?

**Comment by saud2410** [comment]
It's little different but similar for me.
I usually play huge map, make lots of savefiles. (1 save per 1~3 turns)
About 200 turn, saving/loading becomes very laggy.
It works fast again if I delete all the savefiles.

**Comment by yairm210** [comment]
This is not something I can really improve - the bigger the map and the more stuff is happening, naturally the bigger the save file will be...
Maybe I'll try to shrinkwrap the save files themselves and see if that helps

**Comment by scaphander** [comment]
I think this is not _only_ a problem of a too big savegame, as one of too many savegames.
I experienced the same thing when i was having too many savegames.  And i often play small maps with 3 enemies.
Probably the game resurrects each savegame to read its name and put it in the savegame-list
or something like that... i guess.

**Comment by scaphander** [comment]
Maybe its about the FileHandler gdx thing in logic/GameSaver.kt which plays around with the savegames reads an array casts to collection and maps by name.

later in ui/saves/LoadGameScreen.kt - updateLoadableGames(... ) each file is sortedby date with an call to GameSaver.getSave(it).lastModified()

Probably theres to much complexity in this and that causes the time consumption.

Im new to kotlin and android, but i would think that delegating all this sorting stuff to a filesystem-query-thing instead of in memory on the fly casting, shaking and looping would save time or at least keep the complexity within a limit...

The last step could be to load the choosen file by string. 

Maybe the compiler flatens this all, and i got no real idea here.
