### ISSUE TITLE
Worker AI

### ISSUE THREAD

**Issue by Dalcinrafa** [yairm210/Unciv#2923]
Workers frequently state that there's no work to do, when there are. Better automatic worker settings would be nice too.

**Comment by refola** [comment]
I think this is because the workers aren't looking far enough away. The same situation happens with exploration.

The workaround for both cases is the same: Move the unit closer to where it's needed.

**Comment by yairm210** [comment]
This is a tradeoff we need to do between the AI being as useful as possible, and the runtime needed for the AI to check all possible help it can give. We've put a cutoff for technical reasons, so that the game will still run in relatively normal speed of the average Android phone.

**Comment by refola** [comment]
> We've put a cutoff for technical reasons, so that the game will still run in relatively normal speed of the average Android phone.

Mind elaborating on the technical reasons? Because without knowing anything about the code, it seems like even the following naive O(n) algorithm should improve this situation.

1. Make a list of "idle" (by current standards) workers.
2. Iterate thru all tiles, assigning "idle" workers to improvable tiles sequentially (i.e., treating the list like a queue).

If computational resources permit, then you can replace the worker selection method with (a fast approximation of) "choose the closest 'idle' worker". I suspect that ignoring terrain costs to give a simple formulaic distance approximation would make the "closest 'idle' worker" function fast (O(n^2), but *n* is the number of workers, so n^2 is likely under 10,000) while still being accurate enough to satisfy most players.

**Comment by yairm210** [comment]
The problem is trying to figure out which workers can go where.
Not every worker can actually head towards every tile.
The canReach() function uses the getShortestPath() function, which is one of the heaviest functions in the game, and so for tiles that are too far away (I think 20 tiles away?) we don't even try.
If you can improve either of those, the canReach() or the getShortestPath(), that will lead to a great performance boost everywhere in the game =D

**Comment by bitappend** [comment]
A simple and resource cheap solution. Is have the automated workers and explorers. If idle and no workable square in range and and available movement then move 1 tile in a rand() direction .  Sure It doesn't give so genus level automation but will make them act like real people and just look around a bit eventually they will find something.

**Comment by refola** [comment]
Thanks for elaborating! Sounds like some serious graph theory challenges. I or someone else might be able to look up some useful algorithms eventually.…

For reference, judging solely by the names, it looks like `canReach()` and `getShortestPath()` are both digraph traversal problems, but the latter requires an efficient solution. I don't know if the "di"\* part of "digraph" changes which algorithms are available.

Worst case, I suspect that some crude heuristics and simplifying assumptions could still improve the overall situation. But I'm not making strong claims until I learn enough Kotlin and graph theory to tell if there's a better algorithm than whatever's already being done.

\* The graph is directional because you can't always navigate back the way you came. For example, suppose there's a line of three connected hill tiles -- call them A, B, and C -- where tile A is unimproved, tile B has another player's unit, and C has a road. If you have a worker on tile C, then it can move to tile A in one turn. But it can't move from A to C because it would use all its movement points getting to tile B -- an invalid ending tile for that worker, due to the other player's unit -- and will have none left to move onto the road in tile C. (Come to think of it, this would be a really funny way to trap "friendly" units if there's no other way around.)
