### ISSUE TITLE
A.I. money bug

### ISSUE THREAD

**Issue by Crimors** [yairm210/Unciv#2967]
I was playing and I realized at turn about turn 100 the AI had 300000 gold

1. I start a game
2. Put on mods
3.i go through the game as usual
I look on victory status regularly
4. Then I look at victory status like usual then I notice the amount of gold this ai has 

What I expected is a normal amount of gold from the ai instead he has the amount of gold all civs combined
 would have in total at the end of games
 
![20200809_191555](https://user-images.githubusercontent.com/69440401/89746086-08176080-da75-11ea-9d31-14ddb005633e.jpg)

**Comment by mboch** [comment]
I have the same issue in my game. I think the bug is that buying units currently costs negative gold - I gain money for buying them. 

![Screenshot_20200809-231119](https://user-images.githubusercontent.com/8354696/89749509-0316d900-da96-11ea-8b10-643bd92e464c.png)


The AI appears to be taking full advantage considering it has 900k gold on turn 166. I've never seen so many catapults...

**Comment by yairm210** [comment]
Fixed in 3.9.19
I've closed this exact issue 4 times already
I'll leave this one open for other people to discover and not open new ones

**Comment by Aroniyun** [comment]
I have the same bug but it has evolved. It started when I got my first policy that decreased the cost of purchasing items. At that point units changed to a negative cost. Later I built big Ben for another discount and now it costs around 100k to buy a settler instead of -27k. I'll have to see if the next discount flips it again. This appears to only affect units, not building.
