### ISSUE TITLE
Movement options reveal too much about unexplored tiles

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3009]
Currently, the game allows units to chart a course to any tile within its range of movement, even unexplored tiles. But because the game has already determined which tiles are navigable by the unit, this mechanism can inadvertently reveal what terrain is in the unexplored tile. See the below screenshot, where the suggested moves for my trireme allows me to ascertain the shape of the coast.

This is not a huge deal, but I think it would be more in keeping with the notion of "unexplored" if the game does not reveal these sorts of hints. My suggestion is to not allow navigation to any tiles that are currently unexplored.

![Screenshot_20200808-094329_UnCiv](https://user-images.githubusercontent.com/1423934/90592441-6b527280-e19a-11ea-9bc9-1af0982f7bc6.png)

**Comment by bitappend** [comment]
I admit I use this cheat. However I assume the ai does too.I wonder how you could remove and make fair

**Comment by refola** [comment]
I think that navigation should assume that movement through fog-of-war tiles is possible (with movement cost matching unimproved open terrain), and then abort as soon as anything violates that assumption.

That way you can still, e.g., send a scout to the other side of Pangaea and it will go in as straight a line as possible instead of taking the long way just because it's already been explored. A trireme would basically circle the entire island trying to find its way in and only give up after the destination proves to be surrounded by land (or ocean).

**Comment by foolishgrunt** [comment]
I'm changing my vote to match refola's suggestion. :)

**Comment by refola** [comment]
@foolishgrunt Thanks, but I'm pretty sure it's a pull-request-ocracy, not a democracy. ;)  The best someone contributes is what happens, and my idea is just a suggestion unless / until someone codes it up. This is definitely how *I* would try it, but I don't know Kotlin and what intermittent trying-to-see-if-I-can-improve-Unciv's-code effort I have is focused on #2923.
