### ISSUE TITLE
Mobile Modding

### ISSUE THREAD

**Issue by khurtron6** [yairm210/Unciv#3114]
Modding In mobile is hard 
How about Making The PC Modding Same In mobile
Compacting The Units Json By Add A Code "Image":["Tank.png"],
Automatic Find the Folder / UnitIcon Folder
And "Image tileset":"["Tank.png"],
Automatically  Goes to Com.unciv.app / Mods / "Mod" / TileSets / Tank.png

**Comment by ravignir** [comment]
Just get yourself a PC. Some things are easier said than done, and that's one of them.

**Comment by khurtron6** [comment]
Bruh Its Kinda AN AHole for Telling Other to buy a PC Bruh That not cool
Anyway doing that Coding process is more Conventional and Easyer Btw Uncool

**Comment by ravignir** [comment]
Sorry for a blunt answer. When it comes to code(json) editing on mobile - nothing can really be improved, unless you want to implement an ingame GUI like;
-> select a thing to add to your mod (<nation>, tile etc)
-> set nation name, leader, all of the dialogues
-> add nation cities
-> add nation icon.

-> select a thing to add to your nation (<unit>, unique ability, building)
-> set unit attack
-> choose unit type
-> choose free promotions.
-> add uniques
And so on. But that's a lot of work and wasted resources.

If you meant .atlas file generation, I don't think you can efficiently generate these on android device.

So that leads to conclusion; get yourself a pc, even a dirt cheap 15 year old machine should handle unciv + modding w/o problems.

**Comment by khurtron6** [comment]
Bruh have you played Rusted warfare About Same Coding On folder unit.json
file Picture Ad thats it

**Comment by ravignir** [comment]
Can you elaborate?
I've downloaded the mentioned game and i see no imgame mod editor.

**Comment by khurtron6** [comment]
Bruh first have a mod second Goto units find the mod enter the folder find
the Unit And you see Folder of the units Enter it And There is it A Ini
File / json file And a picture That it

**Comment by ravignir** [comment]
Sorry, but i don't get what you are saying.
I've downloaded one of rusted warfare mod and I see .ini files, .template files and .png files.

No jsons, no atlases.
It uses sprite sheets for each unit.

And it does not look like unciv mods, it looks more complicated and time consuming than these in fact.

I don't see how it is easier to make rusted warfare mod than unciv mod, even on Android. Unciv even has built-in mod downloader. You might want to check: 
https://github.com/yairm210/Unciv/wiki/Mods
 for more info on unciv modding.

> When it comes to json editing it's literally the same on both mobile and desktop.
> You can't generate atlas (sprite sheet) files on android.
> mods will work without atlas file, but no images will be displayed.

**Comment by khurtron6** [comment]
Bruh It same like the pcs coding  That all

**Comment by AcridBrimistic** [comment]
I've read this conversation three times and still haven't got a clue what you're arguing for.  Writing on mobile is hard.  In other news, doing integrals in one's head is difficult and composing with a pen is time-consuming.

The other guy telling you to get a PC wasn't being an 'AHole'.  You'll need a PC at some point one way or another.  You should learn to format your comments better and how to join two sentences; it's extremely difficult to understand your arguments.

**Comment by khurtron6** [comment]
Now your being the Ahole
