### ISSUE TITLE
Feature request: Improve city build queue

### ISSUE THREAD

**Issue by SamuelPlentz** [yairm210/Unciv#3137]
I really like the (city build queue, as it really helps in late) game. ;) Thank you.
I would suggest this improvements:

1. Currently I can't add a university to the queue if the library is in the queue, but not yet build. (there are other similar dependencies)
- Either postpone the validation of "can a university already be build" until the queue reaches its position (convert the current error to a warning) or
- make sure it can only be added below a library (also affects move up/down of library/university entries and a delete of the library should also remove the university)

2. Currently I can't add an important item to the top of the queue. I have my long list of buildings I want to be build in the city, but someone declares war on me and I want to add some units to the list. Currently I have to add them and select the new entries and bring each of it to the top one position after the other.
- Either add an "add entries to the top" check mark, that can be activated temporarily or
- add a "move entry to the top" button next to the "move entry 1 position up/down" buttons appearing, when selecting a queue item.

3. Currently managing around 15 to 30 cities is very repetitive.
I am science orientated there is this one city I build my units, but other cities don't need barracks or an armory. So in each newly build or conquered city I add this list of 10 buildings in the correct order omitting "useless" entries. I would like to be able to build a list of buildings with templates instead:
- One should be able to create and name a build template (for example: `Science-Productivity`)
- One should be able to add, order and remove entries in this build template (for example it contains `1. Library`, `2. Granary`, `3. Stable`, `4. Windmill`, `5. University`)
- One should be able to add this build template in a city build queue. If it reaches the top position it should build one entry after the other omitting entries that are not possible like a staple when there are no horses in this city. If every item from the build template is build the template is removed from the queue.
- If one changes the build template (reorder/remove/add items) each city instantly reacts building something else or discarding the build template if no buildings are left to be build.
- Implementation details:
  - It shouldn't be possible to add (national) wonders to the build template. As only one city may build it.
  - It could be possible to add "produce science/gold" to the build template: It should be the last item. As long as it is there this build template would never be discarded.
  - It probably shouldn't be possible to add units to the build template. (counting units build "by the build template" could be hard considering a reordered or in another way changed build template / building the same unit infinitely could be unexpected)
  - Probably only one build template would be sufficient. On the other hand it would be nice to have presets for naval cities, science cities, production cities, ...

Changes like this (Nr. 1 / Nr. 3) would be awesome.

**Comment by refola** [comment]
This is one of the biggest annoyances I've had with the original Civ V. So far, Unciv has a longer build queue as an advantage over its inspiration (I think Civ V had a limit of only 6 items in the queue). I suspect that the first two parts of your feature request will be much easier than the third one for someone to implement.

Responses for number 3:
- This would be extra useful if the templates are saved outside of the game itself. Then I could immediately set my capital to my "starting buildings before first wonder" queue and very quickly move on.
- Wonders should be okay in templates. If a wonder can't be built then it can just be skipped. 
- Units should also be okay in templates. Each unit would only be built as many times as it appears. So a "build starting army" template of "scout, warrior, scout, warrior, archer, archer" would build exactly that in order, skipping the archers if Archery hasn't been researched by the time the last warrior is built.
- I think that science / gold in a build template could be put in a special "build this until something else is possible" slot in the template. If the slot is generalized enough, then it can even do things like "build these buildings when possible, but otherwise alternate between the highest naval units available", but that's getting a bit complicated.

**Comment by K3XRad** [comment]
This is the great suggestion! Exactly what I want to see in the game.

**Comment by hackedpassword** [comment]
The majority of the feature requests here were under discussion in #9980, and codified by #10061.

The templates suggested sound like a lot of work to implement. Niche but powerful in the right hands.

@SomeTroglodyte i feel this old request can be closed as noted above. Should this thread stay open having a feature still hanging? If it were mine I'd close it.

**Comment by hackedpassword** [comment]
Low priority ok. For my ref, I'm looking at thinning down the issues queue if that'd be useful. Problem is there's history I don't know about, throughout years of issue reports, so that conflicts with the potential contribution. What do you think?

**Comment by SeventhM** [comment]
Closing as not planned for now. @SomeTroglodyte Seems like up your "I should rebuild CityScreen" alley, so it's your choice to reopen or whatever
