### ISSUE TITLE
Harbor, seaport not providing aditionnal ressources

### ISSUE THREAD

**Issue by flecheapolinienne** [yairm210/Unciv#3153]
Title says it all. Neither harbor nor seaport provide expected ressource bonuses (production, gold)

**Comment by yairm210** [comment]
What version/mods are you using?

**Comment by yairm210** [comment]
Checked - works fine in my version, probably a mod problem.

**Comment by flecheapolinienne** [comment]
Checking it today!

**Comment by yairm210** [comment]
Checked?

**Comment by flecheapolinienne** [comment]
yes, sorry. I couldn't reproduce the bug after a couple turns.

**Comment by Seadog18** [comment]
Hi - experiencing the same issue. v3.10.10, android 11. No mods. 

Note: I attempted to exit game to see if it might clear the glitch (since it sounds like it went away on its own for original reporter). However, the game throws an error when I try to restart upon opening app - maybe suggests file was somehow corrupted?
