### ISSUE TITLE
Defence alliance pact

### ISSUE THREAD

**Issue by CIZUK** [yairm210/Unciv#3304]
You should be able to sign agreements with allies that means that if someone declares war on one partner, the other automatically joins the war on the defending side.

**Comment by jwmh** [comment]
I think a similar effect is achieved by offering a trade agreement, and
Set the other side's offer to "Declare war on ___" 
I just did this:
Me (only human player).
Three AIs (Persia, Inca, France).
.
Persia had declared war on me (for no reason other than greed i guess).
.
A dozen turns later, I'm losing badly.
.
I asked Inca for help, for them to declare war on Persia.
 (I offered them lots of gold plus opening my borders (didnt ask for the return, only a declaration of war).)
Inca declined.
.
I next asked France for help (same deal).
France agreed!
and a few turns later started attacking Persia.

**Comment by jwmh** [comment]
CIZUK,
Would the above resolve your issue?
Or did you have another scenario in mind, beyond what I suggested?

**Comment by CIZUK** [comment]
Not really, it would be needed to scare other Civs into not starting a war in the first place, saying that if you take me on, you're also taking my ally on and things will be twice as hard.

**Comment by yairm210** [comment]
Closing as 'not in roadmap' as part of our cleanup

**Comment by WhoIsJohannes** [comment]
Was this closed because of lack of time or because you don't want to support it? I think this would be a nice feature. It also seems to be in the original Civ 5, so it would be in scope.

Another thing I'd like to look into is to sign a no-war pact that lasts a certain amount of turns (similar to what happens after signing a peace treaty). This doesn't seem to be in Civ 5. Would you be interested in having that in the game though?

**Comment by tuvus** [comment]
Solved with  #9900
