### ISSUE TITLE
split screen make a crash

### ISSUE THREAD

**Issue by b-1** [yairm210/Unciv#3401]
if I split the screen with an game in recent, the image disappears. becomes a blue screen. the image is not returned if I expand it back to full screen. I need have to restart the application.

but if I run (!) the game after splitting, in the second window, everything is OK.

**Comment by yairm210** [comment]
Does this still happen to you? I can't reproduce this

**Comment by b-1** [comment]
yeap, it's still here. I have the latest version of course.

this is the wrong way:
1. start the game
2. minimize the game
3. open recent apps
4. enable split screen by any method. it doesn't matter if the game will be in the first window or in the second
get a blue screen. bug №1
5. turn off split screen
6. launch the application from recent in full screen
7. the screen is still blue. bug №2

this is the correct way:
1. be sure to close the game by swiping it from recent applications
2. split the screen and adjust the desired ratio (1:1 or 3:1) on one or two other applications
3. start the game in the second window
4. enjoy the game and watch the series;)
5. do not change the window ratio otherwise the blue screen will appear again. bug №3
6. if you want to continue the game, go to the first step

**Comment by GGGuenni** [comment]
This same issue occurs when entering the battery saver mode.
There seems to be an easy fix by adding "screenLayout" and "uiMode" to the AndroidManifest.xml under android:configChanges, where "screenLayout" is the fix for split-screen and "uiMode" the fix for the battery saver mode. Both tags prevent the application from restarting on specific configuration changes.
This is already used for the configuration changes "keyboard", "keyboardHidden", "orientation", and "screenSize" but as stated in the documentation (below) is in fact not recommended.

https://developer.android.com/guide/topics/manifest/activity-element
https://developer.android.com/guide/topics/resources/runtime-changes

From the documentation:
"However, your application should always be able to shutdown and restart with its previous state intact, so you should not consider this technique an escape from retaining your state during normal activity lifecycle."

**Comment by JackRainy** [comment]
My best guess: the problem is in the [ImageGetter](https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/utils/ImageGetter.kt).
It is a static object. 

As you may know, the static objects do not have references, thus, they are not collected by GC.
It means their lifetime can be **longer** than the lifetime of the application itself !

In the given example, the application is recreated (you can set the breakpoint on `UncivGame.create()` to check) when the split screen is enabled. But the `ImageGetter` (and all other static objects) are still alive from the previous session and are not recreated.
When the fresh created application tries to access them, it may find the obsolete data (e.g. Images, Textures, etc.) there. See the description of this problem in [the LibGDX article](https://github.com/libgdx/libgdx/wiki/Managing-your-assets#creating-an-assetmanager).

> Caution: don't make your AssetManager or any other resources (like Texture, etc.) static, unless you properly manage them. 
This will cause problems on Android because the life-cycle of the static variable is not necessarily the same as the life-cycle of your application. Therefore the AssetManager instance of a previous instance of your application might be used for the next instance, while the resources are no longer valid. This typically would cause black/missing textures or incorrect assets.
On Android, it is even possible for multiple instances of your Activity to be active at the same time, so do not think you're safe even if you handle life-cycle methods properly! 

When the application is totally killed (e.g. "by swiping it from recent applications") and the all memory is released, the static objects also become released and the new instance of application already uses the right new assets (e.g. images and textures).

**Comment by JackRainy** [comment]
I have just made an experiment (to prove my theory): I replace the ImageGetter object with the class and all its calls from `ImageGetter.` to `ImageGetter().` - yes, create the object for each call to its methods. Of course, it has absolutely crushed the performance down to 0...1 FPS, but the problem has been resolved - being patient enough you can see the game is restarted in the split screen and does not hang with the blue screen.

Of course, that's not a solution (I doubt the game logic is not even broken) and I do not have any good one by the moment, but at least the problem is identified.
