### ISSUE TITLE
In-Game Music

### ISSUE THREAD

**Issue by Lucaxk** [yairm210/Unciv#3429]
_**Hi**_, You could **add** an option to change the **music** of the menu or the music during the game since it gets a bit **boring** 😊, if it already exists, **sorry** for bothering and if you can tell me the **instructions** to change it correctly, **Thanks**

**Comment by yairm210** [comment]
Hi, first of all , thanks for contacting us!
Unfortunately, music is a very low priority for us, since everyone can just put their own music on and not have it provided as part of the in-game experience, and most of the other problems are things that can't be solved by outside changes. 
Since one of the priorities of the game is keeping a low filesize, the music files would need to be downloaded as the current one is, but having many files would make this another asset requiring management, which is too much cost for too little benefit to us at the moment
