### ISSUE TITLE
Map editor - Zooming often places a tile

### ISSUE THREAD

**Issue by krushia** [yairm210/Unciv#3435]
**Describe the bug**
After two finger pinch zooming in the map editor, a tile is placed when lifting fingers.

**To Reproduce**
1. Go to 'Map editor'
2. Make a new map
3. Make it empty
4. Choose tile brush that will stand out
5. Zoom in and out via pinch gesture

**Comment by krushia** [comment]
On a related note... is there an undo feature?

**Comment by ArchDuque-Pancake** [comment]
This also happens to me...

**Comment by yairm210** [comment]
I'm pretty sure @SomeTroglodyte solved this recently, what say?

**Comment by SomeTroglodyte** [comment]
No I blocked the "Right-Click" ClickListener for Droid only, because somewhere in some secret place some system service translates some gesture to a right-click (not our code). This should _not_ affect map editor: CameraStageBaseScreen, EditorMapHolder, TileGroupMap - and that ClickListener is in WorldMapHolder.

Anyway, map editor is _quite_ unsatisfactory. No inspection mode - "tell me exactly what the tile contains", no mouseover highlighting of the tiles affected by the brush, needs the automatic steps of map generator available individually, unit placing has some dead code, zooming out limit could be a bit more generous than on the game world screen, can produce "illegal" tile combos (in the sense that the generator wouldn't generate them - Stones on Oasis).... Never got around to investigate let around lay out steps that could be done. Probably start by using the new widgets. There's other construction sites holding more interest, as, with patience, you _can_ get the maps you want.
