### ISSUE TITLE
Don't reveal random nation in hot seat ready screen

### ISSUE THREAD

**Issue by krushia** [yairm210/Unciv#3502]
The ready screen between hotseat player turns reveals the nation random players spawned as.

**Describe the solution you'd like**
The best way to deal with this would be to add a player name field for everyone to fill in, and the ready screen would use that instead of the nation.

**Describe alternatives you've considered**
The quickest fix is to just display "Random ready?", but this becomes ambiguous when there are more people playing as random. It would have to be "Random Player 1 ready?" or something.

**Additional context**
I feel bad bringing this up because the nation colored ready screens are so pretty.

**Comment by krushia** [comment]
After everyone has discovered a random nation in game, the ready screen can start addressing that player with pretty colors again?

**Comment by b-1** [comment]
no. I think the question here is that your opponent does not know until the last what nation you play. so that only the style of play could distinguish AI from humans.

and in my opinion, even if your nation is not random, you can still choose not to impersonate who you are playing. it is an interesting gaming experience and offer. thank you, @krushia.

the best solution would be to add the "secret nation" option on the same list as the random, spectator, and other nations. name the players without the options "player1", "player2", etc. and offer the choice of the nation (no matter random or not) after the start and after "ready?" screen. the whole game after that do not give out the names of the players' nation.

**Comment by yairm210** [comment]
I'm closing this as "wontfix"
