### ISSUE TITLE
Cannot upgrade units at 0 resource

### ISSUE THREAD

**Issue by philn3v** [yairm210/UnCiv#362]
Unit upgrades require one excess strategic resource. The upgrade doesnt consume the resource but is required for the upgrade button to appear. Im not sure if this was a feature in the original game.

**Comment by ninjatao** [comment]
I believe the resource was taken on new unit generation. But top-bar did not update.

**Comment by yairm210** [comment]
I agree that it needs to be updated, but it sounds like this happens because the upgraded unit is not, technically, buildable:
https://github.com/yairm210/UnCiv/blob/9ca77fa3996146bc7227512f26deb85610e6c017/core/src/com/unciv/ui/worldscreen/unit/UnitActions.kt#L78

So what we need to check is, if this unit was removed from the civ, would the upgrade be buildable?

**Comment by ninjatao** [comment]
I think the answer is yes. isBuildable() calls getCivResources() for resources availability check. And getCivResources() counts all existing units.
