### ISSUE TITLE
SUPER long... code?

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#3649]
Sometimes when I copy something, it copies into clipboard some REALLY long code. It always starts like H4slAAAAAAAAAAA and it is longer than 5000 characters. You can see it in #2133, #3541 or #3492. Idk if it's a bug or it's intentional, but either way it's too long.
Btw could the game and user IDs get a bit shorter?

**Comment by jahodovykolac** [comment]
And sorry if I'm annoying with my many issues reports.

**Comment by GGGuenni** [comment]
The code you are talking about is a save game as text. You should only be able to copy it via "Copy saved game to clipboard". Do you get it somewhere else? What do you copy to get this text?

The game and user IDs won't get any shorter because Unciv is using the standard UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)
There was however an attempt to make them able to differentiate which would, in fact, make them even longer (#2108).

**Comment by jahodovykolac** [comment]
If I remember correctly, I get it when I copy map data.
So when the game saves the game as text, it generates this code. I get that it must have long code for big data, but it is hard to send it because some apps have characters limit. But I'm not some coding genius so I don't complain.
