### ISSUE TITLE
Game reverts back multiple turns occasionally.

### ISSUE THREAD

**Issue by wethefreakinppl** [yairm210/Unciv#3795]
I'm playing online multiplayer a friend and our games will sometimes go back in time. It can be as few as 2-3 turns but we've also been on turn 65 and it went back to turn 5.

**Comment by GGGuenni** [comment]
This is because there was a bug with the updating of multiplayer games. If it's your turn in the save you have, the game won't download a new version of the save. and thus you will play with the old version you downloaded earlier. If you press "refresh list" when it's the turn of your friend and the other way around you won't have this problem anymore.

If refresh doesn't seem to help, you have to restart your game once because there was also a bug preventing "refresh list" from refreshing correctly.
Both problems are fixed in 3.14.1

**Comment by yairm210** [comment]
Solved in latest version :)
