### ISSUE TITLE
Allow player to sell buildings in cities

### ISSUE THREAD

**Issue by yairm210** [yairm210/UnCiv#384]

**Comment by Am-per-Sand** [comment]
Ermm... 

I'd rather sell them, let's say for half their purchase cost.

**Comment by yairm210** [comment]
So apparently this exists in a Civ V path:

https://gaming.stackexchange.com/questions/8716/how-can-i-sell-buildings

One building per city per turn, for 10% of purchase cost.
Cool.

**Comment by Crit-Cee** [comment]
Yeah 50% is a bit much. I could def see someone pushing production so they can build a building, sell it, build another, sell it, etc... to make money quickly. Since the base conversion of production to gold ability with Guilds is 25% it should be at less than 25% to discourage profiteering off selling buildings.
