### ISSUE TITLE
AI not aware of ruins?

### ISSUE THREAD

**Issue by foolishgrunt** [yairm210/Unciv#3864]
***My apologies, I meant to report this months ago, but it slipped my mind again and again. Please close if this has been addressed in recent updates.***

It seems to me that AI players are unaware of ancient ruins until after they have been discovered by a human player, almost as if the ruins are not generated until the human player explores their location - I assume this is not intentional behavior. I present evidence from three separate games.

Scenario 1: on AI home continent, ruins were still not explored when I discovered them on turn 165.
![img1](https://user-images.githubusercontent.com/1423934/116800510-a68d9b00-aab6-11eb-8a8f-86ac177f170c.png)

Scenario 2: ruins inside city-state's borders were still not explored when I discovered them on turn 165. Then on the very next turn, the ruins are explored by a city-state unit.
![img3](https://user-images.githubusercontent.com/1423934/116800560-23b91000-aab7-11eb-93f1-f073dd5e4fa0.png)
![img4](https://user-images.githubusercontent.com/1423934/116800561-27e52d80-aab7-11eb-8965-675259e3dbd4.png)

Scenario 3: city-state unit is literally on top of ruins when I discover them.
![img2](https://user-images.githubusercontent.com/1423934/116800578-5236eb00-aab7-11eb-97c9-c486fd4a25c3.png)

**Comment by SomeTroglodyte** [comment]
Superficial analysis:
- `MapUnit.getAncientRuinBonus()` seems the only place ruins are cleared after turn 1 (on turn 1 any ruins within 3 tiles of any starting position are erased)
- It is only called from `moveThroughTile` and only if `civInfo.isMajorCiv()`
- `UnitAutomation` only looks for ruins in `tryGoToRuinAndEncampment()` where the code looks sound - if the function is called for a major AI civ's unit it _will_ move and claim the bonus on arrival.
- That function in turn is called in 3 places - automateUnitMoves, automatedExplore and tryExplore (the latter a little redundantly because its 4 callers are 2 for civilians and 2 where tryGoToRuinAndEncampment has already been called shortly before - OK so settlers can also 'pop' ruins...)
- Within automateUnitMoves, for non-air military units, it's the first attempt.

All that looks very clean, no hole allowing your scenarios 'strikes the eye'.

So - scenario 1 india never decided to explore? scenario 2 the ruin wasn't taken by brussels? scenario 3 the warrior never moved there (nah should be excluded by that initial turn 3-tile radius)?

Or - are you playing with an outdated version??? Why do you have two instead of three minimap buttons???

**Comment by yairm210** [comment]
None of this is a bug.
Two of three situations are "city state doesn't activate ruins", which is intentional.
The first one is just 'AI didn't get there with a unit' which is OK, that can happen.

**Comment by foolishgrunt** [comment]
I won't open a new issue, but I do want to mention that scenario 1 has kept happening to me.

All throughout my current game, I've been discovering ruins very close to AI territory and being surprised that they weren't already explored by the AI, but just now I discovered some ruins two spaces away from an AI unit. The next turn, the AI explored them. To my untrained eye, it seems really unlikely that the AI is aware of these ruins until after I discover them.

![Screenshot_20211030-080807_UnCiv](https://user-images.githubusercontent.com/1423934/139539610-df3bfd85-d909-4a17-b82a-ad787b63df5a.png)
![Screenshot_20211030-081002_UnCiv](https://user-images.githubusercontent.com/1423934/139539613-4bbd6513-929c-4531-be29-64237a6ded9a.png)
