### ISSUE TITLE
Send desktop notifications when it's your turn

### ISSUE THREAD

**Issue by SadmanTariq** [yairm210/Unciv#3906]
Make the game send notifications when it's the players turn on pc

**Comment by SadmanTariq** [comment]
A notification when the game is running but minimized. I usually tab out and do other things when it's not my turn so a reminder of when it is my turn would be really helpful.

**Comment by SomeTroglodyte** [comment]
~~I can see it - but that would be more Android-only non-Gdx code, and not trivial. Would need an understanding of GCM, of persistent notifications like Signal does when it doesn't see GCM support, permissions for that, and so on... Doable, but not this month or maybe year for me.~~

~~Oh, correction, since we're FOSS and GCM is very nastily anti-FOSS we would go the persistent notification route anyway, and there were complications getting that working on multiple Android versions...~~

~~Don't get me wrong: I'm talking about two notifications: The one you wish for and one to have the app stay in memory and awake just to remove the randomness from when the first one actually works and when not... And that needs a completely different approach below pie or oreo - i forget...~~

Oh wait - "on pc" - well that's even worse. Anyone can guess how many different OS versions are able to run our jar? Hundreds probably, and they all spam their messages differently.

Idea: User can configure any URL that will get `Gdx.net.openURI` "launched" when it's time (which would still need the stay-awake thingy) - then you can plonk in the SMS gateway of your choice or maybe even a longish mailto: URL...

**Comment by yairm210** [comment]
I don't see a way to do this at all.
Closing as "unviable technologically".

**Comment by ArchDuque-Pancake** [comment]
What if the game makes a distinctive sound?
