### ISSUE TITLE
Android only, auto screen rotation

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#3925]
In general, this game only supports 90˚ deg screen. But when I play this game using earphones, it is less convenient when the screen is in position 90˚. And almost all games in playstore support auto-screen rotation censor. (Can reverse the position of the screen simply by reversing it (90˚ to 270˚ or vice-versa).) Can this game add it for better user experience?

**Comment by ArchDuque-Pancake** [comment]
What? I can do that.

**Comment by AdityaMH** [comment]
You need to turn on screen rotation to do it. But almost any game can flip the screen without turning on screen rotation. I don't want to prolong any other activity just to enable rotation in the settings and just only for a game.

**Comment by ArchDuque-Pancake** [comment]
Yes, exactly, you can already do this. So what are you asking for?

**Comment by AdityaMH** [comment]
I don't want disturb any all app activity just one game.

**Comment by SomeTroglodyte** [comment]
Looks OK in an AVD...
![image](https://user-images.githubusercontent.com/63000004/118131105-61466300-b3fe-11eb-8585-a89a2a13f04c.png)

**Comment by SomeTroglodyte** [comment]
Sorry for the joke - that was with a patched manifest. Everything scales a little smaller than the same session in landscape, and that may be the reason the manifest forbids portrait - consistent scaling might need extra information not readily available in-game?...

Maybe a poll?

**Comment by yairm210** [comment]
Hm
Is there a way to make this opt-in? It's on the Manifest level so that's a problem, but maybe there's a solution

**Comment by SomeTroglodyte** [comment]
"opt-in" - The thought occurred to me - but no idea on how to do that.

**Comment by jahodovykolac** [comment]
In one other game there was an "orientation" settings (in the settings), if you would tap it, you could choose between landscape, portrait and auto (isn't needed here), so it could be something like that.

**Comment by SomeTroglodyte** [comment]
@jahodovykolac  - was that other game open source? Identify the game or better yet, repository?

**Comment by SomeTroglodyte** [comment]
https://user-images.githubusercontent.com/63000004/118295693-7691bf00-b4dc-11eb-8616-6cc87ee46170.mp4

This was a test on a KitKat (🙃!) AVD, the Oreo one is faster. Testers volunteering? You'd need Android Studio with any Unciv fork set up and some Android box set up for adb debugging...

**Comment by SomeTroglodyte** [comment]
As y'all can see I replaced the branch with a new one. Testers _still_ needed!
New: Avoided unreadable options screen at low resolutions + portrait by forcing the box back to landscape (can take a while). Can't make this a separate Activity, sorry - no idea whether libGdx supports that or, if it did, how access to game data would work...

**Comment by AdityaMH** [comment]
where i can testing this?

**Comment by SomeTroglodyte** [comment]
> where i can testing this?

As I said earlier - not a big problem _if_ you have the development environment running and cloned the fork and can run from there normally. In that case tell it about my repo and checkout the branch - I described this elsewhere in more detail. Otherwise - I have not leaned enough to offer an alternative, and even if I could, it would involve installing an apk with a differing signature which in turn means either losing all data by uninstalling first -or- going through the debug bridge to shell package manager, which in turn is easiest through Studio.........

**Comment by AdityaMH** [comment]
ok, i will wait fully release.
I don't think, playing this game in portait mode will be comfortable.

**Comment by SomeTroglodyte** [comment]
Correction: I _can_ [give you a debug apk](https://github.com/SomeTroglodyte/Scratchpad/tree/master/Debug%20apk's), but then I can't even manage on my own tablet to get it to install without losing data. With loss of settings, mods and saves - yes. And - once it is installed, going back to f-droid or store-supplied unciv is just as "painful". For single player, you can use the custom save location feature to at least transfer saves. Multiplayer - you get new ID's so that would be a problem.

Summary - install one of those APK's at your own risk. Install works only if no other package called "com.unciv.app" is installed and you have allowed external sources - I guess, the tablet I tested on is after all lineageOS so I might not see roadblocks others get. And be prepared to lose game data whenever you want to switch to another source as that has a debug signature, so you'll need to completely uninstall first.

**Comment by AdityaMH** [comment]
This issue not fixed in lastest version, why get closed?
