### ISSUE TITLE
Add a button in overview-units tab that highlights your units in the game screen

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#3958]
it would be better if there was a button that when pressed, highlights all your units, when you select any unit when that highlight is on, highlight gets disabled and the game returns to normal render mode with the unit you just selected getting selected.

in the highlight mode the tiles the units are in should be colored, some for instance:

civ unit - worker - working: orange
civ unit - worker - idle - no automation: yellow
civ unit - worker - automated: blue
civ unit - sleeping: grey
civ unit - great person: white, tinted blue

those color codes should also apply for the units list

edit: actually taking a second look at my issue, i think color codes aren't needed, just make certain icons (fortificate, working, working-automated, automated-idle, moving, moving-automated ) appear on top of the unit (please dont make the icons 16x16 :/ )

**Comment by AdityaMH** [comment]
i suggest:
civ unit - worker - working: two hammer icon
civ unit - worker - idle - with automation: hammer with box like icon.
And for all unit keep same. Because this game don't have animation.

**Comment by yairm210** [comment]
I don't quite follow you. A button that exists where? Like, where on the screen?

**Comment by AdityaMH** [comment]
> I don't quite follow you. A button that exists where? Like, where on the screen?

He talking about this
![Screenshot_2021-05-20-00-01-30-302_com unciv app](https://user-images.githubusercontent.com/33791472/118854195-c4ecf680-b8fe-11eb-8ad1-2ab1052989bf.png)


But, i suggest for world area (or maybe for overview too) . Because lack animation, use different icon as alternative.

**Comment by AdityaMH** [comment]
> it would be better if there was a button that when pressed, highlights all your units

Ah, i get it now. That's impossible, because in civ5 don't have this feature. You just selected "with same name" unit until you will get all "worker for example" to move or any action.

**Comment by SomeTroglodyte** [comment]
Actually replacing the "Action" column with icons isn't a bad idea. A nice "Zzz" for Sleeping and the existing Shield for Fortify, and showing exploring/automated and similar stuff is nicely possible...

What bugs me more on that screen is the green upgrade indicators not helping when tapped (because they share their columns's handler) - must have been a `<censored>` who had that idea. I have an alternative in mind, but heaped too much onto my plate already (That idea had an 'upgrade all for `sum` ' included).

Marking tiles is something the game already does, but doing so for all instances of a unit type - not worth it imho. Generating a notification on request that when tapped repeatedly cycles through all those units might be far easier to implement? Maybe. Still - when do you need that? Once per game when you want to start all sleeping workers you should have disbanded instead on railroads? Yes that could be tedious micromanagement - don't get me wrong, I appreciate input of this kind. And I have coded stuff that was motivated by making micromanagement of units easier - e.g. a tiny detail like that overview now remembers its last 'page' helps, and was meant to be complemented by it also keeping its vertical scroll position. That last part I've put on hold because the scroll position would change meaning when you rename units on the world screen (by upgrading them) and I had no eureka moment yet on how to deal with that.

**Comment by jahodovykolac** [comment]
From 3.14.12, units always show their action by an icon and both icons are showed in overview, that could resolve this.

**Comment by AdityaMH** [comment]
> From 3.14.12, units always show their action by an icon and both icons are showed in overview, that could resolve this.

But, missing construct icon when worker construct improvement.

**Comment by yairm210** [comment]
After adding the icons on the units, we can remove the action column entirely.
Unit construction of improvements isn't currently an action, per se, but that's a whole other kettle of fish.

**Comment by SomeTroglodyte** [comment]
What I'm playing around with for today is a new page that generates LocationActions for a few interesting combos - and I _did_ notice some more MapUnit.action abstraction helps for that - including some kind of "is constructing X". 
Got a working draft where one of six useful combos I thought useful is mostly working - one of the problems is when you select e.g. "Civilians that are Sleeping" the LocationAction of course navigates to the _Tile_ such a unit is on, which may select said unit - unless there's a military unit on that tile, too... Interested in seeing the draft?

**Comment by AdityaMH** [comment]
> After adding the icons on the units, we can remove the action column entirely.
I agree with that.

> Unit construction of improvements isn't currently an action, per se, but that's a whole other kettle of fish.
Constructing a farm, mine, or anything on tile isn't an action?
When worker construct something always turn text into yellow. Like catapult to set up.

Why not give worker working icon as inform to us, if this unit is busy, not because lack of turn?

**Comment by logicminimal** [comment]
> After adding the icons on the units, we can remove the action column entirely.
> Unit construction of improvements isn't currently an action, per se, but that's a whole other kettle of fish.

also by the way, the icons for actions are really small, could you fix it?

**Comment by AdityaMH** [comment]
> also by the way, the icons for actions are really small, could you fix it?

if icon actions become little larger, Then it will be a problem later. And ui becomes less interesting.
