### ISSUE TITLE
To be able to Spectate Multiplayer games.

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#3999]
Kind of related to #3921
It would be if you enter a multiplayer game, which you aren't playing in, you enter that game as a spectator.
Currently if you take a game ID from someone elses game, you can see their match, but as barbarians. So what I ask is to, instead of joining as barbarians, join as spectator.

**Comment by Thyrum** [comment]
For anyone trying to implement this, the relevant line seems to be
https://github.com/yairm210/Unciv/blob/55f943f428aed9d8d5597408af826adf09ff5bba/core/src/com/unciv/logic/GameInfo.kt#L80
Changing this to somehow return a spectator player might be enough, but I am not familiar enough withe the codebase to guarantee this.

**Comment by Thyrum** [comment]
Thinking about this a bit, what would be the expected behaviour? If a player joins a game which his uid is not a player in, what should happen? I see 3 options:
1. Just don't. Refuse to let the player join/watch.
2. Add the player as a normal spectator, meaning he has to press `NEXT TURN` every round too.
3. Create a special type of spectator who does not have to press `NEXT TURN` and assign that. This player should never update the game, only download and view it.

Personally I think option 3 is the best. @yairm210, do you agree? Then I might just pick this up when I have time.

**Comment by yairm210** [comment]
Agree

**Comment by ArchDuque-Pancake** [comment]
I agree as well

**Comment by ArchDuque-Pancake** [comment]
Has something been done to this?

**Comment by yairm210** [comment]
Done by @SomeTroglodyte

**Comment by yairm210** [comment]
In #5173

**Comment by SomeTroglodyte** [comment]
Um, I didn't test the effect of that change on a real online-MP game. I would be curious of course. Volunteers (hint, hint)?

**Comment by ArchDuque-Pancake** [comment]
Great!

If you dont find voluteers I could volunter @SomeTroglodyte
