### ISSUE TITLE
Tile info box is visually broken

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#4053]
On 3.14.13-patch1, the tile info box has some bugs:
- Spaces between lines are too big
- The yield images are off-centered
- City construction is not translated (there is Castle instead of "Hrad")

![20210604_211635](https://user-images.githubusercontent.com/79529669/120852226-38873880-c57a-11eb-8089-643f756c596b.jpg)

Older box for comparison:
![20210604_211840](https://user-images.githubusercontent.com/79529669/120852489-8ef47700-c57a-11eb-83eb-36e7aadedb5a.jpg)

**Comment by AdityaMH** [comment]
![IMG_20210605_064652](https://user-images.githubusercontent.com/33791472/120877329-22ac5e80-c5e0-11eb-8a2e-4d00f09b8523.jpg)
This is good features that i love, but not user-friendly for Android. Blocking almost entire notification.
Can we change to center-upper screen or left mini-map just for Android?

**Comment by jahodovykolac** [comment]
@AdityaMH I'm not talking about the whole box being bad, just after the last update it got oversized.

**Comment by AdityaMH** [comment]
> I'm not talking about the whole box being bad, just after the last update it got oversized.

I'm talking about oversize tile info too.

**Comment by jahodovykolac** [comment]
Oops, sorry

**Comment by SomeTroglodyte** [comment]
In order:
- That was intention on my part to make the IMHO a little squashed text more readable _and the links easier to hit_ I guess I'll revert that for non-civilopedia rendering.
- Looks intentional too though I can't remember putting that .padRight(10) in [there](https://github.com/yairm210/Unciv/blob/a1b0a9050681392fb203eef74df3cfd379316dc4/core/src/com/unciv/ui/worldscreen/bottombar/TileInfoTable.kt#L42) - yup that has been there since 2019-10-18
- That's on me losing a pair of curly braces [here](https://github.com/yairm210/Unciv/blob/a1b0a9050681392fb203eef74df3cfd379316dc4/core/src/com/unciv/logic/city/CityConstructions.kt#L160). Will push fix soon.

**Comment by SomeTroglodyte** [comment]
OK, j & a - what do you think:
![image](https://user-images.githubusercontent.com/63000004/120904167-00035f80-c64b-11eb-80c8-8f7677f7f63b.png)
I liked the less squashed line padding better, but it's OK like this too I think. But the yield number on the other hand - I think it's too close to the text IMHO. Suggestions?

**Comment by AdityaMH** [comment]
> OK, j & a - what do you think:
> ![image](https://user-images.githubusercontent.com/63000004/120904167-00035f80-c64b-11eb-80c8-8f7677f7f63b.png)
> I liked the less squashed line padding better, but it's OK like this too I think. But the yield number on the other hand - I think it's too close to the text IMHO. Suggestions?

Can you remove working progress and make tiles info separate by comma: (Grassland, Hill, City Center). And make worker unit progress like: Workers (trading post 2 turn) - India.
Or if you can, make it conditional.
If tile info more than "x" px, that will move to left minimap for specific screen resolution.
Because more low screen resolution selected, more high chance to block entire notification screen.

I'm just want notification not blocked by tile info.

**Comment by AdityaMH** [comment]
Something like this:
---
Delhi (275 HP)
Grassland, Hill, City Center
Crossbowman, Great Engineer - India
+25% to unit defense ** _why defence?_
---

Or more light width:

---
Grassland, Hill, City Center (Delhi)
Crossbowman, Great Engineer - India
+25% to unit defense ** _why defence?_
---

And HP city located to right strength icon (there still have slot).

**Comment by yairm210** [comment]
I agree that the work in progress is removable.
That was part of the tile info from before the construction industry was visible in the city button, and now I feel it's unneeded.

**Comment by AdityaMH** [comment]
> I agree that the work in progress is removable.
> That was part of the tile info from before the construction industry was visible in the city button, and now I feel it's unneeded.

But i think will affected to worker who construct tile improvement. Make them look no different, between workers lack of turn and workers who still working improvement.
Changing worker shape icon (triangle) while working would better.

**Comment by SomeTroglodyte** [comment]
> from before the construction industry was visible in the city button
:+1: 
> separate by comma
The point here is that's tappable and goes to the respective civilopedia page - and due to technical reasons we can do one link per line. So comma separated horizontal arrangement = no links = revert to old tileinfo. @yairm210  we could offer both as option "compact" vs "linked" or so..
> located to right strength
![image](https://user-images.githubusercontent.com/63000004/120918961-7178f780-c6b7-11eb-90bc-9456aff5e0f0.png)
Doesn't look too bad for shorter city names - but, no. That number is already on the city button - which raises the questions: Should that button use the _ranged_ symbol not the melee one? Should health be shown _there_ if known? current/max? Should the city button not test some isViewableToPlayer as the TileInfoTable does?

**Comment by AdityaMH** [comment]
>Due to technical reasons we can do one link per line. So comma separated horizontal arrangement = no links = revert to old tileinfo. @yairm210 we could offer both as option "compact" vs "linked" or so.

I don't know if comma separated can't do vertical arrangement. So don't change this.


>![image](https://user-images.githubusercontent.com/63000004/120918961-7178f780-c6b7-11eb-90bc-9456aff5e0f0.png)
> Doesn't look too bad for shorter city names - but, no. That number is already on the city button - which raises the questions: Should that button use the _ranged_ symbol not the melee one? Should health be shown _there_ if known? current/max? Should the city button not test some isViewableToPlayer as the TileInfoTable does?

I'm talking about HP City moved to city button. And i think would better if just make ranged attack keep hidden.
![Screenshot_2021-06-06-23-10-36-561_com unciv app](https://user-images.githubusercontent.com/33791472/120933846-34981980-c726-11eb-81ac-5133bc0048fc.png)

Something like this:
🛡City strength ♥ HP city current/max

---
🛡85 ♥265/275
---
