### ISSUE TITLE
Paratrooper

### ISSUE THREAD

**Issue by dnddnbdodjd** [yairm210/Unciv#4057]
https://civilization.fandom.com/wiki/Paratrooper_(Civ5)
Combat effectiveness Have a big problem,You should change it.

**Comment by xlenstra** [comment]
Currently it is implemented like it was in the vanilla base game, where its combat effectiveness is arguably not great. It is therefore more useful for sabotaging the enemy by appearing behind his lines, for example to pillage luxury or strategic resources, or, with the medic promotion, can be used to give some extra healing to difficult to reach units, for example.

**Comment by AdityaMH** [comment]
> https://civilization.fandom.com/wiki/Paratrooper_(Civ5)
> Combat effectiveness Have a big problem,You should change it.

In fandom says, paratrooper are used for pillaging specialist not for combat. This unit can be very annoying if also buffed combat strength. So this no big problem and case closed.

**Comment by ravignir** [comment]
Vanilla civ5 has a completely different combat strength for all units and different combat mechanics (units have 10 HP instead of 100 HP). Unciv follows G&K combat mechanics and unit strengths.

FYI Warrior in vanilla civ5 is 6 strength, spearman is 7, mechanized infantry is 50.
![see](https://user-images.githubusercontent.com/30041793/120893168-1640f980-c612-11eb-9a84-24eb3f4f79d3.png)

**Comment by ravignir** [comment]
also paratroopers are not supposed to be able to attack after paradroping unless they have >additional attack< promotion.

**Comment by dnddnbdodjd** [comment]
@xlenstra

**Comment by xlenstra** [comment]
I'll fix it this or the next weekend I suppose
