### ISSUE TITLE
AI: Explore bug

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#4107]
Please don't let explorer like scout or other unit to enter inside CS border automatically when that unit have explore command.
Because this can decrease influence when enter.

Need save file?
Just play at first game tiny pangea with lot CS and make random unit to explore.

**Comment by ravignir** [comment]
While we are at it: automatically cancel exploration when the unit is attacked.

**Comment by SomeTroglodyte** [comment]
While we are at it: Wake up sleeping units when enemy sighted / wake up and un-fortify units that are displaced by border expansion - ravignir, you know that stuff - does c5 do that?

**Comment by xlenstra** [comment]
There is in civ5 an 'alert' action, which is a sleep/fortify that wakes a unit when it sees an enemy unit, and I do believe that normal fortified/sleeping/alert units wake up upon by displaced by a border expansion.

**Comment by ravignir** [comment]
It works exactly like @xlenstra described. Regular Fortify does not wake your unit when it is attacked/sees an unit.

**Comment by ravignir** [comment]
also, if unit wakes up from alert, all of the fortification defense bonuses are lost.

**Comment by SomeTroglodyte** [comment]
Well I have a patch coded that would change 2 things: 
- Automatic wakeup of _sleeping_ units (code in `MapUnit.startTurn`) was testing for enemies within 2 tiles (besides testing is military or civilian without escort), would now test for enemies in visible tiles
- Displacement due to expansion or change of status (diplomacy and city trade) would wake a unit and remove fortification (I mean if you're pushed down a hill that's _got_ to break your prepared defenses, right), but not cancel automation, exploration or moveto orders (in `UnitMovementAlgorithms.teleportToClosestMoveableTile`).

Suggestions on that while I test it?

A new action would be an order of magnitude bigger, no thanks for now.

**Comment by SomeTroglodyte** [comment]
@AdityaMH - sorry for veering off. The mind wanders. But auto-exporation is a complex beast I know little about, only that it's necessarily quite limited to keep resource hunger in check - it _can't_ look to the other side of the map to send your caravel to uncover a few ice floes because considering such a large area and the pathing to get there will consume ram and cpu not proportional to covered distance or quadratic, much worse.... Then again ZOC, threat levels while a worker travels (no I haven't forgotten #3979), or weighing diplomatic repercussions in such pathing are pretty much work in progress anyway I presume... some time...

**Comment by yairm210** [comment]
This already exists as a different issue.
