### ISSUE TITLE
"Outdated" label for mods

### ISSUE THREAD

**Issue by ArchDuque-Pancake** [yairm210/Unciv#4210]
The idea is for a tag or mark to let know players a mod that hasn't got an update may not work properly, because of the constant improving mechanics and stuff.
This would be automated, and perhaps a team could confirm if the mod works properly or not.

¿What do you think?

**Comment by yairm210** [comment]
I can't think of a good way to do this tbh.

**Comment by ArchDuque-Pancake** [comment]
Maybe, a line would be added automaticly in ModOptions, just like the file size or last update time is, and it would show up in-game just as those before mentioned. It would be a simple word saying: "Outdated".

**Comment by yairm210** [comment]
But where would the source of this information be?

**Comment by logicminimal** [comment]
> But where would the source of this information be?

how about a json or txt file from a new github repo that only some people with access and a specialized code can alter?

**Comment by ArchDuque-Pancake** [comment]
> But where would the source of this information be?

I guess it can be added automaticly corresponding with the last update date via a sistem.
If not, maybe what locicminimal said.

**Comment by SomeTroglodyte** [comment]
One could...
- Keep a record of all ruleset deprecations (as class heirarchy, xpath, whatever) - this includes deprecated properties and values, includes deprecations in their grace period, never gets deletions, and is maintained manually by the contributors.
- Have an external automatic agent (github actions? I'm certain there will be some offer capable of doing this) with access to that record, periodically loop over all mods like the mod manager does, and check whether any rule matches. If none, mod gets "good" in some other repo as we wouldn't have write access to the modders' repos, otherwise "outdated".

NO thank you. I'd rather program a new Unciv from scratch - in ABAP.

Alternative: Make modders declare an Unciv version they promise to be compatible with without using deprecated stuff, and trust them on that. Keep a second Unciv version inside Unciv - the one with the last new deprecation. Mod manager compares and says "compatible", "outdated" or "unknown"...

**Comment by ArchDuque-Pancake** [comment]
If it works then yes I guess, whatever is the best or easier.

**Comment by ArchDuque-Pancake** [comment]
Wait a minute, how does the "Updated" label work?

Because, you could do something similar, and it would appear after sometime.
Or, when launching the update, the dev could make a comand that makes all mods have the label added (if the update brings something that need to be update) automaticly until the mod recieves an update.

**Comment by yairm210** [comment]
This is not actionable at all on my end.
This is more a community problem.
