### ISSUE TITLE
Abuse of introduction to other civ

### ISSUE THREAD

**Issue by sockybob** [yairm210/Unciv#4272]
In the beggining of the game as soon as you meet first two civs you can offer them a trade to introduce one to another (if they didn't meet yet) for a good price and they will accept it. Also if you send each of them offer at the same turn they both can accept it and you will receive double reward. So the problem is AI doesn't take into account that it's just the very beggining of the game and it will probably meet other civilization soon enough.

The solution might be simply checking if amount of turns passed are too low, and if it is AI should reject the trade offer.

Another, more complex solution is to make reward for introduction dependent of turns passed, and maybe it can also take map size into account.

**Comment by ravignir** [comment]
3rd solution is to disable introductions, because they do not exist in civ5.

**Comment by logicminimal** [comment]
also we need what do you want for this option in trading

**Comment by saud2410** [comment]
Double introduction happens because trade offer comes first, than you get alarm saying "you have met another civ". And all offers toward civ X is accepted/denied when civ X takes turn. ← This is as major difference as the introduction itself. Introduction is so helpful. But if it's hard to change trade, and introduction should be fixed, i think it has to be deleted.
