### ISSUE TITLE
Turkish doesn't show up as an available language

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4298]
i dont think if i need to provide any screenshots, i am on 3.15.5 patch 1 and its just not there

**Comment by xlenstra** [comment]
This is, because a translator (most likely accidentally) renamed the file containing the translations from 'android/assets/jsons/translations/Turkish.properties' to 'Fixed last merge (Turkish)', so the file could not be found. This is fixed in #4287 so it should be available again from the next version
