### ISSUE TITLE
You can open city construction screen of cities you don't own under rare circumstances

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4344]
**Describe the bug**
It is possible to open the city construction screen of cities you don't own, if you traded them away at the start of your turn AND a building was completed at the start of this turn AND another construction was automatically started in this city

**To Reproduce**
1. Turn on the setting for automatically choosing new constructions to build
2. Create a situation in which you receive a trade request to give away a city on the same turn it finishes building something
3. Trade away your city
4. Click on the notification saying "Work has started on [newConstruction]"
5. You are now in the city ocnstruction screen of a city you do not own

If needed, I can provide a save file for this.
I tried if I could fix it myself quickly, but this wasn't the case, so I reported it here instead. I might try it again later

**Comment by SomeTroglodyte** [comment]
Might correlate with the quirk where you conquer, then raze or puppet (thus should not have construction control), then with 'setting for automatically choosing new constructions' OFF, if the city finishes its construction due, say, to legalism (I still maintain free buildings  should not go into razing cities) - bingo you are _forced_ to choose a construction. Forgot if I ever opened an issue for that. I vaguely remember looking into a fix and, like you, soon giving up due to "this looks like the author knew what they were doing, but I don't"...

**Comment by yairm210** [comment]
This is annoying.
The only way I can think of to resolve this is to filter the notifications at the start of the turn to get rid of 'bad' notifications, but that's SO UGLY.
Maybe filter them upon trade accepted? That sounds better to me...

**Comment by SomeTroglodyte** [comment]
Or if the source is tricky - double safety net and do a check at the destination? I mean CityScreen init/first update checks for permission and just closes itself when that fails?
