### ISSUE TITLE
Aztec jaguar's combat bonus and heal feature doesn't retain in upgrading to swordsman

### ISSUE THREAD

**Issue by qchenac** [yairm210/Unciv#4399]
I remembered in original civ5 the unique unit's feature will carry over with all future upgrades. I double checked the wiki, in jaguar and janisarry entries they both stated that their unique feature will carry during upgrades. Maybe not a bug, I kind of understand it involves some  mechanics problem but just let you know ;)

**Comment by xlenstra** [comment]
Before upgrading:
![Screenshot_20210706_211914](https://user-images.githubusercontent.com/71121390/124655208-d8005980-de9f-11eb-8b50-3f7b8cb947d0.png)
![Screenshot_20210706_211932](https://user-images.githubusercontent.com/71121390/124655221-dcc50d80-de9f-11eb-9903-11cc02c211f8.png)

After upgrading:
![Screenshot_20210706_211949](https://user-images.githubusercontent.com/71121390/124655258-e8183900-de9f-11eb-9076-90c6b2dfb18f.png)
![Screenshot_20210706_212007](https://user-images.githubusercontent.com/71121390/124655288-f1a1a100-de9f-11eb-98a3-eb3aa18c3983.png)

Does look like this is indeed the case!

**Comment by SomeTroglodyte** [comment]
Classic. Need a promotion carrying the unique instead of the baseunit carrying the unique, see 'withdraw' abilities, which are intentionally some 'inheritable' some not. There's other examples I sometimes stumble upon and then forget right away (the new Huns unique unit maybe?). 

A case for #663. But nice tileset mod you're using there. How come one does not see Unciv's window frame?

**Comment by ravignir** [comment]
Yes, some do carry over and some don't.

**Comment by yairm210** [comment]
Into #4697
