### ISSUE TITLE
Civilopedia tutorial sorting & compliment

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#4405]
All civilopedia entry is sorted in ascending order of each language, except difficulty level.([related issue](https://github.com/yairm210/Unciv/issues/2672#issue-627767191))

Similarly, I think tutorial is better to look when it's sorted in different order. For example [ Happiness ] and [ Unhappiness ] is closely related, but you have to look H for happiness, and U(far down below) for unhappiness. It's because tutorial is sorted in abc order. There are some other related entries like [ luxury resource, strategic resource ], and unit things. ([ Experience, Great people, Idle units, Injured units, ... ])

![unhappinesspenalty](https://user-images.githubusercontent.com/64586749/124684406-061a8380-df0a-11eb-80cf-746583647b49.jpg)
I tried to solve it by changing translation of entry names arbitrarily. Result is not good. Each names and corresponding translations can be used out of civilopedia. (3.15.7 vanila with LynxRo Tileset, Korean) Marked line means "Happiness: Unhappiness" in English. That's how i sorted things. It's awkward to look on combat bonus window. It is, and it should be just "Unhappiness(불행)". (I'll fix Korean.properites during next release)

I know there are many systems and related tutorials to be added. Tutorial cannot contain all information, and they even pops up in game when tutorial setting is on. But we might sort things we already have, at least in civilopedia. If some content is too short it might be merged with other related content. There are 2 ways.

1. Sorting & adding. Not merging.
(+) (Small Title) <- foldable when clicked. don't have its own entry
├ Combat
├ Experience
└ ...
(+) (Title 2)
└ ...

2. Merging & Sorting.
Depending on how much entries are merged, small title is not required.

I don't know what exact entry should be complemented or merged, or how they should be sorted. I asked myself a lot about "Is this really necessary feature?", and I'm still not sure. But at the same grade, tutorial is good to browse.

**Comment by SomeTroglodyte** [comment]
I don't completely get what you mean.

Civilopedia is sorted, correct. Sorting currently does not respect culture specific collations, known. Difficulties are in difficulty order, not alphabetically - by design.

Principle of least surprises appliles, too - and I'd expect a majority to grasp alphabetical sorting easiest, unless some visual grouping is used. That could be done, but I have no clear _and complete_ idea what these should be. (Buildings -> Science, Cultore, Growth. OK, but will all buildings fit into such a raster or... Then, this would need to be a json addition, and modders would need to adapt. Or offer some filtering capability in Civilopedia. Or some more keyboard support to page faster. Or the WIP linking ability - one could add linked 'See also' lines to jump beween related things faster. Or...)

In any case, Civilopedia display and sorting has nothing to do with the battle 'screen' your screenshot shows, except for the detail that translations go by the english string only, no calling context is used when looking for a translation, so a translation change to any string in civilopedia would also reflect everywhere else that same string is used. There's no way to change this with any feasible amount of effort, and in my opinion not the correct approach anyway. Identical strings needing different translations in different contexts is bad and should be tackled by rethinking the 'why'.

If you can offer a convincing argument (I'm not convinced) why civilopedia entries need reordering in their current flat list, I'd consider adding a 'sort' number in json, not adding prefixes to their translations.

**Comment by saud2410** [comment]
> If you can offer a convincing argument (I'm not convinced) why civilopedia entries need reordering in their current flat list, I'd consider adding a 'sort' number in json, not adding prefixes to their translations.

Tutorials have complete context when it pops up in game. However, they are sorted in ascending order in civilopedia. If you read top to bottom, it seems to lack connection - or context - each other until you read all of them. It's not hard either reading the whole entry and connecting each other's meaning. But I think it might be helpful to suggest definite context by ordering.

At the same time, I think a few entries are lack of its content.
> Roads and Railroads =
> Connecting your cities to the capital by roads\n  will generate gold via the trade route.\nNote that each road costs 1 gold Maintenance per turn, and each Railroad costs 2 gold,\n  so it may be more economical to wait until the cities grow! =
Gold from trade route is proportional to population of connected city. I think that's why it's helpful to wait connecting cities.

And... that's all. While trying to convince you I noticed i lack definite image of what & how to do; far more that i thought. I don't know about coding so i didn't expect how many ways to have "context" each other. That' why I lost my labor to fixing translation. Each entries should be dealt individually. Only after that we can decide whether they should be ordered differently. For now i think i've gotta close this issue.
