### ISSUE TITLE
Nation names

### ISSUE THREAD

**Issue by Mape6** [yairm210/Unciv#4428]
I have a question or topic regarding the nations in Unciv.
Why are some nations named after their country (e. g. Germany, England, Denmark) but others after their people (e. g. Inka, Iroquois, Azteca) and one after their city(Rome)?
If I play a nation, I would name it after their people.

**Comment by DuffLagerleff** [comment]
1st. Unciv is based on Sid Meier's Civilization 5, therefore most of its content, including names is dependent on the original franchise
2nd. It's just the fact that some peoples' countries either didn't have short names like Germany or had something hardly pronounced as a name, so instead they got their names in simplified way, like Aztec Empire. But since every nation in Unciv is empire and writing empire after some of nations and not doing so with other seems unpractical
3rd. Rome isn't just a city name. Back in my days it was city-state and then it started expansion under the name of Roman republic and later empire. Roman empire. See. Once again the same issue of writing Roman Empire empire.
4th. If you want to name them as you like you can create your mod. There's a [tutorial](https://github.com/yairm210/Unciv/wiki/Making-a-new-Civilization) for it.

**Comment by Mape6** [comment]
> 2nd. It's just the fact that some peoples' countries either didn't have short names like Germany or had something hardly pronounced as a name, so instead they got their names in simplified way, like Aztec Empire. But since every nation in Unciv is empire and writing empire after some of nations and not doing so with other seems unpractical

But there is a name for the German people: Germans. So it would be the Germans Empire. The empire of the German people. 
It's inconsistent for me as it is currently.

> 4th. If you want to name them as you like you can create your mod. There's a [tutorial](https://github.com/yairm210/Unciv/wiki/Making-a-new-Civilization) for it.

Thanks for the hint. I knew that site already. 😉

**Comment by yairm210** [comment]
I'm going according to the base game, there's no particular reason for me to change this

**Comment by jahodovykolac** [comment]
> But there is a name for the German people: Germans. So it would be the Germans Empire. The empire of the German people.
It's inconsistent for me as it is currently.

In my opinion, Aztecs were an ancient culture, you don't lead a "real" country, more like leading people of the culture - called Aztecs.
