### ISSUE TITLE
Capturing civilian water units without researching optics leads to swap crashes

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4556]
It is possible to attack units and capture civilian units in water tiles before researching optics (allow units to embark). This could lead to crashes due to possible swaps being calculated when the unit is selected, see #4237.

This is part of a bigger problem where melee water units can attack land units and vise versa, even though this was not a part of the original game.

**Comment by avdstaaij** [comment]
Like you stated, the title and first part of this issue are a duplicate of case 4 of #4237, so I believe those can be removed here. I prefer to gather all the cases of #4237 in a single issue so that I can link to it when a new case is discovered and so the reason for the crash doesn't have to be repeated every time. The second part might be better placed in #663.

@yairm210, in case you didn't see my comment in #4237 after it was closed, could you re-open the issue? I cannot do it myself because you are the one who closed it.

**Comment by xlenstra** [comment]
Closed on specific request of @avdstaaij, as he for some reason has the belief that his issue is better then mine 😒
