### ISSUE TITLE
City state gold influence is not dependent on game speed

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4647]
![Screenshot_20210726-130000_UnCiv.jpg](https://user-images.githubusercontent.com/56484801/126971606-7bcd4473-e91b-433e-b782-4fc8defdbd71.jpg)

Version: 3.15.14
Save: https://hastebin.com/raw/nukabohixo

I tried to see if this is also the case for other games as well but it seems as it isnt, one key factor here is that i got the gold gifts provide more influence policy from the free policy from the oracle which might be the problem

**Comment by SomeTroglodyte** [comment]
Nope, the bonus is applied. Base is just over 20 for the 250gp gift, due to _Epic game speed_. You should have compared with the situation before getting Philantropy - that would have shown +20/+40/+80.

Influence is still too high because someone thought `(2/3)` would be close to 0.66666666667, but it isn't. Int.div(Int) has return type Int and rounds down. Line `CivilizationInfo.influenceGainedByGift` + 5. Thus, the intended game progress modifier is broken, not the Philantropy bonus.

**Comment by logicminimal** [comment]
> Nope, the bonus is applied. Base is just over 20 for the 250gp gift, due to _Epic game speed_. You should have compared with the situation before getting Philantropy - that would have shown +20/+40/+80.
> 
> Influence is still too high because someone thought `(2/3)` would be close to 0.66666666667, but it isn't. Int.div(Int) has return type Int and rounds down. Line `CivilizationInfo.influenceGainedByGift` + 5. Thus, the intended game progress modifier is broken, not the Philantropy bonus.

well so should this issue be kept on?

**Comment by SomeTroglodyte** [comment]
Keep and change title? "City State gold gift influence not dependent on turn number as intended" or maybe a shorter version of that. From the history, that line was new in #4435 and is unchanged since then. Or close and rely on the author reading the following sooner or later:

@xlenstra  - `influenceGained *= 1 - (2/3) * gameProgressApproximate` is a dead line. I don't want to 'fix' it to use Float because -> testing and comparing with original Civ5...

**Comment by yairm210** [comment]
This sounds like a case where just making it a float resolves the problem tbh.

**Comment by SomeTroglodyte** [comment]
> just making it a float

True, trivial, I just didn't want to presume any balancing done by Xander would still be fine - if they went and matched the factors _empirically_ to known reference numbers we'd be dropping those significantly by fixing here. Well, balancing is of course possible anytime...

**Comment by xlenstra** [comment]
My empirical testing actually showed the previous gold numbers were slightly off, but as I was unable to find out why, I just rolled with it. It could very well be that this was the problem, so this solution looks fine to me.
