### ISSUE TITLE
I think the crudely drawn map functions wrongly

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4667]
i think in the original game it actually gave you a map about places you haven't explored yet but in unciv it barely shows any non explored territory, i think it might be caused by the ruins checking the position the player arrived on theruins from, despite it needing to check the tile ruins is placed on

**Comment by yairm210** [comment]
IIRC In the base game it also gives you random areas around, of which you may have explored quite a bit.
But @ravignir is the resident Original Civ expert :)

**Comment by ravignir** [comment]
So I've run this in Civ5:

https://user-images.githubusercontent.com/30041793/127545432-18d6d5f0-430b-4781-9f57-ce1f837deb09.mp4

Looks like it only discovers the places near ruins and in a direction that unit is moving into.

**Comment by SomeTroglodyte** [comment]
Any _numbers_? How many tiles uncovered could I expect from vanilla Civ5 crude-map assuming I came at the ruins in a straight line with zero visibility modifiers? On average? Estimated variance?

Testing on a prepared map, on flat desert with a 0xp warrior, moving in a straight line through a single line of ruins, counting only the map "rewards", I got 36-8-0-37-6-26-1-7-0-24-37 newly uncovered tiles until the ruins ran out. So, the best case reward isn't so bad. That insufficient data suggests a certain preference for multiples of 8 but not with any statistical significance.

Looking at the code, there's no movement direction influence, the effect is centered on the ruin tile, any tile with a distance of exactly 4 to the ruins is chosen, then the hexagon of distance 4 surrounding that, maximum 61 tiles of which the warrior can have already uncovered at most 39, at least 9. Of those, every tile has a chance of 80% to be revealed. So, getting zero new tiles has a chance of 0.2 ^ (61-39) * 100 = 4.2 e-14 % - so getting that twice is extraordinary - must have been something wrong with my measurement conditions. Best case expectation would be (61-9)*0.8 = around 41 tiles.

Limiting the initially chosen "center of the crude map" to unexplored tiles would significantly increase the minimum tiles discovered without altering the maximum, and would 'skew' the result perceptually 'in the direction the unit is moving' without actually determining said direction. Then, one could compensate by reducing the map radius and/or uncover probability.

I might code something if I had proper reference numbers...

**Comment by ravignir** [comment]
So i was just lucky with ruins uncovering tiles in the direction my unit is coming to.
the distance seems to be 8 tiles from the ruins, and it uncovers usually 30+ tiles. my worst was 22 tiles and best was 46 tiles.

**Comment by ravignir** [comment]
the shape of uncovered terrain appears to be a hexagon with a radius of 5 (in other words, same as max size brush in unciv map editor). it also tends to be in the direction that was not yet discovered.

**Comment by SomeTroglodyte** [comment]
Radius 5 _including_ the center tile is what Unciv does, and Stats 22-46 would match Unciv _if_ we did any avoiding the already discovered area which at the moment we don't. 

Simplest approach would be to filter the center-of-effect tile to only undiscovered ones (+ prevent crashing due to empty list). Tests of current code and said change on a special map (optimum conditions), and removal of the tile-hash-based-random (which is there to thwart reload-retry) show the statistics aren't changed that much - min about 8, max about 45, average 32.6 with a variance of 145 for the current code, sample size 60 "crude maps" events (5 plays of the map - see below); The modified code has about the same min/max/avg (sorry didn't keep the spreadsheet) but a significantly reduced variance of 82, and the results 'feel' a little more useful. And in different situations (scout has more visibility or doesn't run in a straight line) the improvement should be more detectable. Maybe I'll PR it later - if I even kept it.

<details><summary>"Testing ground" map (Play Babylon, 1AI=Greece, No CS or Barb, run north disbanding all other units and taking no promotions):</summary>

H4sIAAAAAAAAAK3d327myHHG4VvxBYgBq7qr/+gsceKcOHBg+8zwgbz7wStgZ2YhaRI7i733DNkcAyuz5d9rak92BugpaOYVyeZT1Z9+/PDww38/PD18uL3cnp7vf/z45Vf3v/38+PH5F7+/Pb/cvfz1h9v9Lz8/v3z6cPf83cOX3/z29s3Lw8c/f/7+4enuyx/+3eP/3e5/fHr49vHz873H3f8+fvvy3b2vd9/dHv/83cu9revdXnQU+enu+Xb79t6K1+g5m5dqdy+3Dz/cnh5ePj/d/uMvL0+3D7ePt+fn+/Vfou//lZ/uXh6/v/368fnl/g8//vDp+fHl8dPH+x//ch9x99f7HD/d/enh+fb729PTw+PH+998c3v4+NPdzxfmbWH++cJffnp4fnm9MG0L088X/vvt+fb0dyt9W+lkpW0r7ecr/+vT548vX37xeu26rV1B1dy/rEydrGzbykZW1m1lJSvLtrKQlVtGKcjKLaSUycotpURSyltKiaSUt5SSkZVbRolklLaMnGSUtoycZJS2jJxklLaMnGSUtoycZJS2jJxklLaMnGSUtoycZJS2jJxklLaMnGTkW0ZGMvItIyMZ+ZaRkYx8y8hIRr5lZCQj3zIykpFvGRnJyLeMjGTkW0ZGMvItIyMZ2ZYRici2iEhCtiVEArItIJKPbfmQeGx/FpGF+12OLNwvILJwz4Ys3KIhyWzBLKTiFsxCvsYtmIX8rbdgFvLvuAWzoAfQthDdL7eF6PLeFqLvx23hP/4O3/6xSSzLXg9dhcv+NaJLe9n/3uh+sez/lugmtOz5oDvbsmeObpfL/n2E7sHL/r2JbuzL+H4nt6Jlv4YW9Axa9gtzQU+2Zb/aF/S8XPZbyIKewst+X1rQs33Zb3YL2jEs+x10QfuQZb8tL2h3s9i4paDY9gfIgnZiy/5YWtD+btkfdgvaNS77I3RBe9FlfzAvaIe77I/7Be2bl30TsaDd+LJvTRa0x1983LVRbvs2akHvI8u+OVvQW86yb/kW9O607BvJ5fU72WTtnht601v2Te+C3h+XfSu9vH4pnazdc3v9pjtZOx6MKLf9ZWLJKLf9FWXJKLf9xWfJKLf9dWoJlNv+krYEym1/9VsC5ba/UC7xKrczIFj2t9QlXsV2ig67ThSwMJ8wxlwn0J7HsWPYiWO8qRPoHbljx2jYMSp2jIIdI7BjZOwYCTuGY8cw7BgrdYz9ImWO0bBjVOwYBTtGYMfI2DESdgzHjmHYMVbqGPsDkDlGw45RsWMU7BiBHSNjx0jYMRw7hmHHWKlj7JtL5hiNOkaljlGoYwR1jEwdI1HHcOoYRh1jhY7RIWM0yhiVMkahjBGUMTJljEQZwyljGGMMRBh/wwn2gsUdI3HHyNwxgjtG4Y5RuWM07hidO8bACQgZJkCGC5CRBMjIAmSEABlFgIwqQEYTIKNzyBg4ASHDBMhwATKSABlZgIwQIKMIkFEFyGgCZHQOGQMnIGSYABkuQEYSICMLkBECZBQBMqoAGU2AjM4hY+AEhAwTIMMFyEhnkPEWTryKbW4OBCcSxQnHOGEYJ1aOE4McEE40jBMV40TBOBEYJzLGiYRxwjFOGMaJleLEIAeEEw3jRMU4UTBOBMaJjHEiYZxwjBOGcWKlODHIAeFEwzhRMU4UjBOBcSJjnEgYJxzjhGGcWClODHJAONEwTlSKE4XiRFCcyBQnEsUJpzhhFCdWiBMd2kSDNlGpTRRqE0FtIlObSNQmnNqEMZuA4xULnK/4mziwzTfHicxxIjhOFI4TleNE4zjROU4c4sDSMkEnXNCJJOhEFnQiBJ0ogk5UQSeaoBOd68QhDkwnTNAJF3QiCTqRBZ0IQSeKoBNV0Ikm6ETnOnGIA9MJE3TCBZ1Igk5kQSdC0Iki6EQVdKIJOtG5ThziwHTCBJ1wQSeSoBOZ60RoOlHBwnTCGHOdIMkOnUCOsZ44xps6gRr4DTtGxY5RsGMEdoyMHSNhx3DsGIYdY6WOMXQCOUbDjlGxYxTsGIEdI2PHSNgxHDuGYcdYqWMMnUCO0bBjVOwYBTtGYMfI2DESdgzHjmHYMVbqGEMnkGM07BgVO0ahjhHUMTJ1jEQdw6ljGHWMFTpGh4zRIGNUyBiFMkZQxsiUMRJlDKeMYYwx4HjFAucrvuoE26dzx8jcMYI7RuGOUbljNO4YnTvGgRMsLBMgwwXISAJkZAEyQoCMIkBGFSCjCZDROWQcOMEgwwTIcAEykgAZWYCMECCjCJBRBchoAmR0DhkHTjDIMAEyXICMJEBGFiAjBMgoAmRUATKaABmdQ8aBEwwyTIAMFyAjCZCRzyDjLZx4FdvcHAhOOMUJwzixUpwY4ABxomGcqBgnCsaJwDiRMU4kjBOOccIwTqwUJwY5oE1swzhRMU4UjBOBcSJjnEgYJxzjhGGcWClODHJAONEwTlSMEwXjRGCcyBgnEsYJxzhhGCdWihODHBBONIwTFeNEwTgRFCcyxYlEccIpThjFiRXiRIc20aBNVGgTBdpEUJvI1CYStQmnNmHMJuB4xQLnK76SA9t9Y5zIHCeC40ThOFE5TjSOE53jxCEOLCsTdMIFnUiCTmRBJ0LQiSLoRBV0ogk60blOHOLAdMIEnXBBJ5KgE1nQiRB0ogg6UQWdaIJOdK4ThzgwnTBBJ1zQiSToRBZ0IgSdKIJOVEEnmqATnevEIQ5MJ0zQCRd0Igk6kQWdCK4TRdOJBhb6CWPMdeJVAm9+QkSgtUMoMlvbTjTjDaFAllGwZQS2jIwtI2HLcGwZhi1jpZYxhAJZRsOWUbFlFGwZgS0jY8tI2DIcW4Zhy1ipZQyhQJbRsGVUbBkFW0Zgy8jYMhK2DMeWYdgyVmoZQyjQm17DllGxZRRsGYEtI1PLSNQynFqGUctYoWV0SBkNUkaFlFEgZQSkjEwpI1HKcEoZxigDjlgscMbiq1Cw3Tq2jIwtI7hlFG4ZlVtG45bRuWUcQMGiMgEzXMCMJGBGFjAjBMwoAmZUATOagBmdY8YBFAwzTMAMFzAjCZiRBcwIATOKgBlVwIwmYEbnmHEABcMMEzDDBcxIAmZkATNCwIwiYEYVMKMJmNE5ZhxAwTDDBMxwATOSgBlZwIw4w4y3gOJVbHN3IEBhFCjWE6A43x31E544X9kEnKgYJwrGicA4kTFOJIwTjnHCME6sFCcGOSCcaBgnKsaJgnEiME5kjBMJ44RjnDCMEyvFiUEOCCcaxomKcaJgnAiMExnjRMI44RgnDOPESnFikAPCiYZxomKcKBgnAuNExjiRKE44xQmjOLFCnOjQJhq0iQptokCbCGgTGdpEojbh1CaM2QQcsVjgjMVXcmD7b4wTGeNEYJwoHCcqx4nGcaJznDjEgSVlgk64oBNJ0Iks6EQIOlEEnaiCTjRBJzrXiUMcmE6YoBMu6EQSdCILOhGCThRBJ6qgE03Qic514hAHphMm6IQLOpEEnciCToSgE0XQiSroRBN0onOdOMSB6YQJOuGCTiRBJ7KgEyHoROE6UTWd6GChnTDGXCfQG3LHjtFOHONNnSDfLUMnkGMEdoyMHSNhx3DsGIYdY6WOMXQCOUbDjlGxYxTsGIEdI2PHSNgxHDuGYcdYqWMMnUCO0bBjVOwYBTtGYMfI2DESdgzHjmHYMVbqGEMnkGM07BgVO0bBjhHYMTJ2jIQdw6ljGHWMFTpGh4zRIGNUyBgFMkZAxsiQMRJkDKeMYYwx4HjFAucrvuoE26tjx8jYMQI7RsGOUbljNO4YnTvGgRMsKBMgwwXISAJkZAEyQoCMIkBGFSCjCZDROWQcOMEgwwTIcAEykgAZWYCMECCjCJBRBchoAmR0DhkHTjDIMAEyXICMJEBGFiAjBMgoAmRUATKaABmdQ8aBEwwyTIAMFyAjCZCRBcgIATLKGWTsPnD3dHv+9Pnpm9v9rx6fv5tQxasQ5wJBqGKdUcWbX8rgCAQXDcNFFeCiYLgIDBcZw0XCcOEYLgzDxUrhYnAEgouG4aJiuCgYLgLDRcZwkTBcOIYLw3CxUrgYHIHgomG4qBguCoaLwHCRMVwkDBeO4cIwXKwULgZHILhoGC4qhouC4SIwXGQMFwnDhWO4MAoXK4SLDt2iQbeo0C0KdIuAbpGhWyToFg7dwphbwNGLBc5efOUItjvHcJExXASGi4LhomK4aBwuOoeLQyNYTibIhQtykQS5yIJchCAXRZCLKshFE+Sic7k4NILJhQly4YJcJEEusiAXIchFEeSiCnLRBLnoXC4OjWByYYJcuCAXSZCLLMhFCHJRBLmoglw0QS46l4tDI5hcmCAXLshFEuQiC3IRc7m4exm//dXt4eXzl3f8+z/85uH58fmPE6U4zRPXqP+sdDRJOtDC9YREqHRI/wp3jx9+ePr0P7cPt48v9797eXh6efz4519/+uZhq/mL/3y63b65nSoJ8pR64ilvKslEVO6ePj18++Wre/n8fP/bh8fvt9+e2snpd/LP/o7/+vGbxy///8XT58ePz6RunprMtbppKjjX6vrUe67VtakOXau7Ti3pUt3hSefXwqW6bepU1+rWqWpdq1umBnatbkzF7FrdPPW1a3XTVOOu1fWp3V2ra1Ppu1Z3nbrgpbrDBt//ehuS+P7X23DH97/ehlK+//U2TPP9r7choO9/vQ0vff/rbejq+19v+2vq+Zvytbrr1Hgv1R3O+/7X21Dh97/ehiG///U2xPn9r7fh0+9/vQ3Nfv/rbdj3+19vQ8rf/3rbOe8cFK/VXWdef6lsn+H+papt1gq4VLXOGgeXqpZZm+FS1Zg1Ja69VMxaGNe2TrOGx7UHxKw9cu0ymDVTLlSdtV0ufaHLfLr0Wt35531dqzv/KWzX6uZpz+ha3Zh2mK7VLdN+1LW6ddq9ula3TXtd1+r2eWfs4oWxzhtpFyvbvO12sbLPm3QXK6d5S+9i5TxvAF6sHPN24cXKZd5cvFi5zluRFyu3eePyYuU+b3NefIis86boxco2b6FerOzzhuvFymnenr1YOc+buRcrx7z1e7FymTeKL1au87byxcpt3oS+WLnPW9YXN1zrvMF9sbLN2+EXK/u8eX6xcpq32i9WzvPG/MXKMW/jX6xc5k3/i5XrfETgYuU2Hyi4WLnPxw8uvpys82GFi5VtPtpwsbLPByEuVk7zsYmLlfN8yOJi5ZiPZEyHA0jdoo9vvD108G8Pf/rr959Iz//rzIZ8JOSY2cCHTsjMxhi+0Gc22nRm43SaAs1dFGHuIk7mLs6r5umExelsA5oh9ukUxOn8ATrHsk4nFU5nBNAZiTadJjjt46NzLGXa8T/ttaNzLHnalT/th6NzLD7tnJ/2rNE5lnXa3T7tK6MzEm3agT7t/aJzLGXaJT7tz6JzLHnayT3toaJzLD7ttp72OdE8/jrtiJ72ItEhiTbtWp72C9E5ljLtLJ729NA5ljzt/p323dA5Fp926E57Y+gcyzrtop00sEhCbdboOmkykXTKrBl10ghCT6FZw+ikWUN/cCn9iM5ZIv/wDy/wzMrXtgUb0J42OE5bC2jIN6ZNiFP+RwO+ddooOCV6NJTdp5g/UXR2BMLm4j6RbnZ0Jc1VfKLR7OhKzOV6Isbs6Eqd6/JEddnRlT4X4Im8siMQNlfaiY6yoytpLqkTwWRHV2KunRNlZEdX6lwkJxLIjq70uRpOtI4dgbC57E1Ejd0Z01zfJurFjq7EXMgmMsWOrtS5Yk30iB1d6XNpmggP+4GfNtegicKwoytpLjYTKWFHV2KuKhPPkJxkwhLXjrS0f5Y2ukYb4MNE95LkA0oHZqAPhqiYPcoJe7yJGegDPDJmj4TZwzF7GGaPlbLHfrEz9miYPSpmj4LZIzB7ZMweCbOHY/YwzB4rZY/9QcrYo2H2qJg9CmaPwOyRMXskzB6O2cMwe6yUPfZNKmOPhtmjYvYomD0Cs0fG7JEwezhmD8PssVL26FQ9GlSPCtWjQPUIqB4ZqkeC6uFQPQypB/vcjmU6a3pqG2y3jxUkYwUJrCAFK0jFCtKwgnSsIMM2GIOYwCAuMEgSGCQLDBICgxSBQarAIE1gkM4ZZNAGZBATGMQFBkkCg2SBQUJgkCIwSBUYpAkM0jmDDNqADGICg7jAIElgkCwwSAgMUgQGqQKDNIFBOmeQQRuQQUxgEBcYJAkMkgUGCYFBisAgdc4gE6o4+wmniCrAz1AdAkGoolGqqJgqCqaKEKgiY6pImCocU4VhqlgpVQyAQFTRMFVUTBUFU0VgqsiYKhKmCsdUYZgqVkoVAyAQVTRMFRVTRcFUEZgqMqaKhKnCMVUYpoqVUsUACEQVDVNFxVRRMFUEpoqMqSJhqnBMFYapYqVU0alUNCoVFUpFgVIRUCoylIoEpcKhVBiSCjabsbw1nPF3AsH25JgqMqaKwFRRMFVUTBUNU0XHVDEAglmFcatwwSqSYBVZsIoQrKIIVlEFq2iCVXRuFYc/MKswwSpcsIokWEUWrCIEqyiCVVTBKppgFZ1bxeEPzCpMsAoXrCIJVpEFqwjBKopgFVWwiiZYRedWcfgDswoTrMIFq0iCVWTBKkKwiiJYRRWsoglW0adW8XeP61XTCQcL2wljTHXiNWO8+cmZna2NE8t4UyjQHjJhy3BsGYYtY6WWMYQCWUbDllGxZRRsGYEtI2PLSNgyHFuGYctYqWUMoUCW0bBlVGwZBVtGYMvI2DIStgzHlmHYMlZqGUMokGU0bBkVW0bBlhHYMjK2jIQtw7FlGLaMlVpGp5TRKGVUShkFUkZAysiQMhKkDIeUYYgy2MDFwiYuDqLAMxJs74ctI7BlFGwZFVtGw5bRsWUMoWCYYRwznGNGEjAjC5gRAmYUATOqgBlNwIzOMeMACoYZJmCGC5iRBMzIAmaEgBlFwIwqYEYTMKNzzDiAgmGGCZjhAmYkATOygBkhYEYRMKMKmNEEzOgcMw6gYJhhAma4gBlJwIwsYEYImFEEzKgCZjQBM/oZZrwFFK9im7sDAYpKgaKcAMX57i1OeOJ8ZRZwImGccIwThnFipTgxyAHhRMM4UTFOFIwTgXEiY5xIGCcc44RhnFgpTgxyQDjRME5UjBMF40RgnMgYJxLGCcc4YRgnVooTgxwQTjSMExXjRME4ERgnMsaJhHHCMU4YxomV4kSnNtGoTVRqE4XaRECbyNAmErQJhzZhyCbYiMXCZiwOc8CfOYGnItBeLjBOFIwTFeNEwzjRMU4McmA6YVwnnOtE4jqRBZ0IQSeKoBNV0Ikm6ETnOnGIA9MJE3TCBZ1Igk5kQSdC0Iki6EQVdKIJOtG5ThziwHTCBJ1wQSeSoBNZ0IkQdKIIOlEFnWiCTnSuE4c4MJ0wQSdc0Ikk6EQWdCIEnSiCTlRBJ5qgE53rxEEOSCdM04kEFtYTxpjrBPqwyMCOkU8c402dQL0tx45h2DFW6hhDJ5BjNOwYFTtGwY4R2DEydoyEHcOxYxh2jJU6xtAJ5BgNO0bFjlGwYwR2jIwdI2HHcOwYhh1jpY4xdAI5RsOOUbFjFOwYgR0jY8dI2DEcO4Zhx1ipY3TKGI0yRqWMUShjBGWMDBkjQcZwyBiGGIONVyxsvuLgCbZdpY6RqWMEdYyCHaNix2jYMTp2jKETLB/jkOEcMhKHjMwhIwTIKAJkVAEymgAZnUPGgRMMMkyADBcgIwmQkQXICAEyigAZVYCMJkBG55Bx4ASDDBMgwwXISAJkZAEyQoCMIkBGFSCjCZDROWQcOMEgwwTIcAEykgAZWYCMECCjCJBRBchoAmR0DhkHTrzK7S2ceBXb3BwIThSKE4FxImOcSAJOOMYJwzixUpwY5IBwomGcqBgnCsaJwDiRMU4kjBOOccIwTqwUJwY5IJxoGCcqxomCcSIwTmSMEwnjhGOcMIwTK8WJQQ4IJxrGiYpxomCcCIwTGeNEwjjhGCcM48RKcaJTm2jUJiq1iUJtIqhNZGoTCdqEQ5swZBNsvGJh8xWHObBdPsWJTHEiKE4UihMV40TDONExTgxyYDphXCec60TiOpG5TgTXiSLoRBV0ogk60blOHOLAdMIEnXBBJ5KgE1nQiRB0ogg6UQWdaIJOdK4Thziw+5YJOuGCTiRBJ7KgEyHoRBF0ogo60QSd6FwnDnFgOmGCTrigE0nQiSzoRAg6UQSdqIJONEEnOteJQxyYThjXCdd0IoOF5YQx5jqBfjRFxo6RThzjTZ1AI7qGHWOljjF0AjlGw45RsWMU7BiBHSNjx0jYMRw7hmHHWKljDJ1AjtGwY1TsGAU7RmDHyNgxEnYMx45h2DFW6hhDJ5BjNOwYFTtGwY4R2DEydoyEHcOxYxh2jJU6RqeM0ShjVMoYhTJGUMbIlDESZQyHjGGIMdh4xcLmKw6eYFt36hiZOkZQxyjUMSp1jIYdo2PHGDrBIMM4ZDiHjMQhI3PICA4ZhUNGFSCjCZDROWQcOMEgwwTIcAEykgAZWYCMECCjCJBRBchoAmR0DhkHTjDIMAEyXICMJEBGFiAjBMgoAmRUATKaABmdQ8aBEwwyTIAMFyAjCZCRBcgIATKKABlVgIwmQEbnkHHgBHum2xlkvIUTr2KbmwPBiaA4kTFOJIwTLuCEYZxYKU4MckA40TBOVIwTBeNEYJzIGCcSxgnHOGEYJ1aKE4McEE40jBMV40TBOBEYJzLGiYRxwjFOGMaJleLEIAeEEw3jRMU4UTBOBMaJjHEiYZxwjBOGcWKlONGpTTRqE5XaRKE2EdQmMrWJRG3CqU0Ysgk2XrGw+YrDHNjOmeJEpjgRFCcKxYlKcaJRnOgYJwY5MJ0wrhPOdSJxnchcJ4LrROE6UblONEEnOteJQxyYTpigEy7oRBJ0Igs6EYJOFEEnqqATTdCJznXiEAemEybohAs6kQSdyIJOhKATRdCJKuhEE3Sic504xIHphAk64YJOJEEnsqATIehEEXSiCjrRBJ3oXCcOcWA6YYJOONeJpOkEWRgnjDHXCbR1TNgx/MQx3tIJdlxkpY4xdAI5RsOOUbFjFOwYgR0jY8dI2DEcO4Zhx1ipYwydQI7RsGNU7BgFO0Zgx8jYMRJ2DMeOYdgxVuoYQyeQYzTsGBU7RsGOEdgxMnaMhB3DsWMYdoyVOkanjNEoY1TKGIUyRlDGyJQxEmUMp4xhjDHYeMXC5isOnmDbYeoYmTpGUMco1DEqdYxGHaNTxxg6wSDDOGQ4h4zEISNzyAgOGYVDRuWQ0ThkdA4ZB04wyDABMlyAjCRARhYgIwTIKAJkVAEymgAZnUPGgRMMMkyADBcgIwmQkQXICAEyigAZVYCMJkBG55Bx4ASDDBMgwwXISAJkZAEyQoCMIkBGFSCjCZDROWQcOMEgwwTI8DPIeAsnXsU2zOGPP/0/21gj1cVeAQA=
</details>
