### ISSUE TITLE
Mod for Civ 2 GamePlay

### ISSUE THREAD

**Issue by crhy** [yairm210/Unciv#4702]
I've played all the Civ games, and while they all have their pluses and minuses, for me by far the most fun version was Civ 2.

I would love to see a mod of UnCiv that was as close as possible to vanilla Civ 2.

Heck, I'd even pitch in for a bounty on that.

Let me know fam!

Oh, and here's a supporting article:
https://gamervw.com/2018/06/29/why-civilization-ii-best-game/

![Civilization-II](https://user-images.githubusercontent.com/21183395/127755582-835ccff2-e7e6-4d8e-b892-89f42fd0cd29.jpg)

**Comment by ArchDuque-Pancake** [comment]
You could mod it your self, modding Unciv is pretty easy.
Either way, I belive this Github issues are only for base game issues.

**Comment by logicminimal** [comment]
> You could mod it your self, modding Unciv is pretty easy.
> Either way, I belive this Github issues are only for base game issues.

bare modding probably isnt enough as civ 2 doesnt even use hexagonal tiles. you can add some of the features from civ 2 using mods and PR'ing some code that your mod will specifically use but i doubt if it will go beyond that

**Comment by SomeTroglodyte** [comment]
True, translating the numbers to account for a tile having 6 equal neighbors instead of 8 unequal ones would be the biggest mod challenge. 

But you can still play the original - set up a VM with the last Windoze version supporting 16-bit, copy WinG.dll into the system folder, copy exe and assets, run it. :cowboy_hat_face:  I think I have all the original CD's including expansions somewhere 1-2 meters behind my left shoulder in that shelf...

**Comment by yairm210** [comment]
This is not an issue regarding the game itself. You can post this on the Discord, but as an issue I'm closing this now.
