### ISSUE TITLE
Chi vince? Who's the winner?

### ISSUE THREAD

**Issue by Eddiri** [yairm210/Unciv#4767]
**Describe the bug**

**To Reproduce**

If game data is required, please add from menu, save game, copy to clipboard, paste here

**Expected behavior**

**Screenshots**

**Additional context**
![Screenshot_2021-08-05-09-28-30-145_com unciv app](https://user-images.githubusercontent.com/88480554/128312540-6ffe9233-0599-4218-be2d-41ac4bcad3e9.jpg)

**Comment by Eddiri** [comment]
I lost the game but it looks like not from the screenshot.why?

**Comment by xlenstra** [comment]
If I had to guess (difficult without a save file), it is because Carthage won a scientific victory on its turn, and you only won it on your turn, later in the turn order. As you won both in the same turn, but Carthage's turn was earlier, they won instead.
However, we still update this screen even after someone has won for when you go into 'one more turn'-mode, so when you finished your spaceship at the start of your turn, the boxes were still marked green, even though you had already lost.

**Comment by Eddiri** [comment]
ok Thanks.
bye
Edoardo
________________________________
