### ISSUE TITLE
UI suggestion: Don't re expand city build selections after first selection

### ISSUE THREAD

**Issue by bensigg** [yairm210/Unciv#4807]
When I go into a city screen, and I don't want to think about units or wonders, because I know I want to build a building / city improvement, I collapse those other categories with that little downwards triangle. This is great.

But then I try to click through the available options, to compare the details of different options, and suddenly those other categories have un-collapsed, and my scroll position doesn't recalculate. So I have to scroll far down, just as if I never collapsed those other categories in the first place. This defeats the entire benefit of using the little "collapse category" arrow in the first place.

I suggest not re-expanding categories just because the user clicked on something. Or at the very least, if you have to re-expand, recalculate the scroll position such that "the thing that was just clicked on" is still visible in the same spot it was a moment ago.

**Comment by logicminimal** [comment]
i remember seeing this bug reported on the discord a while ago

**Comment by SomeTroglodyte** [comment]
Old hat. I tried an 'Expanders remember their state' approach a while ago and went a bit overboard, so that died. Look for closed unmerged PR's by me if you want. Stealing the stacktrace from an empty Exception and abuse that to get a unique ID for some Widget _was_ too clever by half. But I haven't forgotten.
