### ISSUE TITLE
Option to 'View City' when annexing

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#4829]
It would be great to have a button to see what the city has before buying, trading or conquering.
This would allow you to see which buildings, wonders and stats the city has and help you decide better what to do with your new city.

**Comment by ravignir** [comment]
Yup, that thing exists in civ5 but only when you conquer a city and you have an option to puppet/annex/raze/liberate. To see the city without conquering you need a spy in it.

Also - add an option to close found religion/pantheon etc. screens

**Comment by SomeTroglodyte** [comment]
> Also - add an option to close found religion/pantheon etc. screens

What, a second one?

**Comment by ravignir** [comment]
> 
> 
> > Also - add an option to close found religion/pantheon etc. screens
> 
> What, a second one?
I am blind (or generalizing) I guess, but there is no cancel button when choosing free great person.

![z](https://user-images.githubusercontent.com/30041793/128981482-e6879aa7-4322-4398-b837-2ccb23be809f.png)

**Comment by logicminimal** [comment]
> > 
> > 
> > > Also - add an option to close found religion/pantheon etc. screens
> > 
> > What, a second one?
> I am blind (or generalizing) I guess, but there is no cancel button when choosing free great person.
> 
> ![z](https://user-images.githubusercontent.com/30041793/128981482-e6879aa7-4322-4398-b837-2ccb23be809f.png)
> 

free tech, free policies also. you cant cancel them

**Comment by logicminimal** [comment]
> If we reactivate those buttons, the freebie would be lost. Also, excessive quoting.

why would it be lost and cant we just squeeze in an extra button in there?

**Comment by yairm210** [comment]
This is a matter of gameplay, not UI. You can't postpone these 'Free X' additions.

**Comment by alextfish** [comment]
I'm not saying you should be able to Postpone them, but it'd be nice to be able to check the state of your empire to make a more informed choice.

**Comment by CrsiX** [comment]
I'm just throwing ideas into the ring. Is the following behavior feasible?
1. Creating a save game
2. Showing the city as if it was annexed
3. Close the city screen
4. Restore the saved state & delete the save file
5. Don't allow to show the city screen again (optional?)

Essentially, this is what I'm sometimes doing manually, to view the possibly annexed city. You may call it a little kind of cheating, though.

**Comment by CrsiX** [comment]
> You read https://github.com/yairm210/Unciv/pull/9158?

Yes, that's why I threw save & restore into the ring. Since you talked about mods and unforeseeable side-effects, save & restore is the only way to _make sure_ (not just try to make sure) the game is not affected afterwards, AFAICT. Unit tests are good and everything, but they simply can't check everything, especially having _no_ side-effects (which may only be relevant in longer games/simulations or so). I don't know _which_ side-effects there might be, though, it's just a general thought.

> Save & reload is very expensive

That's true. But for example, auto-saving is also done each turn (as detached job, I suppose), which may be expensive as well.
If you want a feature and there's no better way, an however expensive way becomes the best way, doesn't it?

**Comment by CrsiX** [comment]
I'm wondering: should that mechanic be only available in single-player games, not multiplayer?
For multiplayer games, it could have other side-effects that may leak additional information that wouldn't be available otherwise (even though I have no particular example for such). What do you think?

Note that I don't know how original Civ 5 handles that view city feature for multiplayer games.

**Comment by Caballero-Arepa** [comment]
In reconsideration, a lot has happened since 2 years ago, now we have more info than before, for the wonders, and now I think it is now a... I don't know how to say it... it's not important nor necessary any more.
