### ISSUE TITLE
Some advices from Smashfanful

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#488]
I have some advice to give to you:
-Once you've completed all Tradition policies, the first four cities should have an Aqueduct.
-Once Honor has been adopted, you also gain some Culture when you kill a barbarian unit.
-Civilopedia is barely translated in Italian (maybe also in other languages, I didn't see them)
-Also, everyone (including me) is still stuck at technologies like Chemistry when we're close to 1900 AD.

**Comment by yairm210** [comment]
- Tradiion - apparently this is a Vanilla vs G&K difference, since we're not 100% committed to G&K et I'm fine with staying with the current form until we add game modes for different Civ versions
- Honor - I will create a separate issue for this
- Civilopedia - good point, I don't use it so I pretty much neglected it up till now =\ separate issue for this as well
- Techs - CRITICAL POINT! The tech costs were in dire need of calibration, I haven't touched those numbers basically since I first inputted the tech tree and the game is now out of whack because of this, THANK YOU!
