### ISSUE TITLE
Cannot download mods using github links

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#4931]
the download mod from link absolutely does not work, atleast for me.

like try typing in www.github.com/logicminimal/Togglemod-Sightbonus/ and it will just fail, i tried to add unciv-mod topic to it then downloaded it directly from the game and it did work without any problems.

also another suggestion: enable the copy paste field for download from url button, i really can't type it myself, especially on mobile.

and dont make the field start with github.com/... it just causes frustration

edit: and add an option to get link from clipboard

**Comment by xlenstra** [comment]
Problem here is that the master branch of your repository is called 'main' instead of 'master'.

**Comment by logicminimal** [comment]
> Problem here is that the master branch of your repository is called 'main' instead of 'master'.

can we just change it to download the sole branch if no other branches exist?

also a question; does the current system use repo names to detect seperate mods or their id? (will the game still act the same about my mod if i change its repo name?)

**Comment by logicminimal** [comment]
> Problem here is that the master branch of your repository is called 'main' instead of 'master'.

btw why does it work differently when downloading from url and downloading from unciv? shouldnt it hypothetically work the same as it takes the code from main branch as well?

**Comment by SomeTroglodyte** [comment]
You're repeating yourself, I'm sure. I already explained somewhere that if and only if the mod is discovered through the repo search query (by the unciv-mod topic), then it knows the default branch name, because it's included in the search response. If you use the manual URL and your branch is not master, then you can and must give it the URL of the ZIP not the repo, otherwise it would need at least an extra roundtrip. All that has already been explained when the size and timestamp were discussed.

**Comment by yairm210** [comment]
Not a bug, working as intended. Just rename your main branch to master.
