### ISSUE TITLE
.apks instead of (or together with) .aab

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#4980]
Hi. As we all know Android App Bundles are not installable formats but a format to publish your applications in Google Play Store. Thus, directly installing it on Android is not possible. There are some apps in google play store that Let's you install split apk formats such as .apks but not support direct installation of .aab

I found one app to do so but it is not recommended. Reason? It uploads aab into their server, convert it to apk and sends it back signing it with their own key which obviously would make you dependent on them because we all know application signed with one key cannot be installed over another.

Thus my suggestion is uploading split apk format .apks instead of .aab in github. My reasoning? Android provides official tools for direct conversion of .aab to .apks These Split apk formats can be easily installed with apps like [SAI](https://play.google.com/store/apps/details?id=com.aefyr.sai)

Link to `bundletool` by Android: https://developer.android.com/studio/command-line/bundletool

**Comment by logicminimal** [comment]
on top of that i have been unable to get past 4 updates due to how version rolling works on google play, im on 3.16.4-patch2 currently

**Comment by touhidurrr** [comment]
> another problem about this is that i have been (and probably others have been) unable to get past 4 updates due to how version rolling works on google play, im on 3.16.4-patch2 currently, as it doesnt let us the download the latest version before that newest one, which if happens to be a patch gets ignored

Same is me. I couldn’t play with a player with version 3.16.7 today. He couldn’t join the game. I wrote in in Discord.

**Comment by AdityaMH** [comment]
After i trying to install by converting .aab to .apks on google console and other third-apps. They say something wrong on certificate.
so always failed yet.

**Comment by touhidurrr** [comment]
> After i trying to install by converting .aab to .apks on google console and other third-apps. They say something wrong on certificate.
> so always failed yet.

@AdityaMH it's given. Applications on Google Play Store are signed with a play store key. And the apk files you converted using the app you found are signed by their keys. Now recent Android version rejects any Application Installation if they are detected to be signed with some other key than the currently installed one. Now for cryptographical reasons these signings cannot be faked. Which means you can only install Play Store Signed Versions over Play Store Signed Versions. And some other signed version over some other signed versions.
Or, simply to install an apk downloaded from a different source you need to uninstall the current one. That's for security reasons so that someone cannot make you install some modded app in your phone that looks like exactly some other apk.
Now, split apks doesn’t exactly solve this problem, but it makes them more secure. Since you are not using some converter that would sign the apk with their keys making you dependent on them. You still need to uninstall the Play Store apk but It's better.

**Comment by SomeTroglodyte** [comment]
Bullshit. The aab's are not for you. If you want to go g00gle, go to the pay store and accept their limits. If not, go F-Droid and accept their limits, or build yourself. Any signature incompatibilities are not our problem because you only get them when you don't know what you're doing - in which case you shouldn't even try but take one of the first two options.

**Comment by yairm210** [comment]
A. There's no need to *convert* anything.
We have source code. We have a compilation setup. We can build apks.

B. You can't mix-and-match signing in any configuration. You have to pick one release stream (Github, Google Play, F-droid) and stick with it.
You're also going to have to accept that if you try to move from one signing to the other, you're going to lose your existing files. I'm not *100% sure* that this is what will happen, but that's what *I* would have programmed in the case of signing mismatch, in order to mitigate data security and privacy issues.
