### ISSUE TITLE
Just Some random crappy Ideas

### ISSUE THREAD

**Issue by adeliosteve** [yairm210/Unciv#4985]
Worker AI improvements according to the situation
-If a city is starving the automate system didnt care at all about that,i mean i can just manually change it but its pretty anoying 
(Also probably add it in the units settings so it can be changed if you didnt want it)

Wounded affects
-If a unit is wounded add some affects to it like reduced range,slower fortification
-slowly take tiny amounts of dmg
-the affects last until healed 75 percent of hp
(Ill say put it in higher dificullties to add challenge)

Seasons
-Add the four seasons which each have their own affects
-seasons gets more challanging the higher the. difficulty is

Kingdom support
-ciapital in allied forces will support each other by sending foods every once in a while
-capital send food to its starving cities

(Sorry for bad english i didnt study english that well)
if you wanted to modify some of these you can im not the best at suggesting

**Comment by logicminimal** [comment]
> Worker AI improvements according to the situation
> -If a city is starving the automate system didnt care at all about that,i mean i can just manually change it but its pretty anoying 

this might be in the roadmap due to better ai

> (Also probably add it in the units settings so it can be changed if you didnt want it)
> 
> Wounded affects
> -If a unit is wounded add some affects to it like reduced range,slower fortification
> -slowly take tiny amounts of dmg
> -the affects last until healed 75 percent of hp
> (Ill say put it in higher dificullties to add challenge)

only difference is that wounded units deal less damage in civ 5, i dont think if others will be implemented

> 
> Seasons
> -Add the four seasons which each have their own affects
> -seasons gets more challanging the higher the. difficulty is

dont think if we ever will get this as i dont recall it being implemented, even in civ 6

> 
> Kingdom support
> -ciapital in allied forces will support each other by sending foods every once in a while

not between different allied civilizations but in bnw with internal trade routes you can send stuff to your less developed cities. also friendships dont necessarily mean alliances, what could be counted in as an alliance is mostly just teams mode but you cant change your allies (not implemented yet)


> -capital send food to its starving cities

implemented in bnw with internal trade routes, the game has not implementedeven G&K yet

**Comment by yairm210** [comment]
The first suggestion is a good addition, the rest are out of scope for this project :)

**Comment by logicminimal** [comment]
> The first suggestion is a good addition, the rest are out of scope for this project :)

except, you might want to starve a city on purpose, which there should be an exception for, also we should be able to lock out x amount of population from not working anything (like if there are even 1f tiles the population will be assigned to them while production is more important currently)

**Comment by yairm210** [comment]
The only issue in this list (the first) has been dealt with :)
