### ISSUE TITLE
Help Needed: Ideas for UI for seeing followers in foreign cities

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#4987]
Recently, I've added a UI for viewing how many followers and pressures there are in your own cities. However, in the original game you could also view this for other cities, by hovering your mouse over the majority religion icon on citybuttons. Since 'hovering your mouse' is not a viable action to do in Android apps, this is not a viable way of implementing it into unciv. I have trouble coming up with other ways to do this, however, especially as I also don't want to compromise on the 'open diplomatic overview of civ' when clicking on their city buttons.
Does anyone have an idea for how to implement a UI for this?

**Comment by logicminimal** [comment]
opening their diplomacy page takes 2 clicks, when someone clicks it once a ui showing how much followers every religion has. something like this pop ups either instantly or with an animation like pressing a city for the first time, ascending it, im sure you can make this fancier

![20210825_150843.jpg](https://user-images.githubusercontent.com/56484801/130787899-90b5a18f-9af3-4e2f-9548-f8c397712ac3.jpg)

(i actually didnt mean to add the red line but as an euroka moment it could be used to seperate the majority religion from others, which in this case is judaism (what happens if two religions have same amount of followers)

**Comment by AdityaMH** [comment]
Add button like worker use tile improvement when click someone city and lead to pop-up like get notification from builded wonders.

I think we can set this for tile improment too instead blank blue color.

**Comment by logicminimal** [comment]
on another thought, when you press any city (yes any city, including your own) a small pop up could appear on top of the screen or to the below of it, shoeing city name, population, and religions, i think it would be better if it had a brown background, like a wooden plank, no idea why i think brown would be good for this though

**Comment by ravignir** [comment]
![ed](https://user-images.githubusercontent.com/30041793/130803292-3ea91f4e-6f76-4a45-90db-cc4094e6a15e.png)
I will be damn original.
The only problem i can see with this, the resolution may be too low.

**Comment by AdityaMH** [comment]
Hm, still no idea?

**Comment by xlenstra** [comment]
Closing this as it was added in #5321
