### ISSUE TITLE
Civilizations are incorrectly alphabetized in some languages

### ISSUE THREAD

**Issue by SimonCeder** [yairm210/Unciv#5071]
**Platform**
Linux 64 bit.

**Version**
Git, 0389945ab186774b2ec9ad2f600f22f52cf8f664 (3.16.11 more or less)

**Describe the bug**
The alphabetizer function puts 'ö'  right after 'o', whereas in Swedish (and some others??) 'ö' is the last letter of the alphabet.

**To Reproduce**
1. Set language to Swedish
2. Open new game screen
3. Open the civilization picker

**Expected behavior**
"Österrike" (Austria) should go at the end of the list of civilizations.

**Screenshots**
![Screenshot_2021-09-02_23-16-21](https://user-images.githubusercontent.com/63475501/131918137-bec0f44c-f6e8-4fbf-b484-b6c7ba8f3f8e.png)

**Additional information**
The civilopedia is likewise affected.

**Comment by SomeTroglodyte** [comment]
Just search for `Collator.getInstance()` in the Project, and you'll find all instances. The javadoc for that is:
```
    /**
     * Gets the Collator for the current default locale.
     * The default locale is determined by java.util.Locale.getDefault.
     * @return the Collator for the default locale.(for example, en_US)
     * @see java.util.Locale#getDefault
     */
    public static synchronized Collator getInstance() {
        return getInstance(Locale.getDefault());
    }
```

... so you see, it's not dependent on Unciv's language choice but on the System default. I think I commented that fact in the original PR - blame says #4522 

For the collation to follow Unciv's language choice, we'd need to maintain a list of Java-compatible locales with the language. A nice challenge for a PR, but I didn't think it worthwhile. Also, the collation logic would still be the system's, and could still be "erroneous".

**Comment by SimonCeder** [comment]
We could add a "LANGUAGE_CODE" string to template.properties? Which would then be translated into "sv" in Swedish for instance, there's a list of locales [here](https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html).
Trying `.sortedWith(compareBy(Collator.getInstance(Locale("sv")), { it.name.tr() }))` gives correct sorting for Swedish.
But perhaps there's some wrinkle I'm unaware of?

**Comment by SomeTroglodyte** [comment]
Thanks for helping think this through, I haven't got much brain capacity free these days. 
Since you tested that line I'm confident that's all it takes. There's certainly bazillions of wrinkles in the universe we're not aware of, but that sorting stuff should be that simple. Remaining questions - is instantiation of a non-default locale expensive and should we cache it, and where to maintain that code. 

Your suggestion is one I have thought of before, e.g. for internationalizable key bindings, but that somehow doesn't really sit well. Another json is - well another json, but might be cleaner. 
If *.properties, then yes all upper could help avoid confusion. Place right on top + comment. Yours or "SORT_LOCALE"?
Or - hardcode as an enum, and simply prepare all that might perhaps be part of Unciv in the mid-near future so it doesn't need to be updated often..

**Comment by SimonCeder** [comment]
Currently the sorting is only done on screens away from the world map and only once per screen so performance is not a great issue. I think it's possible to get away without caching but if we did perhaps in `GameSettings.kt` alongside `language`?

**Comment by SomeTroglodyte** [comment]
GameSettings - I would have thought GameInfo as settings is so far "clean" transient-free, but you're right, that's where the knowledge when it outdates lies.

Any other lists urgently needing collation-aware sorting? City screen what is already built currently is sorted by build turn afaik.
