### ISSUE TITLE
Locally running the tests in android studio resets game start options and settings

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5096]
**Platform**
Linux 64bit

**Version**
3.16.12

**Describe the bug**
Running the 'serialization tests' in Android studio resets the options for the game start screen, as well as all settings. While this only applies to coders, it is quite annoying having to reapply your settings every time you locally run the tests.

**Comment by SomeTroglodyte** [comment]
It's not only the test preparation that due to me wanting to preserve the newgame settings now overwrites the settings, but you could also get an overwrite if you prevented the first one - due to the test game fulfilling a tutorial.

Not sure what to do - shelve the tests? Make some switches preventing such saves when context is a unit test? Backup and restore?

**Comment by SomeTroglodyte** [comment]
Why this does _not_ bite me: My desktop config runs against a custom working directory as described in my scratchpad, while for the unit tests you can no longer choose the working directory thanks to the arctic fox update.

**Comment by xlenstra** [comment]
> It's not only the test preparation that due to me wanting to preserve the newgame settings now overwrites the settings, but you could also get an overwrite if you prevented the first one - due to the test game fulfilling a tutorial.
> 
> Not sure what to do - shelve the tests? Make some switches preventing such saves when context is a unit test? Backup and restore?

Isn't it an option to somewhere cache the current settings and restore them after the tests have been completed?
