### ISSUE TITLE
Feature Suggestion: Google Drive & Internal Backups

### ISSUE THREAD

**Issue by touhidurrr** [yairm210/Unciv#5114]
Hi. How about implementing Google Drive Backups for Multiplayer & Normal Game saves. I saw some apps asking for permission of accessing their App Data in Google Play.

Also Games files can also be allowed to be saved in File Storage in two ways:

1. Zipping all the `.txt` files and saving them
2. Asking for a Folder Access for `.txt` files to be saved later

I also want to suggest a new kind of `.json` or `.txt` files for saving game data of Multiplayer Games.

```js
// Suggested multiplayer.json
{
  "Game Id": "Some-Game-Id-here",
  "Game Name": "Some Game Name",
  "data": "The txt data of the game. Might ot might not be implemented"
}
```

```
# Suggested txt
--- Unciv Multiplayer Game Save ---
Id: Some-Game-Id-here
Name: Some Game Name
--- Unciv Multiplayer Game Save ---
The normal txt data of the game
```

**Comment by SomeTroglodyte** [comment]
- This is open source. G Drive is almost as bad as OneDrive. And since it probably comes with a document provider see item 3.
- We have no files with a `.txt`extension
- Doing single save '''backups''' using the custom save location feature is IMHO enough - finish your games before starting another one or discard the old ones. Settings are restored quickly by hand.

**Comment by xlenstra** [comment]
Using Google Drive als only works on android phones, and unciv is also distributed via itch.io, desktop downloads, etc. where google drive wouldn't be integrated

**Comment by yairm210** [comment]
Not something we're going to implement.
If your have a working concept for this, PR it :)
