### ISSUE TITLE
AI Logic Suggestions

### ISSUE THREAD

**Issue by AdityaMH** [yairm210/Unciv#5175]
There have been a lot of various suggestion from g̶i̶t̶h̶u̶b̶ discord to extend the gameplay in various ways.
Usually they're from diplomacy logic, automate worker logic, and have very little effect on the general playerbase, and they're kind of clogging up the issues.

So this is an issue to consolidate all those suggestion, as comments to this issue.

*need to get pinned

**Comment by AdityaMH** [comment]
📌 Much Weaker civ get bullied by Much Stronger civ. But most warmonger will get bullied by coalition.
Make game more harder with low thinking instead cheating AI.

**Comment by kingkarna1** [comment]
a builder priority meter with 4 prongs: strategic(focus on strategic resources), bonus(focus on bonus resources), luxury(focus on luxury resources), roads(focus on roads)

**Comment by kingkarna1** [comment]
and automate-like button on military units so they can fight by themselves

**Comment by AdityaMH** [comment]
> a builder priority meter with 4 prongs: strategic(focus on strategic resources), bonus(focus on bonus resources), luxury(focus on luxury resources), roads(focus on roads)

Uh.. it's a feature, not AI logic thinking.

**Comment by kingkarna1** [comment]
> > a builder priority meter with 4 prongs: strategic(focus on strategic resources), bonus(focus on bonus resources), luxury(focus on luxury resources), roads(focus on roads)
> 
> Uh.. it's a feature, not AI logic thinking.

i mean, youll have to change the way the ai thinks to do this though

**Comment by kingkarna1** [comment]
also, make it so the ai have troop build up on enemy borders, and they put units on roads to guard them and they also intentionally flank when possible

**Comment by dnddnbdodjd** [comment]
Make AI Buy strategic resources

**Comment by dnddnbdodjd** [comment]
Let AI Buy strategic resources

**Comment by SuperCiuper** [comment]
When in exploration mode unit should priorotize collecting ancient ruins. Now it requires checkig on scouts every 2/3 turns to make sure you haven't lost bonus tech or other stuff

**Comment by AdityaMH** [comment]
AI never denouncing weakling civ. Make them denouncing first before war.

**Comment by will-ca** [comment]
* AI should randomly shuffle units when it has no other move. I've had routes and improvement tiles blocked off by AI units just sitting there.

* AI should move armies to border before declaring war.

* I'm not sure how the current model works. But IMO having a "threat map" and a "value map" would probably bring improvements:
* * Assign every tile a threat rating based on proximity to foreign borders, proximity to foreign units, foreign relationship status, etc.
* * Assign every tile a value rating based on proximity to own cities, proxmity to settlers and planned settlements, tile yields and resources, etc.
* * AI should then try to always make sure `(MilitaryPresence / TileValue) > TileThreat`. This would take care of border defence, war, escorting, troop placement, etc. without requiring hardcoded logic for all cases.

* Stellaris's diplomacy system is a good example for emergent coalition-building, I think. Opinion modifiers built up over the course of the game naturally align players with common interests.

* AI should be willing to declare war on more powerful civs sometimes. It does this in Civ. 

* "Years of peace" positive opinion modifier is overpowered, without anything negative to balance it. Having a sizable military will basically guarantee it never declares war on you after a couple turns of peace. This is boring.

* The problem is that all the negative modifiers fade over time, while the "Years of peace" modifier increases over time, so peace is guaranteed as long as you have a sizable military. Either it should be weakened, or there should be more negative modifiers that can cancel it out. 

* Possible persistent negative modifiers: "Covet lands you own", "Border friction", "Wary of military buildup", "Social policy/cultural differences", "Friends with their enemies", etc. Instead of being a one-time modifier that fades, these should last for as long as their condition remains true.

* I suggest: Fuzz chances to declare war with random rolls. -1 opinion means +1% chance to declare war every X turns, -10 opinion means +10% chance to declare war every X turns, etc. Make negative opinions additive but positive opinions multiplicative, or use some logarithmic or reciprocal function, so the chance is never 0% or 100%. Or have presence of negative opinion modifiers act as hard minimum on war declaration chance: Even with +100 opinion, if the AI has a grievance with something you've done, then there should be a minimum chance to declare war or denouonce. Stuff like AI personality, distance, strategic value, and relative power would then of course be included as factors or addends in the random roll threshold.

**Comment by K3XRad** [comment]
I notice that AI almost don't use Stealth Bombers or don't use them at all. AI should produce them, which should give serious advantage in wars. It could be more interesting to war with bots if they will use Stealth Bombers more actively.

**Comment by will-ca** [comment]
Red arrow from Vancouver. Should the AI be nuking itself to take out just two enemy units?

![image](https://user-images.githubusercontent.com/37680486/147401921-dab9b0f8-1d39-498c-8b37-5fa710d5e27e.png)

![image](https://user-images.githubusercontent.com/37680486/147401934-3ad9d2dd-762c-4da2-8861-854d8f414997.png)

**Comment by AdityaMH** [comment]
Let's useless Great Prophet AI to spend to build Holy Site or Gift to CS

**Comment by SeventhM** [comment]
I'm closing as Solved for now. If it should be reopened, then please comment. However, issue is so old that it may be better to open as a new issue
