### ISSUE TITLE
RFC: "Blog post" about translations, uniques, and modding

### ISSUE THREAD

**Issue by yairm210** [yairm210/Unciv#5290]
https://github.com/yairm210/Unciv/wiki/Translations,-mods,-and-modding-freedom-in-Open-Source

I'm planning on posting this on Medium as a standalone post, so I'd like to hear your thoughts on style, content, readability, and assumptions I may be making about the target audience :)

**Comment by yairm210** [comment]
https://medium.com/@yairm210/translations-and-moddability-in-open-source-d7cf5e53e40c

Edited version for the platform (plus corrections and simplicity)

**Comment by xlenstra** [comment]
Few things I found while reading:
- In "The Translation Process -- History and revisions" there appears to be an unfinished sentence
- The problem that parameters interfere with normal grammatical flow in languages like German and Greek that have grammatical noun cases or noun genders isn't mentioned, though this might be intentional.
- In "Translation placeholders" you mention "PR". Can we assume enough familiarity of the reader with GitHub to use this?

Other than that, everything looked generally fine in the quick read I had the time to do

**Comment by yairm210** [comment]
Points 1 and 2 I'll check, thanks!
The third - yes, intended audience is developers of open source :)

**Comment by SomeTroglodyte** [comment]
Well, as I refuse to play the grimace-showcase (aka farcebock the destroyer of secure protocols) game, or any of the other medium sign-in demands, I can only comment on the wiki version.
`This format lends itself both the easier translation (it's immediately obvious what needs to be translated) and actual collaboration.` - is that meant with a `to` in place of `the`?
`Separate to different files for simpler management.` - I had to read that twice to get it. "We separated the stuff ... and got..."?
`Rather than being 'build in'` -> "built-in" or "built in"
`This does two things` ... the "B" is not clearly delimited. If all that stays inline, maybe "; and B"? .. Period missing at the end of that paragraph.

As you can see, everything very minor, so the overall verdict is 'very good'. Reading mostly flows smoothly, the meaning comes across. Some places I didn't really find a better wording, so I skipped a comment.

**Comment by yairm210** [comment]
Oof, the return path is harsh. It was easier just to release it, so now it shouldn't require any logins.
https://medium.com/@yairm210/translations-and-moddability-in-open-source-d7cf5e53e40c

**Comment by SomeTroglodyte** [comment]
:laughing:  "Create an account to clap for this story"
