### ISSUE TITLE
release jars in itch io as well

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#5374]

**Comment by xlenstra** [comment]
As far as I'm aware, the .jar is contained in all the downloadable files on itch.io already

**Comment by logicminimal** [comment]
> As far as I'm aware, the .jar is contained in all the downloadable files on itch.io already

thats great but im talking about a standalone jar release

**Comment by yairm210** [comment]
That won't do. People download things from itch.io expecting it will "just work". You can't put something there that is both dependent on having something preinstalled, AND knowing how to actuvate it, from the command line That's not user friendly. 
For Github that's fine, since the assumption is that if you're downloading it from Github, you're in the "I know what I'm doing" group. But not for itch.io.

**Comment by logicminimal** [comment]
> That won't do. People download things from itch.io expecting it will "just work". You can't put something there that is both dependent on having something preinstalled, AND knowing how to actuvate it, from the command line That's not user friendly.
> For Github that's fine, since the assumption is that if you're downloading it from Github, you're in the "I know what I'm doing" group. But not for itch.io.

normally it is fine but downloading 65 megabytes of data with 40 mbs of them being java stuff for an update of 100 kilobytes is not great imo
