### ISSUE TITLE
Unable to download multiplayer game on v3.18.{0,1, 2}

### ISSUE THREAD

**Issue by thepianoboy** [yairm210/Unciv#5685]
My play group has been having issues downloading multiplayer saves ever since the 3.18.1 update landed. 

It seems that if a player is on version 3.18.1 and the next player is on 3.18.0, the next player will get an "Unable to download game ..." error on refresh in the multiplayer menu when it becomes their turn.

We've had mixed results from updating the second player to 3.18.1, but that's not an option for everyone in the group and it hasn't always worked.

I tried loading the Autosave for that particular game as a single player game and that didn't work either. 

We've been seeing similar issues between folks who are on version 3.18.1 passing the turn to someone on 3.17.4 or or 3.18.2. It seems almost like 3.18.1 corrupts cloud (Dropbox) saves in some way, but even then I've not had any problems when both players are on that version.

I don't have enough tech savvy participants to check each available combination of recent release versions, but it does seem like 3.18.1 is the culprit. 

Please let me know if there's anything else I can do to help diagnose and fix this issue.

**Comment by xlenstra** [comment]
This is to some parts intentional behaviour, but should only happen in modded games. In 3.18.1 support was added for two different base rulesets: Vanilla & G&K. To make this happen, some changes were made to how the these base rulesets and modded base rulesets (e.g. deciv, rekmod) were stored of the games. Games saved before 3.18.1 still use the old format, which can not load games with a modded base ruleset saved in 3.18.1 or later. 3.18.1 has conversion code to convert pre-3.18.1 saves to the new format, but this is not reversible in 3.18.0, as that version has no conversion code.

The only advice I can give is for your friends to update their games, which either requires waiting till the version comes out for their device, or downloading the APK (backup your files in that case).



I vote to close this as wont-fix.

**Comment by thepianoboy** [comment]
Ahh, that tracks, I completely forgot we were using a modded ruleset.

That said, there's still the issue when going from 3.18.1 to 3.18.2. Is this also intentional behavior?

**Comment by xlenstra** [comment]
A save file opened in 3.18.1 should be openable in 3.18.2, if not: please provide the save and I'll see if I can reproduce and fix the problem

**Comment by yairm210** [comment]
Is this still a problem?

**Comment by thepianoboy** [comment]
I was trying to investigate the issue on my own and managed to truncate my only copy of the broken save. I'm not able to reproduce it by creating another version, so unless somebody else reports something similar, the issue is probably moot.
