### ISSUE TITLE
Telegraph tech is missing icon

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#5715]
See title. The Telegraph tech in vanilla Civ V is missing its pretty picture.

**Comment by SomeTroglodyte** [comment]
Likely a minor oversight - it's a Vanilla-only tech, not present in G&K...
Possible candidate: https://thenounproject.com/icon/telegraph-22058/ ?
However, thenounproject has drastically changed since I last visited, apart from changed search result URL formatting, the actual license is no longer clearly shown. Are they still trustworthy???

**Comment by SpacedOutChicken** [comment]
It appears to be the usual Attribution license.
