### ISSUE TITLE
Game crashes whenever switching soundtracks

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#5725]
**Platform**
Windows 10, 64 Bits

**Version**
3.18.15

**Describe the bug**
There's a chance that the game will crash whenever switching soundtracks/in-game music, within the options. Other than that, there's nothing much to report.

**Expected behavior**
Game crashes.

**Comment by SomeTroglodyte** [comment]
Current: `const val appVersion = "3.18.7"` - You got 3.18.15 via time machine?
Jokes aside - console log please? All Gdx.Music calls are try/catch wrapped, but some of the OpenAL failures were very hard to catch back when I wrote the MusicController. I thought I ended up with something that at worst does a long pause then moves on to another track...

**Comment by Newexae** [comment]
I have a similar bug with my Rpi 4 where the game crash itself. According to the log, it is due to the music.

Exception playing music: Unable to allocate audio buffers. AL Error: 40963
Exception playing music: Error reading audio data.
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error reading audio data.
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:90)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:253)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
	at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:61)
Caused by: javazoom.jl.decoder.BitstreamException: Bitstream errorcode 102
	at javazoom.jl.decoder.Bitstream.newBitstreamException(Bitstream.java:418)
	at javazoom.jl.decoder.Bitstream.readFrame(Bitstream.java:329)
	at com.badlogic.gdx.backends.lwjgl3.audio.Mp3$Music.read(Mp3.java:67)
	... 6 more

**Comment by HaneulCheong** [comment]
The issue still persists in 3.19.13. Here's the stack trace:
```
Exception in thread "main" java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.fill(OpenALMusic.java:269)
        at com.badlogic.gdx.backends.lwjgl3.audio.OpenALMusic.update(OpenALMusic.java:237)
        at com.badlogic.gdx.backends.lwjgl3.audio.OpenALLwjgl3Audio.update(OpenALLwjgl3Audio.java:253)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:132)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
        at com.unciv.app.desktop.DesktopLauncher.main(DesktopLauncher.kt:62)
```

**Comment by SomeTroglodyte** [comment]
I get them all the time, too, unless I test with music off. There's variations, but all have in common I/O from OpenALMusic.fill and the next Unciv code in the stack trace is DesktopLauncher - which means they can't be caught meaningfully - which means the library is at fault. I'm pretty much convinced Lwjgl2 had the same problems _but_ allowed the I/O errors to be caught by the try/catch in MusicController.tryPlay - see comments there. I vaguely remember investing quite some time back then and that I grudgingly accepted the music sometimes abruptly changing to a new track for no apparent reason...

Note this is happening with music files that behave without any errors in smplayer or audacity.

**Comment by HaneulCheong** [comment]
Shouldn't this be elevated to [LWJGL](https://github.com/LWJGL/lwjgl3) in that case?

**Comment by HaneulCheong** [comment]
Hmm. Nothing much going on regarding music (https://github.com/LWJGL/lwjgl3/issues?q=is%3Aissue+music). This should be reported if we all can agree this is a library issue. It seems this has been persisting for a few months and at the very least we can attempt to track down the culprit.

**Comment by SomeTroglodyte** [comment]
I have the vague idea to try and replace the whole thing so it's not fed by that permanent loop in Gdx (Lwjgl3Application.loop), just so exceptions can be caught, but otherwise as similar as possible. If that then is reliable, then maybe elevate, 'cuz that experiment will show whether to bother lwjgl or gdx, and serve as argument. As it is, we don't really have a thorough investigation _or_ a reliable repro, and don't even know the degree to which it's platform dependent, or dependent on the codec needed. Wanna collect statistics? I also have in mind but not yet done: looking at Mindustry or Shattered to see how they avoid the issue.

**Comment by HaneulCheong** [comment]
Got it. So no background music for now :(

Perhaps in the meantime I can do some tests using different audio files and formats. I have a feeling this issue has nothing to do with the audio files themselves though.

**Comment by SomeTroglodyte** [comment]
> some test

Yes please :smile_cat:

> nothing to do with the audio files themselves

Confirmation would still be good. Music supports mp3, ogg and wav - but MusicController line 30 reads `private val fileExtensions = listOf("mp3", "ogg")   // flac, opus, m4a... blocked by Gdx, 'wav' we don't want` - so to test simple pcm files you'd have to run from source and modify that line.

**Comment by SomeTroglodyte** [comment]
@yairm210  Say, more data? Any Android users affected? Windows/Linux balance? Is it possible you have a collection of reports you could filter on that `lwjgl3.audio.OpenALMusic.fill` portion of the stack which is pretty much selective for this problem, though the actual top exceptions seen can be at least 11 different ones (yes I have collected 11 distinct crash signatures so far).

My take (some of this I've said before) at the moment is:
- Core of the problem is that the Gdx application loop is running Music.update without exception handling, and therefore some exceptions due to codec/buffering/io/whatever will crash right past all our measures. I have code here that seems to actually _prove_ this description.
- That was not the case with the Lwjgl2 backend (which was the backend when I developed MusicController) - the triggering exceptions were maybe the same but could all be caught by a try block around the Music.play method call.
- The diversity of the exceptions seems to hint at thread safety problems in the underlying libraries. The above-mentioned branch catches the un-catchable, and I can see one and the same mp3 crashing then playing just fine seconds later, in the same session. The messages basically say corrupted data, so why would that same source play fine later? Precise statistics are hard to do, but I _do_ get the vague impression reducing the isPlaying and setVolume calls (by eliminating the Timer, eliminating the fade feature and using a completion handler instead) reduces the crash frequency but does _not_ eliminate them.
- Ogg seems just a little less prone than mp3.
- Looking at other games helped little. Shattered has its Music code [here](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/noosa/audio/Music.java), simple and nothing special. Mindustry is in the Gdx showcase, but it's not Gdx at all, its 'Arc' framework seems to work completely different at least for audio (uses [Soloud](http://sol.gfxile.net/soloud/) through JNI). Lastly, Riiablo source is not immediately transparent, but it does call Music.play with no obvious exception handling - maybe it crashes same as us? Maybe its resources are uncompressed wav (the only format the Gdx devs decided to implement themselves - ogg uses com.jcraft.jogg, mp3 is javazoom.jl.decoder)? Can't tell at a glance. Found no other open source Gdx games.
