### ISSUE TITLE
Foreign Land strength bonus not showing up

### ISSUE THREAD

**Issue by SpacedOutChicken** [yairm210/Unciv#5801]
The combat bonus for Foreign Land tiles is not showing up for units that are definitely in foreign land. Whether it's a single unit bonus, like France's Foreign Legion, or a civ-wide bonus, like DeCiv Redux's Blackwarden, no strength increase is coming up. 
[NoForeignBonus.zip](https://github.com/yairm210/Unciv/files/7724287/NoForeignBonus.zip)

**Comment by yairm210** [comment]
Okay, so - the problem *isn't* that the combat bonus isn't applied, or shown to the user.
It is, it's just called "Unit ability" without regard to the reason.
This is due to the change from specific uniques to generic uniques, which is definitely a good change, but it does mean that the user-facing is lost in the process.
I'll think of how we can fix this.

**Comment by xlenstra** [comment]
There was a bug around that time that did prevent 'in [foreign land] tiles' and 'in [friendly land] tiles' conditionals from working; I fixed this without seeing this issue, so it is possible that this issue is actually already fixed
