### ISSUE TITLE
Civ borders don't show

### ISSUE THREAD

**Issue by xlenstra** [yairm210/Unciv#5884]
**Platform**
Desktop, Linux 64-bit

**Version**
f06242ebe11c3d6c679ef7d2424c2fb01b780d51

**Describe the bug**
No borders show up, not of my nation and not of any other nation.
![image](https://user-images.githubusercontent.com/71121390/147822008-67c0a974-4eeb-469f-b4fd-a07b741bc5ee.png)

In other tilesets, the same problem persists:
![image](https://user-images.githubusercontent.com/71121390/147822085-508edeae-e88a-4391-9460-47b96e776c25.png)

I have tried removing all .atlas and .png files and regenerating those, but that did not solve the problem.

Enabling bubbly borders mod does solve the problem:
![image](https://user-images.githubusercontent.com/71121390/147822205-8a430127-858d-4c97-8db7-fe38f773c888.png)

Though only in the fanatasyhex tileset, as other tilesets still lack borders, even with the mod as a permanent audio-visual mod enabled:

![image](https://user-images.githubusercontent.com/71121390/147822278-9b9b57f8-6eac-43c0-8bc8-b0d457e66eb4.png)

**Comment by will-ca** [comment]
Try regenerating `game.atlas`. Deleting it and running the game should do it.

I exclude it from my commits to keep the history clean, but that means it never gets updated in a fresh repo since `git` resets `mtime`.

Ooh. I'm gonna accept that Collaborator offer and push the commit myself real quick.

**Comment by will-ca** [comment]
So, I've immediately learned a lesson about getting too excited and skipping review even if I think something looks very simple. Also about checking all tilesets; I made the same mistake with the arrows 😳.

Default tileset is simple enough. I neglected to give it border images in #5868, and I couldn't make it use FantasyHex as a fallback in #5852 due to its overlay images being disabled in TileGroup.kt when it has situation-specific images, so it's just missing images. #5886 should fix it.

![image](https://user-images.githubusercontent.com/37680486/147827366-2cd9cce3-5261-4c65-9a64-4007cecf5a53.png)

FantasyHex already works for me, however.

![image](https://user-images.githubusercontent.com/37680486/147827400-fd6fe483-613b-479f-9c5a-e0f874efbf63.png)


Side note about the mods: They should provide borders in their own tilesets, in FantasyHex, and in Pix5 and 5Hex— They won't do anything in Default because they override FantasyHex tiles, which can't affect Default as mentioned above. Do they not work in Pix5 and 5Hex?

Poor yairm210, probably waking up and seeing his new "hire" immediately making a hash of things…

**Comment by will-ca** [comment]
@xlenstra If FantasyHex is still broken for you, can you check if `/android/Images/TileSets/FantasyHex/Borders` exists and has the following files?

https://github.com/yairm210/Unciv/tree/master/android/Images/TileSets/FantasyHex/Borders

Also, sorry about, like, this issue existing. This is the second oversight from one of my changes that you've fixed/caught in the last 24 hours. I will test more thoroughly in the future.

**Comment by xlenstra** [comment]
> @xlenstra If FantasyHex is still broken for you, can you check if `/android/Images/TileSets/FantasyHex/Borders` exists and has the following files?
> 
> https://github.com/yairm210/Unciv/tree/master/android/Images/TileSets/FantasyHex/Borders
> 
> Also CTRL+F should find those paths in `game.atlas`.

I'm currently not home, but I'll look into it tomorrow

> Also, sorry about, like, this issue existing. This is the second oversight from one of my changes that you've fixed/caught in the last 24 hours. I will test more thoroughly in the future.

No worries, I've done similar things on multiple occasions 🙃. But as we're all part of the team that is what we're here for :)

**Comment by AdityaMH** [comment]
> Side note about the mods: They should provide borders in their own tilesets, in FantasyHex, and in Pix5 and 5Hex— They won't do anything in Default because they override FantasyHex tiles, which can't affect Default as mentioned above.

But i'm dont want to set border my own, so let's player freely choose default border, or bubble border

**Comment by will-ca** [comment]
@AdityaMH Sorry, I was specifically referring to the "Bubbly Borders", "Greasy Borders", etc. mods. "Should" as in "intended behaviour in these specific mods", not "should" as in "requirement for all mods".

Other tilesets like Pix5 are fine even if you don't provide borders. In that case, the player can freely choose by downloading a mod that does override borders, like the Bubbly Borders Example. So it already works kinda like you describe.

**Comment by xlenstra** [comment]
> @xlenstra If FantasyHex is still broken for you, can you check if `/android/Images/TileSets/FantasyHex/Borders` exists and has the following files?
> 
> https://github.com/yairm210/Unciv/tree/master/android/Images/TileSets/FantasyHex/Borders
> 
> Also CTRL+F should find those paths in `game.atlas`.
> 
> Also, sorry about, like, this issue existing. This is the second oversight from one of my changes that you've fixed/caught in the last 24 hours. I will test more thoroughly in the future.

I've just tested it, and fantasy-hex does seem to show borders this time around. I don't know what changed, but it seems like #5886 should fully close this issue now
