### ISSUE TITLE
Units gifted to City-States disappear on next turn.

### ISSUE THREAD

**Issue by will-ca** [yairm210/Unciv#6041]
**Platform**
Desktop

**Version**
3.19.1

**Describe the bug**

Entire armies and navies gifted to City-States will sometimes just instantly disappear without a trace.

**To Reproduce**
1. Load attached save.
2. Press next turn, then look at M'Banza-Kongo. All those ships disappear.

Arrows show they probably weren't all killed (and the enemy doesn't have enough units in the region to kill them all anyway).

Compare: Manila, Singapore, which have both hanged on to large navies gifted to them many turns ago.

[The Ottomans -  415.zip](https://github.com/yairm210/Unciv/files/7927606/The.Ottomans.-.415.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/37680486/150834857-8d1e4949-df19-4f69-b010-25ef4388f8fb.png)

![image](https://user-images.githubusercontent.com/37680486/150835581-50486eba-b554-4ad3-9e35-9225df570f4e.png)

**Additional context**

If it's a unit maintenance thing, then maybe city states could have their gold gifts added to their stats?

Don't know about original Civ V behaviour…

Also ran into this on other maps before. This is just the clearest.

**Comment by alexban011** [comment]
I know this issue is ~ancient~ but I tried to load this save and I got this so I'll just leave this here (this doesn't seem like a version mismatch issue so yeah)

![image](https://user-images.githubusercontent.com/21990802/207982045-240fa08c-e9c8-4de5-b25f-22d9662e5a61.png)

**Comment by CrispyXYZ** [comment]
This is not a bug.

I added a spectator player to view the stats of M'Banza-Kongo by editing the save file. Here are two screenshots before and after end turn respectively.

before:

![before](https://user-images.githubusercontent.com/64761703/215390076-9b7aa600-9607-41d1-9d65-24a22b435002.png)

after:

![after](https://user-images.githubusercontent.com/64761703/215390115-71dca9a7-188e-4d84-9a00-76ce840aacd5.png)

Obviously, golds increased by over 300 in 1 turn.
That means AI disbanded all the units gifted due to low gold yield, although it is in a war.
