### ISSUE TITLE
When you pull down the window to height 0, the cpu usage goes up to 100% and the gameoptions.json gets corrupted

### ISSUE THREAD

**Issue by logicminimal** [yairm210/Unciv#6088]
to replicate, just take the unciv window, vertically rescale it into a smaller scale, and when it reaches 0 (no portion of the windows shows) the cpu usage jumps to 100% and when you open the game after it will say that gameoptions.json got corrupted and is wont be fixed until you delete the gameoptions.json after so that everything starts to work fine again

**Comment by yairm210** [comment]
This honestly sounds like a 'why the hell are you doing this' problem

**Comment by logicminimal** [comment]
> This honestly sounds like a 'why the hell are you doing this' problem

yeah tbf but it hardlocks the game until you delete the gameoptions.json

**Comment by SomeTroglodyte** [comment]
Shows the raison-d'être of the issue template - does NOT repro on Mint 20.3. Window reduced to just a pixel-wide title bar just sits there, just plays music and when just dragged to a useable size again it's just fine.

But heck, since logicminimal is asking unciv to make us foolproof, let's prove the fool right. It's only left. Or just it was? :confused:
