### ISSUE TITLE
Faith Building Summary

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6145]
Currently it can be difficult to remember what the different Faith buildings do when picking your Follower Belief.

Would be handy to include their production stats so you don't have to check in the Civilopedia

From Discord:
![image](https://user-images.githubusercontent.com/44038014/153543002-ff132f99-daad-4854-a600-2307078323b6.png)

**Comment by itanasi** [comment]
Looking at the code this might be harder than anticipated since the string is using a standardized Unique already. "May buy [] buildings with [] []"

**Comment by xlenstra** [comment]
My first idea would be to also show the effects of each belief at the bottom of the screen, maybe even instead of showing it on the buttons themselves. Then we can use links to the civilopedia, similar to how to tech tree might do it, for people to to find out what stats buildings provide. Still requires closing the civilopedia and reopening the religion founding screen and also loses previously selected beliefs/religion icon/religion name, but should be relatively easy to implement
