### ISSUE TITLE
Font Anti-Aliasing

### ISSUE THREAD

**Issue by ThebestkillerTBK** [yairm210/Unciv#6279]
The font becomes sharp when resolution is high

**Comment by ArchDuque-Pancake** [comment]
Yeah, and sometimes some letters can be seen

**Comment by SomeTroglodyte** [comment]
Old wish, though our options are limited.

I did [experiment](https://github.com/SomeTroglodyte/Unciv/tree/Civilopedia-MSDF-font) about a year ago with [MSDFA](https://duckduckgo.com/?q=MSDFA+fonts) fonts, and the sharpness was better, though not much. I gave up on it for two reasons: Searched days in vain for the cause of geometry errors (dancing baseline), and the need to once again prepare all needed glyphs in font files instead of pulling them from the OS... Don't know where the screenshots went.

**Comment by yairm210** [comment]
Dropping sure to lack of interest and options
