### ISSUE TITLE
Further Zoom

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6294]
Seems a very popular request to enable further zoom out in both game and Map editor.

Ideally after a certain point unit icons can not be rendered to prevent clutter.

Quick messing with `ZoomableScrollPane` zoom limits doesn't seem to work. Lowering limit lower than 0.5 causes the world screen to also shrink
![image](https://user-images.githubusercontent.com/44038014/156974566-e94d0112-a2e1-4ebe-9c4e-4a47a29fcbf3.png)

**Comment by SomeTroglodyte** [comment]
Tried that loooong ago and gave up

**Comment by itanasi** [comment]
So the super dumb solution is in `WorldMapHolder` just change
`setSize(worldScreen.stage.width * 2, worldScreen.stage.height * 2)`
to
`setSize(worldScreen.stage.width * 4, worldScreen.stage.height * 4)`
and then relax the min `zoomScale` in `ZoomableScrollPane` from 0.5 to 0.25. That lets you basically see a Huge map all in the screen. Not sure about the downsides since you'll have so much of the WorldMapHolder basically holding tiles outside the viewable section.

Trying to transition between the `setSize` settings though is a bit trickier to align and get smooth zooming. I recall seeing how to handle this in the past since it's a common issue but don't know it off-hand.

**Comment by yairm210** [comment]
The source of the difficulty is in the only way I found to have both zoom and pan center on the center of the screen.
In essence, there's one big Scroll, which contains the entire map.
When you zoom, you don't actually change the size *of the objects of the map*, since that would make the whole screen shift since the area you're looking at would no longer contain the tiles youu were seeing before.
Instead, we zoom *the scroll itself*.
The downsize is that if the scroll at max zoom-out is the size of the screen, then as you zoom *in* there will be more and more parts of the Scroll that are left outsiide the bounds of the screen, or in other words - there will be parts of the Scroll that will be _entirely inaccessible_ at a great zoom-in.
The way to mitigate this problem is to add padding at the sides of the scroll, so it doesn't only contain the world, it also includes a lot of nothing at the edges.

I lookex for a way to make a better "centered zoom and pan" container and could not find one.

**Comment by itanasi** [comment]
Commenting here to make sure I am keeping my head straight.

ScrollPane is what is zoomed. I haven't figured out where the extra padding is.
ScrollPane sits within WorldScreen.stage, which is also the size of the window/game.
The Actor in ScrollPane is the TileGroup.

setSize() sizes the ScrollPane. Larger we set the size, the lower maxX is. maxX = actor.width - width. maxX is the amount of X scrolling needed to scroll and see all of the Actor.

Need to derive based on zoom, WorldScreen.stage sizes, and scrollX/Y where on the Actor the screen is viewing (centered). Alternatively, recode so that the Actor is the one being zoomed. I have seen some talk about using orthographic camera, but haven't looked into it enough
