### ISSUE TITLE
Access to save files/folders.

### ISSUE THREAD

**Issue by laythstag** [yairm210/UnCiv#631]
I would be great to be able to access the save location (I'm on android) so I can share the save file with my brother to play an asynchronous multiplayer game.

**Comment by yairm210** [comment]
Hm
This is actually a Android internals question, since I save the file in the app's 'internal storage' which is not accessible from the outside
According to 
https://developer.android.com/training/data-storage/files.html#ExternalStoragePermissions
This might even be possible without extra permissions.

But technically, how we you going to do this? Exchange files? Isn't transferring the saved file as text easier, because you can send it via email?

**Comment by laythstag** [comment]
For example, I have Stardew Valley for android and PC. The save file is readily accessible. So I use Resilio Sync to synchronize the save folder on PC with the save folder on android. Whichever save file is most recent is copied to the synchronized folder. I figured I would do a similar thing with Unciv. I would sync my save folder with my brother's. Once I finish my turn and save, Resilio Sync would copy the files to his phone and then he would play when it is convenient with him.

Maybe email would be more convenient. Maybe some series of numbers that tells the game where to continue from. I don't know about developing for android. So if it is not possible at the moment, no big deal.

**Comment by yairm210** [comment]
Oh, cool!
It's definitely possible, is just that I've never done it before so I'm learning :)

**Comment by yairm210** [comment]
Now that we have multiplayer, this is no longer necessary =)
