### ISSUE TITLE
Jungle and forest are resistent and destroyable by nukes at the same time

### ISSUE THREAD

**Issue by jahodovykolac** [yairm210/Unciv#6347]
**Platform**
Android 10

**Version**
Google Play, 3.19.16

**Describe the bug**
Jungle and forest have uniques "Can be destroyed by nukes" and "Resistant to nukes" at the same time

**Expected behavior**
They're resistant or destroyable

**Screenshots**
![Screenshot_20220313-130550_UnCiv](https://user-images.githubusercontent.com/79529669/158058769-eb5fc159-0f2a-40c1-b133-132e14cbed28.jpg)
![Screenshot_20220313-130544_UnCiv](https://user-images.githubusercontent.com/79529669/158058772-b2a2a699-8015-4d7e-9795-154d61ea6591.jpg)

**Additional context**
It looks pretty random which one wins.

**Comment by xlenstra** [comment]
Resistant means they are less likely to be destroyed by nukes, but it is not impossible. The probability is 25% instead of the 50% it normally has.

Though now that I look at it again, it's probably better to combine these uniques into `[25/50]% chance to be destroyed by nukes`, which is both clearer for modders and for users

**Comment by jahodovykolac** [comment]
Oh, so that's how it works.
>  [25/50]% chance to be destroyed by nukes

Definitely clearer
