### ISSUE TITLE
Improvements to online multiplayer system

### ISSUE THREAD

**Issue by GGGuenni** [yairm210/Unciv#6360]
Ideas to improve the multiplayer. Some things were already planned and pursued in #9497 

- [ ] Resign at any time
- [ ] Multiplayer lobbies
- [ ] Public/Private lobbies with a list for public lobbies to easily join games 
- [ ] Kick players from games
- [ ] invite links
- [ ] Turn notifications per game
- [ ] Option to allow players to join already running games (Take over AI)
- [ ] Move multiplayer game related settings (kick, invite, resign, etc.) to WorldScreenMenuPopup (right side?)
- [ ] Usernames to hide UUIDs
- [x] #8482
- [ ] disable charts for non spectator players until the game ends.

2. Multiplayer lobbies: A lobby before the game starts, where everyone can choose their Civ themselves and only the leader can change game related settings 
3. Public lobbies + list: Is this worth the implementation effort? Would this even be used? Maybe ask in a Poll if people would use this
4. Kick players: Should it be a democratic vote or leader decides? Maybe Poll this

**Comment by ravignir** [comment]
Imo, the most important thing is to implement some anti-cheating features.

**Comment by GGGuenni** [comment]
> Imo, the most important thing is to implement some anti-cheating features.

Sadly not possible as far as I can tell. Players will always have the ability to modify the game files or even create a cheating version of unciv on their own repo. There is not much we can do about that.
But that's one of the reasons I don't know if public lobbies would even be used.

**Comment by xlenstra** [comment]
I don't think we have to make it completely fool-proof, but making it more difficult might already be enough to stop most ways of cheating. Currently, in order to start a game you need to send the host your userID, which the host can then later use at any moment to log into the game and mess up your empire.
One way to prevent this, is by not sharing userID's, but by sharing usernames (as you're already planning) and not making these one-to-one translatable to userID's. For example, adding a file in the dropbox saving usernames, hash-encrypted passwords and password-encrypted userID's. This will also allow users to easily sync multiplayer games across different devices; simply logging in with the same account on a different device automatically gives access to the userID, no copy+pasting between different devices required.
We could then also save the username, password & userId in `gameSettings.json`, so we can automatically try logging in again whenever the multiplayer tab is opened.

This would, of course, still leave open the possibility for people to clone the repo and create a version where all passwords are accepted, but the only way out of that is to run all authentication server-side, which is in the current server setup impossible.

**Comment by GGGuenni** [comment]
> One way to prevent this, is by not sharing userID's, but by sharing usernames 

My current plan is to not share anything directly with the game creator but to join a game through a lobby yourself. The only thing that is displayed in-game to everyone in the lobby is currently the first 8 characters of the UUID as I do not have user names implemented yet. Ids can still always be read from the game file itself though

Login system through dropbox sounds kinda crazy but maybe worth a try if it's needed

Looks like the number one priority for me should be finding a way to handle the rate limit fiesta that is going on.
Don't know what the Dropbox tos say about it but as the rate limit is enforced per User we could create multiple accounts that all access the same dropbox which can then in game be selected as different access points

**Comment by SomeTroglodyte** [comment]
Shouldn't `#`1 prio be to finish the backing storage abstraction with at least one working alternate provider, be it local UNC paths or WebDAV?

**Comment by touhidurrr** [comment]
> Multiplayer lobbies: A lobby before the game starts, where everyone can choose their Civ themselves and only the leader can change game related settings

I will say that try not to create more type of files. Ditch `Multiplayer Lobbies` data to the `_preview` file and when the game start create the game file.

**Comment by touhidurrr** [comment]
> Imo, the most important thing is to implement some anti-cheating features.

I was thought of implementing some on UncivServer.xyz as such that players game files won't have data about other civs. So, that they can't see others conditions and cheat.
But this has mainly 2 problems even if cleverly implemented.
1. The host needs to process the game and thus needs everyones data
2. Other's can mimic players and see game data anyways (by using others user ID)
3. Might lead to many unknown circumstances
That's why my plan never progressed.

**Comment by itanasi** [comment]
Another idea, turn timer? If you don't move in X time, either skip turn or resign eventually. Might need to be a Server thing unfortunately

**Comment by touhidurrr** [comment]
> Another idea, turn timer? If you don't move in X time, either skip turn or resign eventually. Might need to be a Server thing unfortunately

It can also be manually programming in a per client basis so that clients secretly kick out a player. (Lol)

I have always had similar Idea from mid 2021 when i started played Unciv. But for lazyness forgot it quickly. Maybe since now I have a server, I would try to implement such logic.

**Comment by touhidurrr** [comment]
Also now that I think about it. How would you know if this is a server or client thing if when you try to join a game, you see yourself kicked out. It would seem like seamless right? XD

**Comment by itanasi** [comment]
Trouble with client side is you can easily change system time

**Comment by touhidurrr** [comment]
> Trouble with client side is you can easily change system time.
> 
> Also, how would the system then pass the game to the next player?

Fetch the time from NTP or something on startup!!! Case closed!!!!

**Comment by qwerty2586** [comment]
I think multiplayer server should use websockets instead of constant polling preview save each 500ms. With websockets server can distribute save instant when is pushed by other player. With some stream code, it can be started distributing even before upload is complete for example. Also with websockets server is aware who is connected and signal this info to players. Server will also have awereness who is on turn and make players skip if timeout is reached. 

Here is interesting implementation of dummy websocket server.
https://github.com/mafintosh/signalhub

**Comment by touhidurrr** [comment]
> I think multiplayer server should use websockets instead of constant polling preview save each 500ms. With websockets server can distribute save instant when is pushed by other player. With some stream code, it can be started distributing even before upload is complete for example. Also with websockets server is aware who is connected and signal this info to players. Server will also have awereness who is on turn and make players skip if timeout is reached.
> 
> Here is interesting implementation of dummy websocket server. https://github.com/mafintosh/signalhub

Unciv uses free Dropbox API by default. So, no WebSocket for now. But I do think WebSocket support should be included. I am open to implement WebSocket for UncivServer.xyz if it is ever implemented. T

**Comment by itanasi** [comment]
Reviving this.

Something helpful would be a Password Screen for each time you start your turn. Merge it into the "Start <Civilization>" screen used for Hotseat.

If no Password, can just Continue.

If a Password is set, can opt to change it or just enter password to enter the turn.

Save hashed password in the save file per civilization.

Would improve security for Hotseat and Online MP.

**Comment by ravignir** [comment]
disable charts for non spectator players until the game ends.

**Comment by GGGuenni** [comment]
> Something helpful would be a Password Screen for each time you start your turn

It is currently shown on next turn when trying to upload the file and the password hasn't been set in the options yet or the set password is wrong. Only works if the server supports auth v1 and only for multiplayer, not hotseat.
(Well, I haven't checked for a while so it might not be working anymore idk 😅 )
uncivserver.xyz currently does not support auth if I'm not mistaken as there were plans to overhaul the multiplayer completely.

This is the line that triggers the AuthPopup
https://github.com/GGGuenni/Unciv/blob/1c15bd5cb62b4ffe64894cbb5988aa9060e89c9f/core/src/com/unciv/ui/screens/worldscreen/WorldScreen.kt#L624



> disable charts for non spectator players until the game ends.

I will add it to the issue description in case someone is searching for multiplayer stuff to work on

**Comment by alexban011** [comment]
@itanasi I already started implementing that but then decided to stop.
#7334
