### ISSUE TITLE
World Wrap Zoom Edges

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6407]
If you Zoom out further than the TileGroup map, then it will shrink down and not fill up the screen.

This becomes a weird thing especially on the WorldWrap setting where the top will get cut off instead of going to the top and you can see the cut off edges in the X dimension. Especially in small map dimensions and large resolution screens.

This is an artifact of how we do Zoom by shrinking the entire `ZoomableScrollPane` when we zoom out further than 1.0.

Better UI to cap the zoom somehow (seems difficult to constrain/calculate). Or fix so that the Y dimension with WorldWrap will take up more of the space. Or implement a true Zoom rewrite. Potentially by resizing the ScrollPane for every Zoom level.

![image](https://user-images.githubusercontent.com/44038014/159405579-1c9eb60a-31da-4d37-909a-a5a25351fcf3.png)

**Comment by SomeTroglodyte** [comment]
Link to #6354 just for reference.

FYI - I keep playtesting the same game, map, turn over and over with in-dev branches. Since this is in I usually see the same symptom, _but not always_. When it works, I love it... But I haven't found any correlation yet when and maybe why.

Lastly - this is a major performance hog. On that save (not too big: `type:Archipelago,shape:Rectangular,mapSize:{radius:30,width:66,height:43,name:Large},mapResources:Legendary Start,worldWrap:true,...`), especially leaving Civilopedia or Overview is noticeable with a few seconds, where before it was painless (OK the 12 cores are permanently at 100% here doing other things, but still :cat:).
