### ISSUE TITLE
universal suffrage civic doesn't add happiness

### ISSUE THREAD

**Issue by Timur512** [yairm210/Unciv#6485]
Version 4.0.2

**Comment by Timur512** [comment]
Actually it maybe Rekmod bug

**Comment by xlenstra** [comment]
Please use the standard template for bugs, so you at least include a save file where this bug occurs and the mods you have used.

**Comment by Timur512** [comment]
I can't include save file, it writes "we don't support that file type"

**Comment by SomeTroglodyte** [comment]
Unciv has a button "Copy to clipboard" on the save screen or the crash handler, and our bug template a section "If game data is required, please add it here" describing the process to include a save directly in the issue text. Otherwise, you'll need to follow the instructions right behind that message you quote - it _says_ try again with ZIP, if you know how to create compressed archives that's a possibility. Or rename the file to give it a ".txt" extension first. Many options.

Other than that - why should it add happiness? "[+33]% Strength for cities <when defending>" is what it is coded to do. Even if we had a BNW ruleset, which we don't, it would not add happiness, but reduce specialist unhappiness, same as "Democracy" in our current rulesets. As per the fandom wiki.

**Comment by yairm210** [comment]
Closing as "mod problem"
