### ISSUE TITLE
On Archlinux compiling it is always false

### ISSUE THREAD

**Issue by lishaoxia1985** [yairm210/Unciv#6491]
On Archlinux I cannot compile, it gives these messages:
Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

I have tried more times.

**Comment by SomeTroglodyte** [comment]
Running Android Studio Bumblebee or...?

If yes, start by:
* Close all edit tabs (or Studio will waste time interpreting stuff prematurely)
* make sure SDK Manager - Android SDK Platform 30 rev 3 (and sources - remember to check Show package details to see the truth) + Android SDK Build-Tools 30.0.3 are installed. This is the part that should work automatically (meaning auto download missing) but that has been broken since gradle 7.
* make sure a good JRE is used for gradle - should be part of the project config, but you can control that part yourself. A current LTE Java 11 from Adoptium perhaps, or the one Studio brings along and is running under? Worth trying.
* File - Invalidate Caches... and 'invalidate+restart' ticking the checkbox (studio needs this almost daily anyway).
* When the project reloads, wait. You should see Indexing and after that a gradle sync running. If that looks broken, as last resort, try starting a sync (File - sync prj w/ gradle or top right elephant). Wait. WAIT for it to finish before doing _anything_ else. If necessary, go outside for an hour. Or a day. Don't try to run/build before the sync is really done. (Normally a pending sync is clever enough to suspend/start over as necessary but if you already have problems better be absolutely sure).
* Build - clean and Build - rebuild.

If the box/profile is really old, a good cleaning might help. Bleachbit, then obvious stuff within the project like .gradle and <module>/build, then Studio's caches manually, ~/.gradle, ~/.android/cache, ....

**Comment by lishaoxia1985** [comment]
Ok, that will be solved when you install the right branch Android SDK Build-Tools, now the required version is 32.0.0.
