### ISSUE TITLE
Carthage AI frequently ends unit turns on mountain

### ISSUE THREAD

**Issue by 0avsz** [yairm210/Unciv#6589]
**Platform**
Operating system type, major version, architecture (64/32 bit).

Android

**Version**
Where you got the game and the exact version number.
4.0.6

**Describe the bug**

Carthage's AI frequently ends unit turns on mountains

**To Reproduce**
1. Choose a map with some mountains with Carthage as AI
2. Wait until she has a great general
3. Their workers and units have a high chance of ending on a mountain and will lose health

**Expected behavior**

AI should avoid ending turns with units on mountain if possible. 

**Screenshots**

**Additional context**
This issue also happens to automated units.
This is also a problem in Civ V.

**Comment by SomeTroglodyte** [comment]
I *just* saw this in a test game, and "Dido" is at least clever enough to not move such a unit onto the next mountain the next turn, so I did not see it as a problem. If we ever get to fixing movement properly (at the moment we have needless detours, needless stopovers with unused movement, and wrong estimates with changing maxmoves due to embarkment) this will probably solve itself, as we'll need some fuzzy logic to differentiate routes not only by speed.

**Comment by yairm210** [comment]
Closing for lack of interest
