### ISSUE TITLE
Placement issue on medium maps

### ISSUE THREAD

**Issue by ozyxcv** [yairm210/UnCiv#670]
On medium sized Default and Perlin maps (I haven't tested Pangaea yet) there is a significant chance that your settler will spawn within 5 tiles of the map's edge seemingly irrespective of total number of civs or starting bias. I have tested medium-Default in particular with 4 different civs (England, Arabia, Babylon and France) and out of 100 spawns each (50 with 5 enemy civs and 50 with 10 enemy civs) I was spawning within 5 tiles of the edge roughly 50% of the time. Results on Perlin are about the same except a larger portion of that 50% are on the literal edge tile of the map.

**Comment by yairm210** [comment]
Aha
Interesting
This makes sense even if the distribution is random, since the outer layers are always the largest
But this makes even more sense with the current method
What the current alg. does is try and maximize distance between civ starting locations, and once it the side effects would indeed be pushing everyone to the edges
Luckily this is also very simple to solve, I just need to have that distance be not only from other starting locations but also from the edges
Thanks, hope to deal with this soon!
