### ISSUE TITLE
Missing mods in Downloadable mods list

### ISSUE THREAD

**Issue by stixZman** [yairm210/Unciv#6758]
Hello,

Since a few days ago (I´m not sure if it´s related to latest 4.0.14 release or not) I´m missing some of the most starred and downloaded mods for Unciv in Android app (don´t know if it occurs in the desktop app)

If I navigate to unciv mod topic URL [https://github.com/topics/unciv-mod](https://github.com/topics/unciv-mod) I´m missing some repositories like 5Hex tileset, RekMod and many more.

Can anyone help me to download these mods from repositories? I uninstalled Google Play Store version in order to install apk directly from latest github release (since it takes a few days to update the release on Play Store)

Thank you very much in advance.

**Comment by SomeTroglodyte** [comment]
If you know the repo URL, there's a manual button (accepts repo url's if that repo uses 'master' as primary branch name, or a complete branch url).
![image](https://user-images.githubusercontent.com/63000004/167845594-66cb8fc6-a75a-43d4-8eb5-8844dd21510e.png)

But thanks for the heads-up. Can't believe querying directly on github also fails, but forewarned is good. ...Yes, seems a github failure. Nothing we can do. Maybe you could do us the favour to escalate directly to github?

**Comment by Ouaz** [comment]
Yeah, that's weird, 5Hex and Rekmod are not listed... although they have the unciv-mod tag. Sorting by number of stars, 5Hex should be on top of the list...

You can manually add these mods on Android by connecting your device to your PC (a bit cumbersome, but that's the only workaround until Github fixes the problem... if they fix it):

1) On your PC, go to https://github.com/ravignir/5Hex-Tileset, click on "Code" (green button), and select "download zip"
2) Connect your android device to your PC through USB, and select "Explore"
3) Navigate to  `Android/data/com.unciv.app/files/`. Here, creates a "mods" folder, and inside it, a `5Hex-Manual` folder. So it gives `Android/data/com.unciv.app/files/mods/5Hex-Manual`.
4) Open the zip file, and copy the `jsons` folder,` game.atlas`, `game.png`, `game2.png`, `game3.png`, `game4.png` in `Android/data/com.unciv.app/files/mods/5Hex-Manual` created in point 3 (`images` folder is not needed).
5) Unplug your Android device from you PC (eject/remove USB device if available) and start Unciv. 5Hex-Manual should appear in your installed mods list. Enable it as usual.

However, to uninstall it (when you'll want to), it won't work from Unciv mods manager (because the mod manager does not install/remove mods from the folder we created). You will have to connect again your Android device, erase manually the `mods` folder in `Android/data/com.unciv.app/files`, then start Unciv and click on "Remove 5Hex-Manual" to clean the installed mods list.

Did I say it was cumbersome? :D

**Comment by SomeTroglodyte** [comment]
Oh my. Going through MTP and two devices? Just copy the link _on Android_ into the box I showed, done. Android _has_ text copy and paste.

P.S.: [it's escalated](https://github.com/github/feedback/discussions/16392)

**Comment by Ouaz** [comment]
Oh god, I thought you said that even using "Download mod from URL" doesn't work... I misread. -_-'

I edit my previous post.

**Comment by stixZman** [comment]
Thank you both for your help about manually installing these mods! I finally got mods easily installed using "Download from URL" method.

As it´s not an unciv issue and it´s related to github, you can close this ticket.

Thank you again!

**Comment by xlenstra** [comment]
I've also posted a ticket directly to github, hopefully we'll get a response from either the forum or them directly soon

**Comment by stixZman** [comment]
Still no response about this from github and topic search is still missing many mods.

**Comment by xlenstra** [comment]
Seeing as we still have no response from github, maybe we should start thinking about alternatives, as github seemingly is unreliable?

**Comment by SomeTroglodyte** [comment]
It could well be that we hit some upper limit of their search engine, maybe even documented but devilishly well-hidden-so. Too lazy to check.

Also - moving - mulling the idea for the last few days, nothing comes to mind, and with the seeming shift to even less privacy- and open- friendliness than before in the space provider market (see the aggressive closure of we.tl,...) - dunno. A repo maintaining only a json pointing to mods, maybe with extra value added by that repo's maintainers? Every mod author >= N stars automatically made editor? A parseable wiki???

**Comment by xlenstra** [comment]
> I've also posted a ticket directly to github, hopefully we'll get a response from either the forum or them directly soon

Update: I've heard back from github support, and they fixed the problem specifically for 5hex-tileset. I've contacted them again as this doesn't solve our underlying problem (notably RekMOD and deciv-redux are still missing), and will tell more when I hear back.

**Comment by xlenstra** [comment]
Update: Github responded with the following:


> Thanks for the explanation there.
> 
> I've checked this and I get different results everywhere.
> 
> I used the [GitHub CLI](https://github.com/cli/cli) gh search repos --topic unciv-mod --limit 200 and got 154 results. This uses the REST API.
> 
> Using the [GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer), I got 194 results.
> 
> Query (you have to paginate this - 100 is the maximum it will return):
> 
```
query MyQuery {
  topic(name: "unciv-mod") {
    repositories(first: 100) {
      edges {
        node {
          nameWithOwner
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
      totalCount
    }
  }
}
```
> 
> On GitHub.com, it's saying 164 right now.
> 
> I have opened an issue with our search team, and I will let you know when I have an update. To set expectations, search is complex, and so this may not be something that gets resolved very quickly. It is likely worth playing around with the different options above to see if one of them might be more reliable for your uses for now.
> 
> You could also cache some results to prevent repositories that were already listed from disappearing if we have a search outage, or if the repository drops out of the index for any other reason.

Sounds like the best plan to ensure that everything works is to move away from GitHub search after all. I'm personally fond of the "have a GitHub repo with a json with links to each mod in it", though other options are always possible.

**Comment by SomeTroglodyte** [comment]
> personally fond of

Thanks. Adds value by having the "curated" repo pattern. Like ubuntu distros not having the discord client because their repo maintainers are in accord with my evil prejudices :smiling_imp: :zany_face:    ... or our hard block list (is this gone yet?)... Still, a lot of effort.

**Comment by SomeTroglodyte** [comment]
@xlenstra - you didn't _link_ said ticket. One might add that it even impedes the ability to manage PR's. Which seems to me could interest their staff far more than just a bunch of players not finding their mods.

I could push code to my Fork and open a PR in yours for it, but I can't at the moment do the same with [alexban011/Unciv](https://github.com/alexban011/Unciv) because the "choose a base repository" box fails the same way.

**Comment by yairm210** [comment]
IS this still ongoing?

**Comment by xlenstra** [comment]
A quick check shows that REKmod cant be downloaded in-game, so I assume so.

**Comment by yairm210** [comment]
It's been a while, re-checked this and everything seems in order, all mods are properly retrieved
