### ISSUE TITLE
Add condition for AI to declare war.

### ISSUE THREAD

**Issue by Caballero-Arepa** [yairm210/Unciv#6767]
I'm sorry for the title. So:

The issue:

Currently, I'm sure of it, the only reason AI declares war on someone is just because they have a far superior army and that's it.
The problem; This leads to situations of:
- All or most civs ganging up to a single civ
- AI declaring war very early on without the proper army (they often just have 6 warriors and 3 archers and think thats enough to conquer you)
- AI making war even with very high relationship (I don't know if this point is still there, as I never get declared war on).

An example has been shown on Discord by the user @Dzar#9770 [over here.](https://discord.com/channels/586194543280390151/586194543716859916/973663905731735684), where he wrote down all wars in a game.
This image just proves points 1 and 2.![imagen](https://user-images.githubusercontent.com/78449553/167895925-110f030b-e702-4241-b662-ac91ae91be03.png)
Here we see that Cartage is being attacked by the whole world, why? Because they don't have an army; and we see the army of 4 nations, which are a bunch of warriors that ain't going to do anything.

And I do think it's a problem, because it makes AI so predicable, that once you learn to keep up your military, you never have to worry about getting attacked, which is not that fun.

The solution [I see]:

To add the condition so War can only be declared if relation with the enemy is 0 or below.
This comes with various birds down with one bullet, as it allows for:
- Denounce action becomes actually useful
- Doing good diplomacy becomes important
- Avoids absurd situation where your "friend" attacks you

This would only be a cap for AI, but it could also be added to players but an exception would have to be placed if we add the limit to human players as well, which would be for player be able to declare war if a Protected CS is being attacked by other, and to possibility for player to declare war when relationship is still neutral, so warmongering effect can take place.
What about the diplomatic debuff of "Your so called friendship is worth nothing"?
It would trigger when you attack a civ after having recently declare friendship with it. (with nukes, denouncing or broken promises)
But I think is better to leave the condition only for AI.

Another thing that *could* be done is to add a sort of check list of units to have for AI to declare war. Bt maybe that's to much, so probably not, I just leave it on top of the table as an option.

I'm no coder so this is just a wish letter :)

On the topic, denouncing currently doesn't remove the warmongering effect, as it suposedly does in Civ V.

**Comment by yairm210** [comment]
Against Civ V policy, restricts player agency, not seeing it.
Diplomatic debuff exists already.
As for no warmongering if you denounced: what's your source?

**Comment by xlenstra** [comment]
So I've just scrolled a bit through the source code of the original, and among other things it contains an 800 line long function detailing exactly what stance AI should take towards another player, one of which is 'declaring war'. (`CvDiplomacyAi.cpp:2900` in expansion 1)

Looking through our code, 'declaring war' is just something any AI can do at any time, and while we give a small disincentive if you've actually signed a declaration of friendship with them (among other things), this means that friendly AI's can also just declare war at any time if they suddenly see an oppertunity. While _seemingly_ the original game also had that, that is because they had an entire backstab mechanic where an AI would pretend to be friends. In our case, they themselves believe to be friends, until suddenly they decide that their army is much larger than ours and attack.

It thus seems that while Civ V has a system determining a 'general stance' of each AI with each other (one of which is 'declare war') and every turn chooses the one most aligned with current factors, we just check every turn whether some arbitrary barrier for declaring war is met. This indeed shows a difference in behaviour, though solving it probably wouldn't go the same way as was noted in this issue.

**Comment by yairm210** [comment]
There's a fine line we need to walk between 'diplomacy is powerful so we can be friends with everyone and never go to war' to 'diplomacy is useless'.
Currently, if you're allies and have declaration of friendship, that's a -15 to them wanting to attack you.
So even if they WAY overpower you, so a +30 from that, they *still* don't reach the +20 needed for them to actually declare war on you. Only if they way overpower you PLUS you have an isolated city THEN will they declare war on you with DoF.
And even that goes away if you have a trade agreement, or you're trading them resources, or you're more than 7 tiles away, or there's no land route...
Making alliances even stronger would be pushing it to OP mode.

I think that's fair, and making it even stronger will

**Comment by yairm210** [comment]
The only real problem outlined in this issue is 'enemy declares war but can't actually take a single city', which - fair enough, but that's another reason *not* to declare war that we need to add.
The stars already need to align hard in order for AI to declare war on you, what's one more star...

**Comment by ArchDuque-Pancake** [comment]
Well,  it was more for the AI than the human, but as it violates Civ V policy then I'm sorry for bothering. At least AI is a bit smarter now
