### ISSUE TITLE
Feature request: Add notification for upgrades that requires resource

### ISSUE THREAD

**Issue by heipizhu4** [yairm210/Unciv#6802]
**Is your feature request related to a problem? Please describe.**
This issue comes from a not-a-bug bug report from my friend. He showed me a screenshot.
![image](https://user-images.githubusercontent.com/100454479/168410275-a04016e5-bd8b-4c78-9efd-a78632dcf4f1.png)
He reported that he wasn't able to upgrade the tank to modern armor, though he got enough gold and resource.
But in fact, he couldn't upgrade it because he has unlocked the Giant Death Robot already and didn't have enough uranium.
This is the situation which has enough resource.
![image](https://user-images.githubusercontent.com/100454479/168410716-7d81428c-3783-40a2-92ae-689c47678308.png)

**Describe the solution you'd like**
How about adding some notification to the upgrade tablet?
Instead of 110 gold and hiden, let it be 110 gold+1uranium and disabled.

**Describe alternatives you've considered**
Another way to resolve this is to upgrade the tank to modern armor. which requires one aluminum, which the player have.

**Additional context**
Not sure how civ5 deal with the upgrade issue.

**Comment by yairm210** [comment]
Showing resources on upgrade is a good idea even if it does succeed

**Comment by SomeTroglodyte** [comment]
.. and not being able to selectively control which of several upgrade possibilities to take is an old hat too .. Didn't that discussion end in "Civ5 doesn't too"?

**Comment by yairm210** [comment]
Yes, we upgrade to latest, because usually the older ones are deprecated anyway

**Comment by SomeTroglodyte** [comment]
... kinda makes me wish the GDR had its own upgrade ***Sound*** - steal something from some moronic transfuddlers movie and fade it over to a king gong roar...

**Comment by SomeTroglodyte** [comment]
I may have some energy left to try a solution in the next days. The Unit upgrading code needs a bit of cleanup, though.

Question: Our "upgrade to the latest" may save the user gold in extreme circumstances. Fix? Explanation: It's a delta from current to final unit value. If it were an aggregate of stepwise upgrades, a _negative_ step would be clamped to zero, so the overall would be more expensive than it is now... Yes sometimes an upgraded unit can be cheaper than its predecessor. Fix?

Question: fandom seems to agree clamping is done on the end result, so upgrading for 0 gold in these unusual circumstances is correct. But to me it feels wrong - clamping the delta before applying the +10 base and civ-wide deductions would feel more natural.

I would also re-introduce the "single step" upgrade - on the "more.." thingy, available only when multi steps possible, this would re-open access to intermediates if gold limited - or this resource situation. Should be a relatively minor effort.

**Comment by SomeTroglodyte** [comment]
Save game for testing? 90% done, but polish will take time. Needing to mock a test game situation even more.

**Comment by heipizhu4** [comment]
> Save game for testing
The file mentioned in the issue:
<details><summary>Saved game</summary>
[Rome - 346 turns.zip](https://github.com/yairm210/Unciv/files/8704435/Rome.-.346.turns.zip)
May require 5-Hex-Tileset
</details>

**Comment by heipizhu4** [comment]
> Save game for testing
The file mentioned in the issue:
<details><summary>Saved game</summary>
[Rome - 346 turns.zip](https://github.com/yairm210/Unciv/files/8704451/Rome.-.346.turns.zip)

May require 5-Hex-Tileset
</details>

**Comment by heipizhu4** [comment]
> Save game for testing
[Rome - 346 turns.zip](https://github.com/yairm210/Unciv/files/8704489/Rome.-.346.turns.zip)
The save game mentioned in the issue. May need 5Hex-Tileset. You can sell the nuclear plant in Rome to get uranium.

**Comment by SomeTroglodyte** [comment]
<details><summary>Screenshots</summary>

A Modern Armor that can upgrade (note free here just means the cost calculation returned zero! MA and GDR have the same cost in json, leaves the 10 base, -33% pentagon -33% policy makes 4.4, rounded down see below):
![image](https://user-images.githubusercontent.com/63000004/168854620-7063eaf8-7211-46d4-a3f2-9d8c5ac1fa25.png)
A Bomber:
![image](https://user-images.githubusercontent.com/63000004/168854698-afb45598-c431-4166-8ea3-7925952cc55a.png)
A Tank, GDR researcheed but no Uranium (your save):
![image](https://user-images.githubusercontent.com/63000004/168854828-dae4a986-3b26-4e94-8750-55bf60b43b9a.png)
"Second page" of the same unit:
![image](https://user-images.githubusercontent.com/63000004/168854888-4df5ec15-f820-49a7-8061-36c6c388d0cd.png)
Same for a Landship:
![image](https://user-images.githubusercontent.com/63000004/168854947-29d7df25-3386-459d-a0f6-deac4fe694f4.png)
![image](https://user-images.githubusercontent.com/63000004/168854977-b66c9a30-ffa5-440c-a50d-e21747b17b88.png)
</details>

... I have strong doubts our cost calculation is right. I have just applied the "round _down_ to nearest 5" mentioned on fandom, and that makes MA->GDR free. Feels mightily wrong.

Also, our "shortcut" to latest researched upgrade is not quite correct because it skips turns - fandom says skipping is not allowed, and what you gain is one turn per skipped upgrade. _Feels_ a little bit strange. You could upgrade that Landship to GDR if you scrounge up an Uranium from somewhere in 1 turn, or you could go Tank - Modern - GDR taking 3 turns, only the last blocked by lack of Uranium ... Also, late game upgrades feel much too cheap, and fandom mentions an Era effect but lists none. Someone remind me where those C++ sources can be found online???

Also, any other specific situations that should be tested? I need to test ruins and non-ruins free upgrades too. How did one trigger the latter again?

**Comment by SomeTroglodyte** [comment]
OK, so we're lacking this:
```C++
		const EraTypes eUpgradeEra = (EraTypes) pkTechInfo->GetEra();

		double fMultiplier = 1.0f;
		fMultiplier += (eUpgradeEra* /*0.3*/ GC.getUNIT_UPGRADE_COST_MULTIPLIER_PER_ERA());

		iPrice = int(iPrice * fMultiplier);
```
and this:
`iPrice = (int) pow((double) iPrice, (double) /*1.0f*/ GC.getUNIT_UPGRADE_COST_EXPONENT());`

Do their era numbers start at the same base as ours?

**Comment by xlenstra** [comment]
Looking through the game XML files, it seems like `UNIT_UPGRADE_COST_MULTIPLIER_PER_ERA` has a value of 0.0 in both vanilla and G&K (and BNW). I'll check in-game to see whether modern armor should just be upgradable to GDR for free, or what exactly goes on there

**Comment by xlenstra** [comment]
So I've checked, and for some reason the cost of upgrading a modern armor to a GDR is 10 gold, even though their costs are the same and `UNIT_UPGRADE_COST_MULTIPLIER_PER_ERA` has a value of 0. Looks like that 10 is the base upgrade cost, and it can't go lower than that? Not sure where in the code that last part is, though.

![image](https://user-images.githubusercontent.com/71121390/168901277-be0c53ad-39f9-441d-ad03-6c9c5d50233b.png)

 
> Also, our "shortcut" to latest researched upgrade is not quite correct because it skips turns

I believe this was polled and the community decided to stray away from civ 5 behaviour in this case as this was more user-friendly and such

**Comment by SomeTroglodyte** [comment]
Thanks! I just took the `/*0.3*/` to be the actual value - all the other comments seemed to be. _feels_ very reasonable, with pentagon and prof army you'll pay 10g for the MA-GDR upgrade:
![image](https://user-images.githubusercontent.com/63000004/168901543-3006696a-5528-44c1-9d04-df1e405f5c41.png)

While you're at it - does having Temple of Artemis change Ranged upgrade costs?

**Comment by SomeTroglodyte** [comment]
> 10 is the base upgrade cost, and it can't go lower than that

From the c++ code pentagon and prof army **_do_** apply to the 10 base so the observed 10 must be the era 0.3 ????

> community decided to stray

Yea my draft keeps to it, but now calculates cost step by step, could mean a coin more with landskniggits in there.

**Comment by xlenstra** [comment]
> From the c++ code pentagon and prof army do apply to the 10 base so the observed 10 must be the era 0.3 ????

My test was without all these discounts, I'll check what happens if you do have them

**Comment by SomeTroglodyte** [comment]
Btw, still no `markupEnabled` - any idea on how to make it clearer **_why_** the button gets disabled in screenshots 3 and 5 of [this comment](https://github.com/yairm210/Unciv/issues/6802#issuecomment-1129051414)? 

Opinion on the negative Resource requirement changes - drop them? 

And - the cost of Tank to GDR would become 370 gold for that Rome save included here _with_ 0.3 for multiplierPerEra (**no** pentagon **or** rebate from policy for Rome here; tank to MA: 10 + 2 * (425-375) makes 110, eraNumber is 7 so *= 3.1 makes 341 rounded to 340. MA to GDR is 10 base *= 3.1 for the era, rounded: 30. Sum: 370). Would it make sense to take that as indicator whether era should have an effect and compare that to Civ5?

(and thanks for helping!!! :pray: )

**Comment by xlenstra** [comment]
Edit: Yup, its free
![image](https://user-images.githubusercontent.com/71121390/168907134-68a82da7-792a-4a49-8ce0-023f58ac252f.png)

**Comment by xlenstra** [comment]
> any idea on how to make it clearer why the button gets disabled in screenshots 3 and 5 of https://github.com/yairm210/Unciv/issues/6802#issuecomment-1129051414?

My first idea would be to make the `-1 Uranium` red if there is no uranium, but not sure if that's possible or not (probably requires colour markdown similar to #5917? As otherwise you'd always colour the entire label)

**Comment by SomeTroglodyte** [comment]
> make the `+1 Uranium` red

I _said_ no markupEnabled yet which means we had _exactly_ the same train of thought.

> mod constant

The constants are long done, was just typing the wiki doc.

> think is best

In this case, I was at 50:50 myself, so it counts.

> Yup, its free

Pity. 10 felt so much better. And needs code refactoring since at the moment I xlate 0 to free, and that doesn't look proper in context. Still haven't tested the 'true' "FREE". I assume there was no template because that's not a  UnitAction but instant from elsewhere, so... Best fake a call with Alt-F8, possibly faster than actually setting up a game to trigger it.
