### ISSUE TITLE
Feature request: MP Vote Kick

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#6956]
Allow for vote kicking on MP and then taken over by an AI to allow games to continue if one player goes AWOL

**Comment by ArchDuque-Pancake** [comment]
Yeah, I do prefer a collective, player-base kick, rather than a time limit.
For example my Venezuelan friends often don't have energy (you know, the crisis) and so there are many days that they can't move, but we know that it happens, and are patient with them, because we are friends :).

Having a time limit would ruin that, for us at the least.

So I think is better for a voting kick, or at least an option to toggle it and/or set time limit.

How would it be done?

I imagine a button inside MP Game Settings, or somewhere in the MP window, where there appears to option to vote for a player (the player would be displayed as the civ it controls), a display of how many votes player has, and also maybe a display of how many days of inactivity there has been.

**Comment by itanasi** [comment]
My simple idea:
At game creation, set the minimum timer
During game can see how long since last move
In MP window if above the timer, an option appears to initiate a vote. Starting player obv votes Yes, event notifies all other players as well.
If unanimous, kicks player you're waiting on, AI takes over, play continues
If not unanimous, reset timer to prevent vote spam
If player makes move, continues as normal

**Comment by itanasi** [comment]
Still a very popular idea. Just no one had taken it on

**Comment by Caballero-Arepa** [comment]
Indeed.

At least that the game maker has and option to force-resign the current turn player .

**Comment by SeventhM** [comment]
> Still a very popular idea. Just no one had taken it on

I wouldn't be surprised if this could've been something apart of that multiplayer v2 idea. The bigger thing is probably just that idea haven't taken off and we kinda haven't touched the multiplayer system beyond that. Not my expertise, though, at best I could maybe see what about it could be piecemealed

**Comment by yairm210** [comment]
This is currently done as "after 24h any player can automate the current turn of current player, after 48h any player can kick turn current player permanently into AI"
This solves the problem mentioned and requires no cross-player sync
We're counting on players to not use this maliciously because tbh we can't defend at all against malicious players and we don't try to deal with that threat
