### ISSUE TITLE
Cant change locked citizen once you leave the city screen

### ISSUE THREAD

**Issue by alexban011** [yairm210/Unciv#6963]
**Platform**
Android 11

**Version**
4.1.2

**Describe the bug**
If you lock a citizen in a tile, once you leave the city screen and enter it back the citizen remains locked in until you click "reset citizens"

**To Reproduce**
1. Go to the city screen of any city
2. Click on lock a citizen on a tile
3. Exit the city screen
4. Enter back in the city screen
5. Now you can't change that citizen, unless you reset them all

**Comment by itanasi** [comment]
To clarify, seems you can't unlock them with one click, which is the behavior you previously would have had. If you select the tile and manually Unlock the tile, behavior returns to normal.

Pretty sure this is because on load it's blocking putting the onClick on locked tiles. Should be an easy fix if someone gets to it before me.
