### ISSUE TITLE
Game Ends in a Time Victory even if the option is turned off.

### ISSUE THREAD

**Issue by NoviceCoder2000** [yairm210/Unciv#7191]
**Platform**
Android OS

**Version**
4.1.8

**Describe the bug**
As the title already suggests the game ends automatically even if you didn't turn on the time victory option, making games on longer game speed impossible to properly finish.

**To Reproduce**
- Play a game ideally on Marathon or Epic.
- On Turn 500, the game automatically declares a time victory.

**Additional context**
This is a game of mine of Korea at Turn 499. Modded, yes although I don't think these mods used were directly the cause of the problem.

[Korea - Turn 499.txt](https://github.com/yairm210/Unciv/files/8924282/Korea.-.Turn.499.txt)

**Comment by OptimizedForDensity** [comment]
If anyone wants to open a PR to fix this, the issue is on line 58 of `VictoryManager.kt`

https://github.com/yairm210/Unciv/blob/0533c9eabade88adc3c9b65115288c645663af94/core/src/com/unciv/logic/civilization/VictoryManager.kt#L58

Changing `civInfo.gameInfo.ruleSet.victories.key` to `civInfo.gameInfo.gameParameters.victoryTypes` fixes this bug by only looking at the victory types that were enabled during game setup. However, this specific fix would cause the otherwise-harmless bug described in #7156 to cause crashes on any current or future games where someone has enabled (and not later disabled) a modded victory condition.

**Comment by JackRainy** [comment]
Thank you for confirming my ideas.
The PR is already there - #7197.
