### ISSUE TITLE
Inquisitor does not prevent spreading of religion by automated missionaries/great prophets

### ISSUE THREAD

**Issue by Azzurite** [yairm210/Unciv#7206]
When you put an Inquisitor somewhere, it is supposed to protect from spreading by missionaries/great prophets.

However, the AI unit automation does not contain a check for if an inquisitor is in a city, thus spreads religion anyway:

https://github.com/yairm210/Unciv/blob/4933082088e1e63d7a88d49e73db45be01a01827/core/src/com/unciv/logic/automation/SpecificUnitAutomation.kt#L296-L316

https://github.com/yairm210/Unciv/blob/4933082088e1e63d7a88d49e73db45be01a01827/core/src/com/unciv/logic/civilization/ReligionManager.kt#L331-L336

**Comment by OptimizedForDensity** [comment]
Did you see it happening? It looks like the "Spread Religion" action checks for if an inquisitor is within a tile of a city and be disabled if there is one

https://github.com/yairm210/Unciv/blob/9683e27526af844b43c2bdb9ff4af0890809c830/core/src/com/unciv/ui/worldscreen/unit/UnitActions.kt#L643-L667

That being said, the AI should be updated since AI prophets/missionaries may end up standing around trying to spread religion where they can't.
