### ISSUE TITLE
Feature request: new Tab for empire overview

### ISSUE THREAD

**Issue by MindaugasRumsa51** [yairm210/Unciv#7485]
New empire overview tab needed - diplomacy for spectacor only
it can display "Spectacor" word only if tab pressed by usual player

problem: current diplomacy tab shows only diplomacy for selected civilization, spectacor needs see more

**Comment by alexban011** [comment]
I don't really understand the issue here

**Comment by MindaugasRumsa51** [comment]
1. start new game. 1 spectacor human and 3 AI civs
2. you now are spectacor and after first turn you can look at diplomacy tab for whats going on
3.  select one of civs city from game screen
4. go to diplomacy tab and you will see what this selected civ is seeing. thats ok
5. now i want switch to Spectacor (i had not found such option) or switch to spectacor's diplomacy tab where spectacor can see all things, not viewing civ is seeing

**Comment by MindaugasRumsa51** [comment]
ps. you can download Potato version and look how this new tab working

**Comment by alexban011** [comment]
Ahh ok I sort of understand now.
So the diplomacy screen shows the spectator as a civilization and after selecting a civ you can't select the spectator? Well I think it should just be removed. I also strongly advise against adding an entirely new screen which is useless to the players and only (somewhat) useful to the spectator. I mean I opened your potato version and to me the screens look identical so I don't really know what is supposed to be changed? (they're also broken for me since I don't see the lines)

**Comment by itanasi** [comment]
I believe the request is that, when a Spectator and not selecting a Civ, you should still be able to see the Overview tab. Particularly the state of Diplomacy. Effectively giving the Spectator a true God-eye view of the current state of Diplomacy.

Otherwise you are only able to see Diplomacy from the view of particular Civs. Which late-game doesn't usually matter, but can be relevant when different Civs haven't met each other yet.

**Comment by MindaugasRumsa51** [comment]
itanasi, yes it is
also i found here way to hide tab from normal players and this way already exists sever lines code below where Religion tab is hidden when religion is disabled

by the way it is good to enable ability for spectacor to see selected civs technology and policies tree
it is possible, just tested it. only need some changes in tech and policy picker screens and in worldscreen

**Comment by alexban011** [comment]
> you should still be able to see the Overview tab. 

But you can? 

![Screenshot_20220727-165019_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/181263919-1d1dacf1-1acd-4e02-9cdd-f5bdb3654f50.jpg)![Screenshot_20220727-165013_UnCiv.jpg](https://user-images.githubusercontent.com/21990802/181263938-7d0e6b4f-e92c-4e13-a969-012bc95d0997.jpg)

What you can't do is deselect a civ (i.e select the spectator back) 
Also it would probably be best not to show the spectator in the tab, right?

**Comment by MindaugasRumsa51** [comment]
i am dumb enough.... we will wait for someone smarter to explain a problem

and i said - there is way to hide "D" tab from usual players

**Comment by alexban011** [comment]
> i am dumb enough.... we will wait for someone smarter to explain a problem

I mean.. itanasi did understand what you're saying so I think I might be the dumb one here haha

**Comment by itanasi** [comment]
Just checked a MP game I'm Spectating and you don't get the Diplomacy button.

But yes, cleaning things up so you can deselect the Civ and return to Spectator View, and some cleaning of the Diplomacy tab when it's in Spectator mode, could help. Basically fix the one tab we have, no new tab
![Screenshot_20220728-111737](https://user-images.githubusercontent.com/44038014/181609120-0bedebc5-2f3a-49c6-b87c-7074ec00431f.png)

**Comment by alexban011** [comment]
Interesting. 
So if you are not in the game you can't enter the screen, but if your player id is in the game you can see it but can't select the spectator again.

**Comment by yairm210** [comment]
Sounds like a super niche ask tbh.
Closing for lack of interest.
