### ISSUE TITLE
Feature request: Improved option to rename the unit

### ISSUE THREAD

**Issue by pyotr71** [yairm210/Unciv#7600]
Unciv has option to change name of Units, but its active ONLY when Unit achieving promotion:

![promocja](https://user-images.githubusercontent.com/18636457/182833404-5158a4ea-f09e-4f85-9cae-413adbe3cf53.png)

I think it's good idea to add this option permanently.
Where to put the option?
1. On the Overview -> Units screen

OR (maybe better)

2. On the Promotion screen (we get there after clicking promotion symbol)

![units](https://user-images.githubusercontent.com/18636457/182833602-76243bd8-6a90-4a14-8023-7907890e6901.png)

**Comment by Caballero-Arepa** [comment]
I super-agree with this. It has been asked *a lot* on the discord server, and I dont see why not implementing it.
It's such a great qol feature.

**Comment by huckdogg** [comment]
I have a working implementation of the rename feature for all units, even when they have no active promotions and no promotion available.

I changed the unit info box in the main map screen (below) so that clicking the unit name (red box) will take you to the promotion/rename screen. I did this because units with no promotions do not have a link to the promotion/rename page. Clicking the unit icon (yellow box) retains the old behavior of linking to wiki.
![ScreenShot_20220815_1660605113](https://user-images.githubusercontent.com/876926/184736188-6c65c07e-7719-45f6-ad34-21fac2bbbd60.png)

I have also changed the Overview screen for units to have an Edit column with a button that opens the promotion/rename screen.
![ScreenShot_20220815_1660604589](https://user-images.githubusercontent.com/876926/184738118-4cb583e5-e03c-470d-ba4e-e7f64eb9a0c0.png)

However, when the unit name is changed and the promotion screen is closed, the Overview page does not refresh to reflect the unit name change. If anyone has a suggestion on how to refresh the overview, I would appreciate it.

**Comment by OptimizedForDensity** [comment]
Full disclosure, I don't entirely know if this would work since I thought of this while flipping through some of the code files and not by actually testing it, but it might be possible to move the functions from `init` in `UnitOverviewScreen` to a function called something like `refresh()` (along with a few functions to clean up `Table`s and other variables to make sure you start with a fresh set of data). Then have `init` and a new function `override fun show()` call this `refresh()` function to 1) make sure you initially load the data correctly when you first enter the unit overview screen and 2) refresh data whenever you leave the promotion picker screen which happens when you call `show()` on the `Screen` which happens when `UncivGame` calls `setScreen()` when you close out of the promotion picker screen.

**Comment by huckdogg** [comment]
Thanks for the help @OptimizedForDensity. You pushed me in a direction where I was able to find a solution.

I actually switched over to using the AskTextPopup in all situations where the rename can happen, which allows me to run code after hitting OK. 

I have completed the coding and testing, and I will be submitting the PR before the end of the week.
