### ISSUE TITLE
mod doesn't show up in menu and world creation

### ISSUE THREAD

**Issue by Squarehead365** [yairm210/Unciv#7643]
**Platform**
linux, 64bit

**Version**
4.2.3

**Describe the bug**
i made a mod, but i doesn't show up in the mod menu and i cant choose it

**To Reproduce**
1. open the mods tab in game
2. load by url
3. program says its successful but mod isn't showing up
4. try to create world
5. cant choose it
6. check folder and the mod is there but isn't showing up

**Expected behavior**
the game appears in menu and can be chosen

**link to mod repository**

https://github.com/Squarehead365/The-Regulars

**Comment by xlenstra** [comment]
This often happens when there is a syntax error in one of your json files. Does your mod show up in the options -> find mod errors screen? If so, fix the error it notes there. If it doesn't, try opening the game from a terminal, then the error will be printed either when the game starts or when the mod is installed.

**Comment by Squarehead365** [comment]
The error is:
`Exception loading mod 'The-Regulars":
    Cannot read the array length because 
    "items" is null null
`

What should I do?

**Comment by Squarehead365** [comment]
i figured it! i leave buldings json empty, and didn't delete it. thanks you for all you support!
