### ISSUE TITLE
AI builds the same wonder as the player had built previous turn

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#782]
Americans ignore Japanese wonders!!!

Please check the [save](https://raw.githubusercontent.com/Am-per-Sand/saves/master/wonders), press next turn and check if another Louvre gets finished in Washington

**Comment by sulai** [comment]
I can reproduce and your case is a very special case because the two wonders are finished just one turn apart. In that case, canceling the other wonders does not work.

**Comment by sulai** [comment]
I tried to fix it, but I didn't find a proper way to test it. You would need to restart your turn, so the cancel-other-wonders thing will get triggered. Do you happen have a saved game of the turn just before (or maybe some turns before)?

**Comment by yairm210** [comment]
Hm
One thing we should implement for debugging reasons is saving autosaves a number of turns back

**Comment by ozyxcv** [comment]
I've had this happen playing multiple civs not just the Americans, but usually it only happens on the same turn i.e. I'll get a "_____ has been built in ______" but it will also be finished in my own on that same turn

**Comment by yairm210** [comment]
I see the problem then... 🙄 
What happens is, the production points are added on the END of the turn, and it should be thus - because that's when we have the 'start for that turn' for science and gold reasons
But the construction is only built at the BEGINNING of the next turn, so you don't build a unit in a full city -> unit built outside city at end of turn -> unit attacked and killed before you had a chance to move it or anything

This leads to a problem when between the end of your turn and the start of the next, the building is no longer available - but you're already amassed all the construction points you need for it, so it gets built anyway!
