### ISSUE TITLE
Workers: AI creates too many, attacking them gives too much XP

### ISSUE THREAD

**Issue by jmuchemb** [yairm210/Unciv#7869]
I don't see why the AI creates so many workers. For me, it gives the AI a significant disadvantage, in 2 ways:
- there's obviously the fact that producing useless units is a waste of resources: it costs gold to maintain them and if the AI doesn't know what to produce, it can produce science;
- I can train my ranged units a lot by attacking them. Sure, it's fun but given that they don't cause any damage, I don't find realistic that units can be trained this way, or at least not more than against barbarians. I wonder what's the behavior of Civ5.

To better illustrate "too many", it's to a point than on my side:
- I create only 2-3 workers during the whole game, whatever the size of my empire
- I kill many (see above)
- I capture many
- I use some to distract the AI
- and still I disband many

**Comment by iamlibertybell** [comment]
I don't think it is a bug.

For a 5*5 city,  it have 18 blocks, For a 7*7 city, it have 36 blocks.
An impovment needs about 5 turns (4 turns on building + 1 turns on movment) to finished.
For 10 cities, it takes  900 (18*5*10) ~ 1800 turns (36*5*10 ) to finished all.

It takes 300~600 turns on 3 workers,  90~180 turns on 10 workers.

**Comment by uuoooh** [comment]
I have just seen a game where ai couldnt settle new areas because workers blocked everything. AI empire was blocked everywhere but the 4 tiles wide sea access and after sending one settler through there to settle some island outside mainland the horde of workers rushing to upgrade that one island stopped in there - because some workers already did everything - and plugged the passage so completely that the next settlers couldnt pass. There were like 20 workers in that area.
Also blocked generals from reaching some city state ai declared war to but it didnt matter much.

**Comment by uuoooh** [comment]
> For a 5 * 5 city, it have 18 blocks, For a 7 * 7 city, it have 36 blocks. An impovment needs about 5+ turns (4 turns on building + 1 turns on movment) to finished. For 10 cities, it takes 900 (18 * 5 * 10) ~ 1800 turns (36 * 5 * 10 ) to finished all
Yea but cities start tiny and expand slow enough that a single worker is enough for like 3 cities, or twice that if cities are coastal and spread deep into water, as is generally profitable to settle. You cities start at size 2 with only one tile needing upgrade, and slowly grow from there, if a city is big its usually got there by having upgraded tiles already, theres never a need to upgrade huge tracts of land quickly.

**Comment by yairm210** [comment]
Currently the formula is "build workers as per the number of cities". 
I don't think that 3 workers for an entire empire makes sense, at least not for the sizes I've seen, but I'll change this so that about 3 workers, the AI will try to make 1 worker per 4 cities. e.g, for the first 3 cities it wants a worker, but the next one will only come at city 16, then at city 20. We'll see if that's a good ratio.

**Comment by jmuchemb** [comment]
> I use some to distract the AI

And that also. I keep finding the AI attaches too much importance to workers.
