### ISSUE TITLE
Memory leak in 4.2.11

### ISSUE THREAD

**Issue by hippie68** [yairm210/Unciv#7876]
**Platform**
Linux, Debian 11, x64

**Version**
4.2.11 .jar file

**Describe the bug**
While playing turns for just a few minutes, memory usage steadily grows to more than 4 GB until the RAM (6 GB) is full and the OS freezes.

**To Reproduce**
Play a game with the 4.2.11 Java file (openjdk 17.0.4 2022-07-19).

**Expected behavior**
The memory usage does not grow until 6 GB of RAM are full.

**Screenshots**
![memory_leak](https://user-images.githubusercontent.com/65259318/193155977-c6e76c53-b52b-4a2c-a71f-6b626231e1fb.png)

**Comment by touhidurrr** [comment]
doesn't happen in previous versions?

**Comment by hippie68** [comment]
Now I have tried 4.2.8, which has the bug, too. The memory leaks after ending a turn.

**Comment by yairm210** [comment]
Okay, this is really freaky
I can see the memory usage go up on the performance monitor, even when I set -xmx100m so it shouldn't consume above 100mb of memory
But, research lead to [this'(https://plumbr.io/blog/memory-leaks/why-does-my-java-process-consume-more-memory-than-xmx), and so I tried setting -XX:MaxPermSize=100m and that *did* crash.

Following @Azzurite's excellent advice at #7491 I ~~took a dump~~ - *generated* a heap dump file from the game and it shows something interesting:

![image](https://user-images.githubusercontent.com/8366208/193465930-bf34674c-2382-4567-9bd4-1621391dc1db.png)

The important parts here are that there are 5 WorldMapHolder and WorldMapScreen in memory, when we should be disposing of the old ones as we generate new ones.
It's very hard to understand who's holding a reference to it, but it's definitely still there, 

Thing is, screens *are disposed*, and most of their data is gone, but still somehow something is still referencing them - so what is it?

After a WHOLE BUNCH of digging, it looks like this is the suspect:

![image](https://user-images.githubusercontent.com/8366208/193469123-93e321a5-1fbf-4c8b-899f-297a6bf0cf7b.png)

addZoomListener doesn't actually use an existing class. Instead, it creates an object *based off of* an existing class, with some changes.

Since class objects are never disposed of, and remain in the permanent storage (remember MaxPermSize?), if we create a class with a reference to the zoom pane, which references the world map holder, which references the world map, *none of them* will be disposed!

So that's my guess for now, going to try and turn all those 'dynamic classes' into real honest-to-goodness classes and see it if makes a difference

**Comment by yairm210** [comment]
Well that wasn't it.
I have no idea what's going on, I can't seem to simulate the OOM error except on extremely small max memory sizes

**Comment by yairm210** [comment]
But the used mem is still showing up as like 600mb

**Comment by touhidurrr** [comment]
> The important parts here are that there are 5 WorldMapHolder and WorldMapScreen in memory, when we should be disposing of the old ones as we generate new ones.
It's very hard to understand who's holding a reference to it, but it's definitely still there,


Well it seems like my random guess was plausible. I actually thought that this might be an issue. That's why I talked about Garbage Collector in Discord. Such a thing in Unciv is nothing new as it has been reported before that Unciv takes more and more memory as the game progresses.
I thought it might be because the game isn't dumping the old game objects properly and Garbage Collector is not doing good enough job to dump useless parts of memory and thus it keeps piling up each time the client refreshes. I thought it might be interesting to see if using newer JRE's results in better use of memory.
But then I saw that the person who opened this issue was actually using a newer version of JRE. So that means we need to resolve this issue manually.

As objects are basically references, deleting objects often results to nothing.
The only solution I can think of is manually deleting all variable and objects and lists recursively and building new object.
That might work, who knows.

**Comment by touhidurrr** [comment]
Another solution is dynamic object building. Instead of dumping the whole game object, we can try to make minimal changes to the object to represent the updated version of the game. Also never done anything like this myself. Not sure if this would solve the issue but should improve performance if ever implemented.

**Comment by hippie68** [comment]
Seeing you mentioned the World Map, perhaps it may help to know I played in 4K native resolution and set the game's internal resolution to 1500x1000. I also changed the game's default settings to show more icons on the map. Perhaps this all contributes to more memory leaking than it would on smaller screens.

![memory_leak_settings](https://user-images.githubusercontent.com/65259318/193555701-ec723e94-4519-4740-a230-8a8f2ba04a4a.png)

**Comment by yairm210** [comment]
After 'general' memory profiling on Android for about 20 turns, I discovered the following:

Start:

![image](https://user-images.githubusercontent.com/8366208/197355975-5fc617b0-c9b7-4b54-b1b6-9f51c9fd8217.png)

After some turns: 

![image](https://user-images.githubusercontent.com/8366208/197355751-43c9fb12-5e33-48ae-8a88-720fff08c643.png)

After move turns:

![image](https://user-images.githubusercontent.com/8366208/197355874-ac9c81cf-239a-4954-b894-59ed2c049840.png)

After some time doing nothing:

![image](https://user-images.githubusercontent.com/8366208/197355896-58fb5787-3e65-445c-afc4-2836b94711a2.png)


**Conclusion**

The reason the Java memory limiters didn't cause OOM exceptions is because the leaking memory *isn't from Java objects*. It seems to be from Graphics, which rise about 10MB every turn, so after 100 turns you'll have an entire wasted GB of them.
I these 'Graphics' are OpenGL textures or somesuch, but I'll try to research this and mem dump the Android after we have a lot of that so we can see where it's actually going.

**Comment by yairm210** [comment]
![image](https://user-images.githubusercontent.com/8366208/197356222-facd30b9-d972-4e31-9104-450bad21a17b.png)

O SHIT SON

**Comment by yairm210** [comment]
And indeed, a memory dump of this point:

![image](https://user-images.githubusercontent.com/8366208/197356489-37d9732c-d168-4021-9c18-29ad1ef14250.png)


Gives us this:

![image](https://user-images.githubusercontent.com/8366208/197356542-1d23e237-59aa-4c78-af3b-7d75f58d3084.png)


Or in other words, 'out of 500MB Java can account for about 200MB'
The numbers don't exactly line up but it's the right ballpark

**Comment by yairm210** [comment]
And it turns out this memory *problem* is the result of a memory *saving* technique 

Every time we switch the old world screen out, instead of creating a new one concurrently to the previous leading to twice the memory footprint and to "out of memory" errors, @Azzurite implemented the frankly genius technique of taking a *screenshot* of the current screen and showing that to the user whil ein the background we dismantle the old screen and create the new one.

The problem was, that this 'temporary screen' was never manually disposed, and those 'screenshots' are OpenGL textures, which means they aren't auto-disposed... and thus every turn a new 'screenshot' was created which (depending of course on screen size and resolution) could be 10MB.

Those screens are now disposed, the 'Graphics' part of Android profiling no longer rises by 10MB every turn, and so this should be resolved.

# Final Conclusion

MEMORY PROFILING IS A BITCH

**Comment by touhidurrr** [comment]
Finally I got to know why Unciv takes so much memory. The actual reason seems to be interesting. Seems like interacting with high level API comes with the unintended drawbacks of sometime not realizing the behaviour of low level API's.

I read that losing data is common at low level API's, not it seems like hoarding data is also.

Lol.

**Comment by hippie68** [comment]
I am now using version 4.2.15 Build 759, and the memory still leaks after every turn until the 6 GB of RAM is full after just a few turns. This is the Unciv.jar version on Debian 11. I am playing with Unciv resolution 1500x1000 in 4K desktop resolution.

```
java --version
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)
```

**Comment by touhidurrr** [comment]
And we thought that the story was over......
