### ISSUE TITLE
Feature request: Ban certain nations (from pick or random pool) in online multiplayer

### ISSUE THREAD

**Issue by letstalkaboutdune** [yairm210/Unciv#8399]
This request is an attempt to enable players to create a more competitive multiplayer experience.

The idea is that in many competitive multiplayer games, there is a "ban phase" where players can choose certain characters, heroes, etc., (in our case nations) to ban from the pick or random pool. I'd like Unciv to implement something like that.

Perhaps the players could agree beforehand and choose a list of as many nations as they want to ban. Or, each player could receive one ban that they could apply to any nation.

In terms of UI, this could be achieved with a "Competitive Mode" tickbox in the new game options, which would then display new buttons for banning. It could also force the Demographics dashboard to be used in game, which limits the amount of ranking information that a player can see for other nations .

**Comment by alexban011** [comment]
I like the idea, but.. :

How would this work exactly? Because right now you add the players and choose their civs. Actually you don't even add the players.. you just add an id and the game just checks if the id looks valid, so it has no clue if anyone actually has that id.

One way I figure this could be implemented would be to choose how many civs you want (and their ids if they're human) and then create the game without actually creating the map (which isn't possible currently). Then the people choose their civs in something that would resemble "turn -1". And then the first player in the list actually creates the game. 

I figure this would require a lot of refactoring so I'm definitely not going to even try working on this :D
Even teams might be easier to implement :)

**Comment by alexban011** [comment]
I mean removing certain nations from the random pool isn't hard, but giving players (other than the one creating the game) options to ban nations is. 

So a "remove list of nations from random pool" feature would be much easier to implement, but of course, you'd have to trust the host that he will actually remove them.

**Comment by letstalkaboutdune** [comment]
Yes, I'm thinking very simple here. Keep the honor system philosophy of new game setup, so the players agree on which nations to ban ahead of time. Then the host can choose banned civs when setting up the game. This is mostly relevant for random, otherwise they can simply not get picked.

Players can always double-check the game settings by using the "Start New Game" workaround while in-game. Of course, a clean way to see game settings while in-game would be even better, which is another feature request. :)

**Comment by letstalkaboutdune** [comment]
Another nice application of this would be to ban all non-mod civs when playing a modded game. That way you could random just from the pool of civs from the mod.

In fact, it would be even more convenient if in the ban window, you could select banning all civs from any enabled mods.
