### ISSUE TITLE
Translation file mistakes

### ISSUE THREAD

**Issue by balazsszalab** [yairm210/Unciv#8463]
The line bellow should have an equation sigh after it, I think:
due to discovering a Natural Wonder

There is no such button as indicated bellow:
Click 'Create improvement'

The correct text should be:
Click 'Construct improvement'

**Comment by Ouaz** [comment]
> The line bellow should have an equation sigh after it, I think:
> due to discovering a Natural Wonder

This will be fixed in next release (dd9f946).

In your Hungarian language file, you can add the missing ` = ` and translate the line as usual.

> There is no such button as indicated bellow:
> Click 'Create improvement'

>The correct text should be:
>Click 'Construct improvement'

Ah... true. It's a small error in the Worker tutorial. I don't know if I'm going to fix it, as translators will have to translate the whole sentence again (though they can copy the previous translation, and simply modify the button name)...

`Construct an improvement!\nConstruct a Worker unit > Move to a Plains or Grassland tile > \n Click 'Create improvement' (above the unit table, bottom left)\n > Choose the farm > \n Leave the worker there until it's finished`
