### ISSUE TITLE
Feature request:  [macos] when opened with JavaLauncher.app, Game settings and saves are lost on game close

### ISSUE THREAD

**Issue by yw662** [yairm210/Unciv#8492]
**Is your feature request related to a problem? Please describe.**
If the game is opened with `java -jar` from terminal, it will save gameSettings and saveFile in current directory, and can be loaded next time. 

However, if the game is opened by double click (or, by `JavaLauncher.app`, this is the default handler for `.jar` files on macos), it will always open to the language selection UI, and all previous game settings and saves are lost.

**Describe the solution you'd like**
Maybe the game can default its settings and saves path  to `~/.unciv`, `~/.config/unciv` or `~/.local/somewhere`, on macos or *nix.

**Describe alternatives you've considered**
or use somewhere else, I don't know :).

**Comment by harens** [comment]
Just to note that this is fixed in the [MacPorts build](https://ports.macports.org/port/unciv/). Game settings/mods/etc. are all saved after closing or upgrading the program.

```
sudo port install unciv
```

Bonus: Why have `JavaLauncher.app` when you can have a nice Unciv app with MacPorts :)

![image](https://user-images.githubusercontent.com/12570877/219956808-a70c6cb8-3563-4719-8ad9-958043f23c0a.png)
