### ISSUE TITLE
Feature request: Add "religion cap" in the civilopedia

### ISSUE THREAD

**Issue by saud2410** [yairm210/Unciv#8496]
Based Version: 4.4.6 win64

Include "religion cap" in civilopedia-tutorials-religion.

Steady-FAQ in Unciv discord is "I can't found religion, why?"
Usually the answer is "There's a cap for religion number."
( which is iirc `[ "number of all player" ÷ 2 ] + 1` )

There's no problem answering to such important question over and over again.
But It requires simple math, sometimes it's little confusing for me.

I think it worth to be included in civilopedia, with clear & concise words.
Civilopedia-tutorials-religion might be good, or any other places.

**Comment by yairm210** [comment]
How would you phrase this? Can you write the line you would like to see there?

**Comment by OptimizedForDensity** [comment]
The exact number of religions that can be founded in a game is the minimum of the following values
* `numPlayers / 2 + 1`
* Number of founder beliefs defined in ruleset - number of founder beliefs used by established religions (not necessarily equivalent to the number of founded religions since Byzantium or mod equivalent can take a second founder belief)
* Number of follower beliefs defined in ruleset - number of follower beliefs used by established religions (similar note as the above point)

I think these should also be mentioned in a civilopedia entry too since it's relevant for total conversion mods and people who like to play games with tons of civs. In G&K Unciv, the max number of religions can be as low as 7 (6 enhanced religions, Byzantine enhanced religion with an extra follower belief pick, and a non-enhanced religion).

**Comment by saud2410** [comment]
![civilopedia-religion](https://user-images.githubusercontent.com/64586749/215581111-f82e6957-c140-4066-89d9-982294a369fb.jpg)

> Current: Do take care founding a religion soon, only about half the players in the game are able to found a religion!

> A: .., only half of the player in the game +1 religion can be founded!
> B: .., only about half the players in the game are able to found a religion! (`numPlayers / 2 + 1`)

Both are goofy... 🤦I just wanted someone to add it cuz i'm not a good English speaker. Anyway the point is showing basic math of religion cap. I think "only about half" isn't enough.

**Comment by OptimizedForDensity** [comment]
>Edit: Please make sure what happens when numPlayers is odd number. If there's 3 civ, religion cap is 2, right?

The division rounds down so 3 civs would mean 2 religions at most.

You could say something like "There must be at least 1 available Founder belief and 1 available Follower belief to found a religion. The maximum number of religions allowed in the game is capped at half of the number of civilizations (rounded down) plus 1, or the number of religions is capped by the number of entries in the Religions.json file for the combinations of mods you are playing with if this is a lesser value."

**Comment by Weverak** [comment]
Hey,
So you mean, if there is let's say 5 civs, you divide it by two and round it down, so that's will be 2. Then you add 1 and you get religions limit? If yes, I would like to add it on wiki.

**Comment by saud2410** [comment]
@Weverak `Divide - Round down - Add 1` is correct. Thank you for having interest on this issue.
