### ISSUE TITLE
Feature request: Recommend Number of Civs

### ISSUE THREAD

**Issue by itanasi** [yairm210/Unciv#8524]
We often get asked what number of civs per map size.

Would be nice to give recommendations of numbers of Major Civs and City States per map size when making a new game. Possibly also per generated type. And then obviously if people want more or less room they are free to make what they want.

**Comment by yairm210** [comment]
First we need to compile the amounts o

**Comment by yairm210** [comment]
I'll reopen this if anyone can compile a list of "map sizes to recommended players" from players

We can then extrapolate from that list what the optimal "land tiles per civ" calculation should be, so that when a player selects a map size we can calculate approximately how much land will be there and therefore what recommended number of civs is

But as it is this requires a lot of research before it's actionable

**Comment by Caballero-Arepa** [comment]
@ravignir
