### ISSUE TITLE
Using colored SVG instead of bitmap for icons

### ISSUE THREAD

**Issue by plasmalasgun** [yairm210/Unciv#867]
Using multicolor svg scales much better than using bitmaps

**Comment by yairm210** [comment]
A. The tiles, as they are, are pixel art anyway, so for them it shouldn't make much of a difference?
B. For all the icons etc. It could make a difference, but libgdx doesn't support svg out-of-the-box. I see there are implementations, but since it's relatively complicated and with low marginal utility, this will probably stay on the todo list for a while

**Comment by MayeulC** [comment]
Hmm, I also put a thumbs up for the OS icon.
Question: would you be against vector art as an icon pack at some point? I know i generally tend to prefer it, personally.

**Comment by yairm210** [comment]
I honestly don't see this happening anytime soon. Closing for complexity and low marginal utility.
