### ISSUE TITLE
The Android Navigation bar doesn't auto-hide on Galaxy S10

### ISSUE THREAD

**Issue by Kyliathy** [yairm210/UnCiv#872]
Hey :). Wonderful work with this game and awesome that it is OSS! How does one donate to this project?

Oh, and here's a screenshot of the problem I just described :).

![20190613_155756](https://user-images.githubusercontent.com/20860173/59439094-eaa92100-8df4-11e9-8c4d-875729c1fd47.jpg)

**Comment by yairm210** [comment]
Okay then, I leaned something new
 Didn't now this was even an issue, but apparently it's really easy to solve

**Comment by Kyliathy** [comment]
Hey :). By this you mean that the presence of the bar there is "by design"? :). For me, it breaks immersion a bit. 

Thanks for the quick answer. How does one donate to you?

**Comment by yairm210** [comment]
Nope, not by design - I was just unaware of this difference between phones (for me the navigation bar is built into a physically different part of the phone)

I'm not really sure what I would do with donations... this is a hobby project for me, and even if you gave me money I'm not sure what I could do with it to improve the project...?

The best help would be for you to join us in both reporting problems and maybe even working on the code itself, but even spreading the word is good =D

**Comment by Kyliathy** [comment]
I'd love to contribute one day to this. I'm a big fan of Civ series, but at the moment my job demands already too much of me :). 

I'm not sure what's the resolution of this issue. Did you make a fix for it or do I have some other way of getting rid of that bar?

**Comment by yairm210** [comment]
What I added should fix it, I can't check it because of the phone difference
Will enter version 2.17.7 so stay tuned, should get released in about a week (I just released a version so...)
