### ISSUE TITLE
Trade Offers Issues

### ISSUE THREAD

**Issue by Smashfanful** [yairm210/UnCiv#880]
When you propose a trade with another civilization, there is something that should be worth noting. You remember the "Our trade with [nation] has ended" notification? Well, that should only happen when said trade contains at least one of these deals: resource exchange, friendship, border-free deals or gold per turn; one-time deals, such as gold, technologies, war declarations, civ or city-state introduction and cities, shouldn't trigger that notification by their nature.

**Comment by yairm210** [comment]
Please be specific in the*title* of your issues

**Comment by yairm210** [comment]
This appears to already be the case, can you provide a counterexample?

**Comment by Smashfanful** [comment]
Well, during one game, I was playing as India, and encountered Rome. We exchanged technologies, as I gave Augustus the secrets of Mining and he gave me Pottery. Next turn, horever, I noticed the "Our trade with [nation] has ended" notification.

**Comment by yairm210** [comment]
...I don't think you understand what I mean by "meaningful names".
I mean "tell me what the problem is", not "what KIND of problem it is."
So here, the problem is "Notifications for end-of-trade should not activate after instant trade" or something like that.
You add a lot of issues that are all like "diplomacy issues", "trade issues", which makes it very hard to tell what they are if you're looking at the Issues page - you have to enter each one to find out.
