### ISSUE TITLE
sh: line 1: xdg-mime: command not found

### ISSUE THREAD

**Issue by JMarianoIFSTTAR** [yairm210/Unciv#8938]
**Platform**
Ubuntu 22.04

**Version**
     Version: 4.5.9 (flatpak app/io.github.yairm210.unciv/x86_64/stable)

**Describe the bug**
 
See title

**To Reproduce**
Juste install and run

LANG=C flatpak run io.github.yairm210.unciv 
sh: line 1: xdg-mime: command not found

but xdg-mim is installed

which xdg-mime
/usr/bin/xdg-mime

Not really a bug, since playing Unciv seems to be ok...

**Comment by yairm210** [comment]
@MayeulC sounds like a flatpak issue?

**Comment by MayeulC** [comment]
It is, this issue has been present for as long as I remember. This issue would be better in the flatpak repository.

`xdg-mime` is not part off the freedesktop runtime. You can indeed check that it's not here by running `which xdg-mime` inside the flatpak:

```
% flatpak run --command=sh io.github.yairm210.unciv 
$ which xdg-mime
which: no xdg-mime in (/app/bin:/app/jre/bin:/usr/bin)
```

I tried to find out what calls or uses it, to no avail. I don't think it's Unciv code calling it. Maybe java? As it is, I don't think there are any issues besides the message, but it's a bit annoying, indeed.

It seems some other programs are affected:
https://github.com/flatpak/flatpak/issues/2464

Reading that other issue, it could be due to Discord trying to use that, actually (I personally have no intention to use/no interest in Discord and would prefer if it was not shipped on an otherwise fully-open system but heh). I think Discord works fine without, still.

I could silence the output by piping it to `grep -v 'xdg-mime'`, but it may hide other issues :shrug:
