### ISSUE TITLE
Possible Feature: Open source machine translation

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9031]
<details><summary>This is Unciv running with on-the-fly machine translation, open-source, no network traffic:</summary>

Spanish...
![image](https://user-images.githubusercontent.com/63000004/227712365-ac039ade-c3f7-4daf-9a60-c69ec6e3f399.png)
![image](https://user-images.githubusercontent.com/63000004/227712368-a4aa47d4-f395-4242-9c35-9a4b442b7077.png)

Esperanto...
![image](https://user-images.githubusercontent.com/63000004/227714976-1def4a7d-f161-461f-a1ef-3587c40c2d2e.png)

</details>

Yes, it's FOSS[^2]. Quite funny[^1] in some ways - but what do you think? Yum or Bleurgh? On the fly for exotic candidates or as possible option to ḱick-start new languages... :zany_face:

Side question - the font names pulled from the OS run through translation - uh, how are the templates supposed to end up in the translation files? IMHO thouse are better off untranslated, besides, the OS may already have i18n them...

[^1]: Like Close -> Cercano. Valid without context, but wrong choice...
[^2]: Apertium.org

**Comment by yairm210** [comment]
I'm against, even english autotranslations are iffy at best and those are the ones with the most data.
We would be cleaning up after ourselves.

Translation is one of those areas where AI is *really* useful for *human translators* because it does 90% of the work, but I wouldn't want to put in translations with 10% errors. 
Maybe we can find a way to make this help translators...?
