### ISSUE TITLE
Unexpected prompt for server password

### ISSUE THREAD

**Issue by Chris1712** [yairm210/Unciv#9136]
**Platform**
linux x64 client (or android client), linux x64 multiplayer server

**Version**
Server 4.5.16-patch1, client 4.5.16-patch1

**Describe the bug**
A multiplayer game I've been playing for around a month no longer works - at the end of my turn I'm prompted to enter a server password, but one hasn't been configured. An empty password doesn't work, and the  Furthermore the `/isAlive` endpoint for the server I'm using returns `{authVersion: 0}` so I'm not sure why my client believes a password is needed.

If I've read https://github.com/yairm210/Unciv/pull/8716 correctly I don't think currently the server supports setting a password. I've found that reverting the server to 4.4.19, predating that work, resolves the problem even with the latest clients.

**To Reproduce**
1. Attempt to finish a turn as a player in a multiplayer game.
2. See the prompt for password, regardless of whether one has been set.

I can supply a savegame/work on a minimal recreation if that'd be helpful. The server doesn't appear to have created any other config files where passwords could be stored.

**Expected behavior**
No prompt to supply a password at the end of the turn.

**Screenshots**
The prompt I see:
![image](https://user-images.githubusercontent.com/8271330/230660146-0f4f395a-116b-47f5-a223-8301937450c3.png)

The multiplayer settings (I've got no ability to configure a password):
![image](https://user-images.githubusercontent.com/8271330/230660458-d5d6ecfb-93c6-4a6b-bd98-682a84bd1e9f.png)

**Comment by yairm210** [comment]
@GGGuenni @touhidurrr Any ideas?

**Comment by GGGuenni** [comment]
> I've found that reverting the server to 4.4.19, predating that work, resolves the problem even with the latest clients.

That's *super weird* especially if the server does return authVersion 0 in both versions

So I've got no clue what could be the problem right know

**Comment by GGGuenni** [comment]
Quick look at the code doesn't look suspicious to me
The worldscreen only pops the Auth popup if a MultiplayerAuthException is thrown https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/worldscreen/WorldScreen.kt#L571-L580

The exception is only thrown if a 401 is returned

Default value is still 0

So everything seems fine

**Comment by Chris1712** [comment]
Thanks for taking a look @GGGuenni. I'll do some more investigation myself and see if I can figure anything out, I'll report back.

**Comment by touhidurrr** [comment]
The password implementation of UncivServer.xyz is buggy and setting new passwords does not work. That's why it is not hosted on the main server but on `replit.uncivserver.xyz`.
I am rewriting the codebase in Nest.js and hopefully this would fix this issue.

**Comment by yairm210** [comment]
@Chris1712 Is this still happening? Is it only with the test server?

**Comment by Chris1712** [comment]
I'm not sure what's meant by 'test server' in this context. My friends and I play using [the server jar from this repo ](https://github.com/yairm210/Unciv/releases/download/4.6.5/UncivServer.jar).

I made a tiny repository including sample settings and a save file that reproduces the issue, if it helps: https://github.com/Chris1712/unciv-9136-repro

**Comment by Chris1712** [comment]
I've hooked up my debugger and made a little progress. The popup is shown because of a `MultiplayerAuthException` caught in WorldScreen.kt. 
`UncivServerFileStorage.saveFileData` gets a 401 trying to PUT to `http://localhost:27001/files/3472777b-d5b9-4067-bf3b-3ed665a6e996`
The server seems to throw the 401 hitting this check https://github.com/yairm210/Unciv/blob/master/server/src/com/unciv/app/server/UncivServer.kt#L133 - I will attempt a PR to rectify this.

**Comment by Chris1712** [comment]
This is fixed with the merge of https://github.com/yairm210/Unciv/pull/9261 - thanks for the help.

**Comment by unleex** [comment]
well, same issue just arose for me.. i was playing the game with four friends for two days, today i came home, opened my mac and all of the sudden, i see this prompt

**Comment by cwhaworth** [comment]
Someone I'm playing a game with just had this happen also.

android
app ver: 4.16.2
server: uncivserver.xyz

**Comment by touhidurrr** [comment]
For reference, the auth guide is in:
https://canary.discord.com/channels/586194543280390151/847173429056634951/1349344398894301195.
Auth was properly tested by the community before launch in:
https://canary.discord.com/channels/586194543280390151/1349344398894301195

The reason for the popup is probably because if there is no password associated with a userId in GameSettings.json, the client throws a popup. This is the intended behavior for the Auth implemented in Unciv. So, how do we deal with issues like: https://github.com/yairm210/Unciv/issues/9136#issuecomment-2816227128 and https://github.com/yairm210/Unciv/issues/9136#issuecomment-2816202063? I am not sure. I already guessed that this might happen as soon as we launch auth even if there is nothing wrong with the implementation. I tried to reproduce the bugs and failed. Everything seems to be working just fine.

All of these look like the users getting worked up by the auth popup.

**Comment by touhidurrr** [comment]
I will copy paste the passwords guide for UncivServer.xyz here for reference. @unleex @cwhaworth 
# Passwords Guide
1. Initially you will get an authentication popup. Any password will work. But this password does not set any new password. Any password is considered valid for **userId** with no password so that people who have not set any password yet have no issues.
2. To actually set your password, go to settings > multiplayer > set password.
3. Auth is only applicable for uploading a new turn into the server.
4. In the auth server, to upload a new turn, your **userId** needs to be in the game and you have to be authorized or have no password set.
5. As you can guess from rule 4, only players who have set a password have their **userId** protected. Any **userId** which have no password set in the server can still be impersonated.
6. So, to have a fully protected game, all of the players have to set a password. This way anyone else cannot upload a new turn even if they have the **gameId**. Because they do not have the passwords for any of the **userId** which is in the game to impersonate.
7. **userId's** or **gameId's** where all characters are the same (for example `00000000-0000-0000-0000-000000000000`) are reserved by the admin. **DO NOT** use these IDs.
8. **YOU** are **RESPONSIBLE** for remembering the password that you set. **DO NOT** bother the admons asking to reset them.

So, essentially, setting a password protects your **userId**. If everyone in a game has a password, then this protects the whole game and any 3rd person cannot upload a new turn maliciously.

**Comment by cwhaworth** [comment]
Thanks @touhidurrr 

>As you can guess from rule 4, only players who have set a password have their userId protected. Any userId which have no password set in the server can still be impersonated

we actually just tested if i am also seeing the popup by me setting their uid as mine, and yes I saw the popup in this case, so yea I understand why you guys implemented this. We'll give the instructions a shot and let you know if we run into issues. in that case is it fine if we continue this thread, or wpuld rather open a new one for tracking?

**Comment by touhidurrr** [comment]
> Thanks @touhidurrr 

Dont thank me yet. I am currently dealing with a major outrage and trying to fix it asap.

**Comment by touhidurrr** [comment]
@cwhaworth @unleex can you check if the issue persists?

**Comment by touhidurrr** [comment]
> what was wrong?

The list of player ids in the database were not populated properly for unknown reasons. So, the server couldn’t verify if you were on the server and kept rejecting random save files.

Trying to fix it, I attempted to clean preview files where this bug happened after writing some patches. Because this metadata was stored with preview files. But mistakenly run the query to all available files which wiped out all main save files because they do not have this metadata to begin with.

The rest is history.

**Comment by unleex** [comment]
@touhidurrr oh, glad that everything is fine now. why this 401 error started arising for everybody in one time?

**Comment by touhidurrr** [comment]
> @touhidurrr oh, glad that everything is fine now. why this 401 error started arising for everybody in one time?

Already explained above.

**Comment by cwhaworth** [comment]
Can confirm its working for us now too. Thanks, again @touhidurrr
