### ISSUE TITLE
Limit workers to owned tiles

### ISSUE THREAD

**Issue by Am-per-Sand** [yairm210/UnCiv#915]
except for roads maybe
or at least exclude improvements from foreign tiles

**Comment by yairm210** [comment]
Are you talking about automation, or to limit the possibility of building improvements outside?
Because if it's automation, we only build outside our borders if there's a resource right outside, so we can save time, and even this is a last-priority (below building roads to connect cities)
We never build improvements in tiles outside our territory

If it's about the possibility, I don't see any reason to not allow us to build outside our territory

In either case, not something I feel needs to change

**Comment by Am-per-Sand** [comment]
> only build outside our borders if there's a resource right outside, so we can save time, and even this is a last-priority (below building roads to connect cities)

If you build a city between city states, don't exceed too much on its culture, their settlers will eventually improve a lot of tiles, and afterwards you can improve your culture speed or simply buy them - looks like an exploit, but I think AI would do the same if automated workers of the player would improve their cities neighbouring tiles. In other words looks like an exploit...

,,,

> We never build improvements in tiles outside our territory

See above and below:

> If it's about the possibility, I don't see any reason to not allow us to build outside our territory

,,,

And how does it work during war-time or open-borders?

**Comment by yairm210** [comment]
Same during war time - why should us being at war affect whether I can build in your territory?

**Comment by yairm210** [comment]
As for open borders, well... there's a known exploit in Civ games where you build roads in your enemy's territory to raise upkeep costs. I plan to introduce an alert from the AI if it recognizes you're doing this and have future roadbuilding lower diplomatic relations, maybe even be declared an act of war?
