### ISSUE TITLE
Feature request: Clearer friendlier Battle strength comparison

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9205]
@Ouaz presented this in an otherwise unrelated [issue](https://github.com/yairm210/Unciv/issues/9186) [discussion](https://github.com/yairm210/Unciv/issues/9186#issuecomment-1510495186) - and suggestion three is way cool. _Quote_:

***Currently:**
![current](https://user-images.githubusercontent.com/11946570/232338777-72958d8b-2a1b-459f-af29-6a731171acc3.png)

**1st suggestion: HP numbers on/off setting** (simplest fix ^^)
A setting in Display > Interface:  `[ ] Show HP numbers in battle table`. If unchecked, no numbers, so people with OCD are happy again.
<img src="https://user-images.githubusercontent.com/11946570/232338841-8da980e9-d04c-4a2e-bd3c-5cc5ccd29c27.png">

**2nd suggestion: Detailed data**
As people finds  `65 -> 35-20` is not a logic way to write the HP (despite the bar above showing exactly that), detailed data is used instead:
![detailed_hp](https://user-images.githubusercontent.com/11946570/232343249-8a5e6242-0f2d-4984-9a6c-a57e43ed6b7a.png)

**3rd suggestion: Big Bang overhaul** (designed by @letstalkaboutdune )
![big_bang](https://user-images.githubusercontent.com/11946570/232341913-5d2b1316-6bd1-46a9-8a55-e8ba059f135b.png)
- Vertical HP bars for direct comparison.
- Simplified text bonus for better readability and more compact battle table.
- Bonus texts are linked to their corresponding Civilopedia articles if the player needs more information.

The 1st suggestion would make my day, if the other ones are too much a hassle to implement. :smiley: 

--- _End-Quote_. 

It was also mentioned that the current version is extremely jarring to certain minorities, and if that can be alleviated with something as nice as that, I'd say yes please. (no guarantee I'll take the bait myself though, so if anyone wants to take a shot, "assign yourself" up there top right)

**Comment by itanasi** [comment]
I don't think it was intentional. It was a mock up and likely just swapped which started full.

**Comment by letstalkaboutdune** [comment]
It's been quite a while, but I'm pretty sure it's just a mockup. No meaning to which side is full vs. not, just an example.

**Comment by yairm210** [comment]
We had this discussion endlessly on Discord, we did a gazillion polls.
People want to see the numbers.
If anyone wants to work on the 3rd option then go for it but I'm not doing any more healthbar changes, I'm sick of it.
Ouaz knows he's in the minority regarding number direction, since there was a clear poll on the matter.

**Comment by Ouaz** [comment]
:disappointed:

I really tried to see the numbers disconnected from how the bar depletes, like this: `current health -> health range after battle`.
It seems that how majority of people sees it. No problem.

But I can't.
I just mentally link the numbers to the colored parts and the health bar direction, making me read it this way:
![reading](https://user-images.githubusercontent.com/11946570/232610360-f57bf74a-0e64-4bdb-932d-10fa65a83963.png)

To make an analogy, take the "rabbit shape" on the Moon. Once you see it, it's impossible to "unsee" it.

It's the same thing for me with this bar and these numbers, it's very annoying each time I watch it, because I know these numbers do not match the bar direction just above, and I have to read them this weird way. It even hinders somewhat my gaming experience.

That's why I solemnly ask to add the 1st suggestion:
A setting in Display > Interface: `[x] Show HP numbers in battle table`
The setting would be activated by default, so users who have not problem with these numbers, won't even notice the difference.

Please.

Thank you for reading.

**Comment by itanasi** [comment]
Lower left followed by upper left imo

**Comment by letstalkaboutdune** [comment]
I think upper left is the best overall. You get the clarity of having some of the black showing up on the sides, but it's wide enough to see the bar well.

**Comment by letstalkaboutdune** [comment]
It's hard to tell what's "real" and what are rendering/compression artifacts. Also I have no idea what happens with zoom/pan when given only a static image. But actually I'm gonna duck out of this convo because UI in this game gets me tilted.

**Comment by Ouaz** [comment]
I slightly prefer 3/0.5 due to the bars being wider and therefore kind of "brighter", but 2/1 is very acceptable too.

4/0 is disqualified. ^^ Same for master, now I see the asymetry (I didn't see it at first... again XD ).

**Comment by Ouaz** [comment]
Going to try it now! :fire:

**Comment by Ouaz** [comment]
That simply looks awesome! What a wizard you are. :shipit:
(don't mind the crappy rendering, old laptop with java 1.8, I play only on the Android version) 

![wow](https://user-images.githubusercontent.com/11946570/233853820-3af25ac8-aff9-4d12-8e86-7c8127403f58.png)

I don't know what you plan to do for the buff/debuff lines.
I think descriptions can be removed (only keep `name (type) +/- value%` e.g. `Shock II (Promotion) +15%`, '`Nationalism (Policy) +15%`, and therefore the font size could be increased a bit?
It does not have to be necessarily linked to their civilopedia articles, if it's too much hassle to implement. It will push players to learn their unit attributes only by their names. :book:
But maybe this have to be discussed first (I already see users saying "_Where are the buff descriptions!?_")

To be annoying until the end, could it be possible to make the red bar "flash" like in the current battle table? It's a nice visual touch, especially when removing a good chunk of the enemy HP bar.

Oh, and I almost forgot... MERCI!

PS: Is it possible to define a fixed height for the bars (as it changes depending the numbers of listed attributes)? Or maybe you have already fixed that.
![height](https://user-images.githubusercontent.com/11946570/233855368-0bfe577a-0e2b-4fad-be39-d244dc5b1914.png)

**Comment by Ouaz** [comment]
>So the jar was not useful after all? Huh?

No, no, useful. I use the PC version to test things (translation, assets, visual mods) and take screenshots/do mockups.
I "play" on the android version.

> But attacking a General - didn't notice that icon breaks layout too...
I thought it was the the "unit/city misalignment" you mentioned, and that you fixed in the last jar (the white bar and the attributes being shifted)

> Uh, wow, good thing, too. Dampens enthusiasm.
:laughing: 

> Oh - and if you want to help, could you produce saves where one can quickly test air sweep and nuke attacks?

I think I have a late game save file with that somewhere.

**Comment by Ouaz** [comment]
> could you produce saves where one can quickly test air sweep and nuke attacks?

Here it is: [AirSweep_Nuke_test.zip](https://github.com/yairm210/Unciv/files/11312899/AirSweep_Nuke_test.zip)
Go to Mosul in the lower right corner of the map.
![airsweep_nuke](https://user-images.githubusercontent.com/11946570/234067468-a1052dc4-396b-476d-8d19-c1143a2b44f1.png)

> Nuke, par exemple, could probably do with just a single column - the missile as header like above, and a victim list.

![nuke](https://user-images.githubusercontent.com/11946570/234068899-4d64a156-4b18-462d-9967-7d82a230c7e2.png)

I agree. On header showing the missile, and maybe sort the victims in two colums: `allied casualties | enemy casualties`, with Cities on top.
```
                Atomic Bomb
[Allied Casualties]    [Enemy Casualties]
        Mosul               Fustat
        Tank                Machine Gun
        Tank                Great General
                            Mobile Sam
                            Sheeps
```

**Comment by Ouaz** [comment]
> except if you're nuking "nice", one side is lopsidedly empty...

Ach, I didn't think of that. :grimacing: 

Let's keep the single column then.
And also the sorting then, as it is based on the bomb radius: units in 1-tile range from ground zero, then units in 2-tile range.

<details>
<summary>More sheeps.</summary>
"Sheeps" listed here just to have fun. And because "Sheep" has become an Unciv meme on Discord (https://github.com/RealBamboolord/Sheep-Meta), as it seems map RNG goes sometimes mad with sheeps everywhere at the start. (if I understood correctly the whole story).
</details>

**Comment by Ouaz** [comment]
Looks nice! I will test it tomorrow, I don't have my PC at the moment.
The summary text is a nice touch in my opinion, but maybe some players may find it redundant? Let's keep it for now.

> there's no sorting at the moment and getTilesInDistance goes by radius then two points along each radius "rim" clockwise... 

That's what I meant actually.^^ Sorry, my english is sometimes weak, that's why I use mockups most of the time. :p

- If we go for 2 columns (which I think looks good, even if the allied one may be empty), the sorting on the screenshot is good.
- If you prefer 1 colum, let's keep the current "rim clockwise + tile distance" sorting.

For the Air Sweep battle table, I have to think about it... Show the numbers of covered tiles by the sweep? I have no idea actually. XD

**Comment by itanasi** [comment]
By default for Air Sweep you have no idea if anyone even Can Intercept on a tile. And I'm pretty sure you can't check to see if enemy units have spare moves to use.

**Comment by Ouaz** [comment]
Tested, it looks very nice. :+1: 
For the "0 innocent bystanders, and 0 allies" listed most of the time... well, let's say we care about collateral damages. XD
What the colors mean is straightforward anyway, and players will test various target to see the difference (targeting their own cities for example).

Weeeelll... Mr. Nitpick is coming again:

![buff_order](https://user-images.githubusercontent.com/11946570/234659443-58686dc7-35fc-4de1-a5eb-e84aa0ff0cc5.png)

Is it possible to sort the promotion buff list? In the example above, by alphabetical order? 
```
Charge
Drill I
Drill II
Drill III
```

On the other hand, _it seems_ that all the buffs all already sorted by type (good thing) :
```
Promotion
Policy
Special (Great General, National ability, etc)
Tile attributes
Debuffs
```

Sorry to ask again things with all the work you already did!

**Comment by Ouaz** [comment]
> LinkedHashMap preserves order of addition...

That's what I assumed... on most of the units, except this tank on the screenshot. How the hell did I promote it first to Drill II and Drill I in last? :rofl: 
Answered by you (if I understood well):
_"Drill and Charge are the same UniqueType.Strength, which 42 steps further down come from a HashMap which practically guarantees random retrieval order..."_

> I might be tempted to code an animation that makes them change places randomly all the time - wouldn't be any worse...

Save you the trouble. Let's keep the actual code, this "random" sorting isn't a big deal anyway.

> You know, I also remember you suggesting "make them shorter" and me thinking "OK but pack the verbose explanation into a tooltip" then saying something like - that level of detail should come later, not the first two PR's...  I just looked, and that's all nicely contained in one source file I haven't touched here at all!

THIS is more interesting. Though... will tooltips work on Android? (I never tested touch&hold on Unciv actually, to see if some tooltips are displayed... I don't have my tablet at hand to check).
Nota bene: I requested clickable buff lines leading to their civilopedia articles otherwise, and make the font size a bit bigger if only buff names are displayed. :p _*hum hum annoying guy asking too much*_

> how do we remove the german flag from those health bars (black for xenophobia, red for bloodlust and gold for greed)

Oh geez, never noticed too. :laughing: 
Another _"Once you see it, you can't unsee it"._

**Comment by SeventhM** [comment]
Unstaling with a comment, might give a label if Yairm approves. Persona opinion: the vertical bars looks nice, but I still really want the exact numbers list *somewhere*. Should probably get a poll on discord if this goes anywhere

**Comment by itanasi** [comment]
The arguments about this on Discord were long, fraught, and partially led to letstalkaboutdune leaving

**Comment by SeventhM** [comment]
Well, I'm not aware of the history here, tbh  ¯\\\_(ツ)\_/¯. Probably wasn't paying attention entirely when it was discussed, especially since it wasn't through the polls channel. And, if this would go somewhere that improves the UI, might as well. If you're saying this is a wontfix scenario, then this can be closed then. Just seems at a glance that most of those involved with this issue seems to like the vertical healthbars, which means to me the next step would be polling

**Comment by itanasi** [comment]
Went looking and found one of the straw polls
https://discord.com/channels/586194543280390151/633733497277775884/1064981827544170566

**Comment by SeventhM** [comment]
The art channel and the polls channel are two very different channels. One gets a ping and most people check, the other... Not my focus

**Comment by itanasi** [comment]
My comment was less "this is Won't Fix" and more this is a very contentious topic.

Personally adding vertical and keeping the current numbers, perhaps at the bottom of the table, would be an improvement. I think all other additions have been done already at this point.

**Comment by SeventhM** [comment]
Looking there (had to copy the link to one of my 6 blank test discord servers then click from there... Don't ask why I have 6, I hardly use more than 2 anyways), I seems like the discussion is whether to have hp numbers or not. Maybe members of the art channel doesn't like the numbers, but I definitely do and would just want the information cleaned up. And [Yairm's previous message](https://github.com/yairm210/Unciv/issues/9205#issuecomment-1510763977)  implies the answer is, yes, we should have the numbers and would ***need*** to ping if we did a poll. 

As for making it vertical, this still doesn't seem to be contentious. Mostly everyone is ok with the idea of vertical bars like in Civ 5. If that can't be done because of a complaint about numbers, then maybe this should be closed because it won't ever move towards a phase where it could be polled

**Comment by yairm210** [comment]
Pretty accurate - numbers have to stay, bars can change

**Comment by Ouaz** [comment]
If the bars are made vertical (which I personally like, alongside the new battle table layout), the numbers won't be a problem anymore and they can stay as they are (i.e current HP -> Min-Max remaining HP range)

The fuss about the numbers was not about the numbers themselves, but the wrong order, which is counter-intuitive based on what HP projection the horizontal bar shows just above (`current HP -> **Max-Min** remaining HP range )

Horizontal bar (wrong):
<img src="https://user-images.githubusercontent.com/11946570/232610360-f57bf74a-0e64-4bdb-932d-10fa65a83963.png">

With the vertical bar, the discrepancy is solved, as the bar will be read independently from the remaining HP points projection range.
![verticalbar](https://github.com/yairm210/Unciv/assets/11946570/2d5ed8ee-685f-4346-897d-a0606399661f)

**Comment by SeventhM** [comment]
> The fuss about the numbers was not about the numbers themselves

Ehhhhh, you say that, but reading through that link to discord itanasi sent clearly shows there's also a subfaction that wants no numbers whatsoever, preferring to rely on standardized tick marks at most. Even the first suggestion mentioned in the issue's OP specifically is just a setting to remove the numbers with no other changes. I can totally see flipping the order of the numbers, but removing them outright is a nogo from me

Also, unless the new layout actually shows the numbers alongside the graph as your mockup shows, The whole concern about the numbers being backwards would still inevitably be there, so it's not like the move to a vertical graph really solves it

**Comment by Ouaz** [comment]
> there's also a subfaction that wants no numbers whatsoever

Haha, yes, they wanted no number (me included) or at least make them optional, once the request to modify the order has been rejected (mostly because people didn't understand that these numbers represent the color ranges in the HP bar).
It's really annoying to read these numbers while they're not matching the way the bar depletes JUST above.

> unless the new layout actually shows the numbers alongside the graph as your mockup shows

The new layout will show step numbers only (100, 75, 50, 25).

For me, the vertical bar solves it, as the HP numbers (Current -> Min-Max) will be far from it, not just next to it and "parallel", like with the horizontal bar, which causes the reading discrepancy.

The bar depletes vertically, the number projection shows the HP remaining and are read independently from the bar.

Hard to explain not in my native language. ^^

**Comment by itanasi** [comment]
Part of the disagreement on convention was numbers aligning to the bars.

In English normally you do Max - Min for a range of values. For whatever reason some RPGs do Min - Max, which is what we have now. And when we talked about horizontal bars going to center/outside, there was even worse weirdness of misalignment between the panels.

Vertical bars avoid all that, and so just keep the numbers consistent on both panels. We can argue about Max-Min v Min-Max in a separate Issue/Discord.

**Comment by SeventhM** [comment]
> once the request to modify the order has been rejected

Huh, didn't realized it got polled already

> In English normally you do Max - Min for a range of values. For whatever reason some RPGs do Min - Max, which is what we have now

Eh... depends. I mean, for code, I feel like `min <= x && x < max` is more common than `max > x && x >= min`, mostly as a side effect of stuff like for loops, and min - max does make more sense for ranges in some cases ("from 10 down to 5" sounds like downplaying as opposed to "from 5 up to 10"). The main reason imo it should go max-min here is more so the context of the arrow beforehand makes max-min look cleaner. Tbh, I don't really care how it looks next to the bar because the bar is itself hard to read being as small as it is and with no extra markers. So while everyone else might say vertical bars fix it, I really don't agree. I view that as a separate discussion altogether
