### ISSUE TITLE
Feature request: ability to view which city a tile belongs to

### ISSUE THREAD

**Issue by matty0234** [yairm210/Unciv#9315]
To start, I'm uncertain if this is a Civ VI feature, so I apologize if it is. 

I find it difficult to determine which city a tile belongs to when two cities are connected. I usually go into the city and look at which tiles are shaded and figure out if it's the one I'm looking to build on. There have been times when the tile is clearly in one of the cities but it's shaded darker in both. 

When selecting the tile, it shows which country it belongs to, but perhaps showing the city too would be great.

Alternatively, when you're in the city view, it could be helpful if the city borders were outlined.

I love the game though and appreciate the work and place to give feedback! 🫡🤘🏼

**Comment by yairm210** [comment]
I don't see a good reason to provide this info on the world screen, providing it in the city is good enough

**Comment by hackedpassword** [comment]
I wouldn't mind a display option that shows city property boundaries.

**Comment by SeventhM** [comment]
> I don't see a good reason to provide this info on the world screen, providing it in the city is good enough

I'm going to disagree here. I didn't even know that was a thing, and I feel this is extremely easy to miss. We also now have solutions for showing more detailed stats for tiles, and it seems more likely that someone checks this information from the world map rather than the city screen. I don't see where the harm is
