### ISSUE TITLE
Can declare war on city state after making peace with its allied major civ 

### ISSUE THREAD

**Issue by Stipidess** [yairm210/Unciv#9359]
**Platform**
It's on mobile, i think it's OPPO model CPH1909. I don't think mobile has the bits system (hopefully)

**Version**
Version 4.6.4-patch 2. Got it from the play store. 

**Describe the bug**

I was in war with Germany, Germany sent me a trade, to sign a peace contract and give me some gold. Since i was allied with every city state, they also signed the peace deal. But right at the literal next turn, germany declared war on a city state they're supposed to be in peace with. 

**To Reproduce**
I don't understand your instructions, but i don't know how to reproduce the bug either. 

**Expected behavior**
I expected for Germany to remain in peace with all city states. 

**Screenshots**
![Screenshot_2023-05-09-15-11-55-32](https://user-images.githubusercontent.com/82772485/237046610-0eda7597-0278-4174-8ef5-bdd486a2ed6d.jpg)
![Screenshot_2023-05-09-15-12-03-68](https://user-images.githubusercontent.com/82772485/237046656-8beb0f0e-8ad1-4c60-a21e-acf5701ea0f7.jpg)

**Additional context**
N/A

**Comment by yairm210** [comment]
Please attach the autosave of turn 802 (load game - show autosaves - copy to clipboard)
I think chances are that this will be solved if you update but I'm not certain

**Comment by yairm210** [comment]
@ravignir Just want to make sure - in Civ V, is this how it works? If you make peace with a civ that has an allied city state, can you then not declare war on that city state?

**Comment by yairm210** [comment]
If anyone is interested in working on the technical side of this:
The problem is that peace is declared between nations by a peace agreement *trade*, and we check the turns left of the peace agreement trade to determine how many turns are left before we can declare war.

So to extend this behavior to city-states, we can make a trade including only that - as in `getNegotiatePeaceCityStateButton`

Alternatively we can revamp this logic and have turns to peace be a DiplomacyFlag
