### ISSUE TITLE
Feature request: Use real JSON files

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9504]
**Is your feature request related to a problem? Please describe.**
JSON files don't have [] at the outer space, which is seen in multiple files. This will cause parse errors on web browsers.

**Describe the solution you'd like**
Use {} instead of [].

**Comment by touhidurrr** [comment]
Just curious, are you referring to Mod files here?

**Comment by GrimPixel** [comment]
Yes, mod files.
I must correct that. The reason why browsers can't parse them is that there are many trailing commas, instead of using [].

**Comment by touhidurrr** [comment]
I think this issue has a correct title but a wrong description. In JSON, `[]` means empty array, and `{}` means empty object. Both are standard in all JSON that I know of. 
Yes, Unciv doesn't use the standard JSON format, and browsers `JSON.parse` cant recognize it but that is not because of `[]`. It's because Unciv uses a non-standard and not-so-popular JSON format that has few parsers online. By few, I mean that I didn't find any parser for it online that could parse it except LibGdx.
The situation is so dire that I had to try to write a parser for it, which works somewhat but is not 100% accurate all time and sometimes gives incorrect output. You can find it here:
https://github.com/touhidurrr/UncivServer.xyz/blob/main/src/modules/UncivParser.ts
It has `parse()` and `stringify()` methods.

That's all. I do think Unciv should use standard JSON for all files, but it's a bit more complicated for Mods. I am not sure whether mod owners will like or dislike this change (probably the latter) and thus will not suggest the change either (lol).

**Comment by yairm210** [comment]
[] just means "array" in json. That's not a problem.
One thing that mod files do is they allow inclusion of *comments*, which is not is JSON spec, but many (most?) json parsers can handle that.
This issue comes from a *fundamental issue" with json (not allowing comments) which makes it hard to work with for humans.

@touhidurrr - that's only for save files, and even that has been fixed in latest versions :)

**Comment by yairm210** [comment]
In any case, forcing everyone to use non-commented json files is a no-go. Maybe we can experiment with supporting YAML, which - being an actually *good* standard - does support comments
