### ISSUE TITLE
Feature request: add more topics

### ISSUE THREAD

**Issue by GrimPixel** [yairm210/Unciv#9534]
**Is your feature request related to a problem? Please describe.**
There are few topics to distinguish the use of mods. It is hard to see what the mod does simply by their names

**Describe the solution you'd like**
Add more topics, like “unciv-nations”, “unciv-religions”, “unciv-buildings”, “unciv-improvements”, “unciv-units”.

**Comment by yairm210** [comment]
@SomeTroglodyte 
They won't appear as filters and as texts in the button:
![image](https://github.com/yairm210/Unciv/assets/8366208/cbe90925-0adc-43af-879f-4c664a697c72)

I think this is a good idea, as well as replacing "fun" with "mechanics" since that's what it's actually being used for practically speaking
