### ISSUE TITLE
Feature RFC: Civilopedia Search

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9591]
https://github.com/yairm210/Unciv/assets/63000004/bf5a61d8-fd79-469d-b5c8-66a9be6cd569

[For now, an imperfect test-of-concept](https://drop.picasoft.net/r/VkfpLu7S#Wnjqv1KDWdmiQ4OrUPJQgaKs0JnUaPmCfba6tjzHkgk=). 

Should search current *combined* ruleset by default, forgot the dropdown entry. Expander because the new one animates nicer (from bottom) while results come in from the background job - should replace w/standard pane. It's fulltext on the translated pedia texts, but I haven't really dug into whether there are loopholes it could miss. Also didn't know where to stash a UI for the question "I'm looking at Sentry Tower - which mod is it from?" Filtering mod by mod finds the answer, but...

**Comment by yairm210** [comment]
Definitely interesting! I'm not convinced that the dropdown is actually necessary since when you have a ruleset they you're using that entire ruleset

As for "source for objects", we could do this in the Ruleset creation - have each object contain an extra string for "sourceRuleset", and populate it when we read the files to create the objects
Then we can perhaps display that at the bottom of each Civilopedia item, just a small label of "source: {modName}"

**Comment by CrsiX** [comment]
I like that. I would space the results a little more, I guess one could miss-tap easily (at least in that view on smaller Android phones).
Also, do you have a minimum number of chars? Searching for `e` would probably yield a million results, basically the whole civilopedia, maybe only search for something like three or more characters?

**Comment by hackedpassword** [comment]
> I like that. I would space the results a little more

You know, trying to select from drop down menus is already a game of Operation...

@SomeTroglodyte Awesome. I like the concept of being able to search per mod, since what I'm looking for is almost certainly targeted to the mod in context.

Would you be able to attach the associated icon to each item?

**Comment by hackedpassword** [comment]
The explanation is appreciated @SomeTroglodyte. From the UX/UI side I think "why does it have to be so complicated, Just stick an imagine on the line!" but the rational knows-just-enough-software-dev-be-dangerous side says "stay out of the way and let real devs solve resource puzzles you don't even know where to start with!" Quite the internal conflict. Funny thing is, I showed up to this thread for exactly this, to hear more about the internal mechanics of the game. One day maybe it'll make coherent sense.

**Comment by yairm210** [comment]
@SomeTroglodyte Bump - would gladly have this in the game
