### ISSUE TITLE
Cannot resume game after update

### ISSUE THREAD

**Issue by marek22k** [yairm210/Unciv#9676]
**Platform**
Android

**Version**
4.7.4

**Describe the bug**
The game complains about a missing modification, although it is installed. However, it is now displayed under a different name in the "Store".

**Expected behavior**
No "=" is added to the end and the game loads.

**Screenshots**
![pic1](https://github.com/yairm210/Unciv/assets/46723399/cce15c4f-7bee-4222-a79c-3736d7cdb3a6)
![pic2](https://github.com/yairm210/Unciv/assets/46723399/a6f1071c-785e-4e0e-8216-272250202b68)

**Additional context**
Maybe related to https://github.com/yairm210/Unciv/pull/9645 and https://github.com/yairm210/Unciv/blob/master/core/src/com/unciv/ui/screens/pickerscreens/GitHub.kt#L457?

**Comment by marek22k** [comment]
> > although it is installed
> 
> No it's not

It is installed, as you can see on the screenshot, just under a different name.

> 
> Thing is, that mod's repository name is designed to crash Unciv on Windows, as we transate "-" to spaces, and Windows doesn't like folder names with trailing spaces. It can do them, but needs extra effort which is not done in simple Java libraries. The resolution was to map _trailing_ dashes to something else.

Somehow strange that such names exist. Personally, I would find it nicer to simply remove the spaces or special characters at the end - they bring no added value for the user.

> 
> As Linux(-kernel-based) user, you were able to use folder names with trailing blanks, but in the interest of some fairness it's better to treat all users equally, which means you get the folder name translation that saves Windows users from that DOS attack too, and will have to redownload. Simple as that.

**Comment by CodeKatta** [comment]
I have a similar problem after upgrading from 4.7.2 to 4.7.3 (f-droid):
![Screenshot_20230626_105538_Unciv](https://github.com/yairm210/Unciv/assets/26285588/dc5ab23e-8f3e-4797-a5a5-9ad11444049e)

Were there any major changes from 4.7.2 to 4.7.3?

**Comment by marek22k** [comment]
That would be another problem: The F-Droid version of UnCiv sometimes lags tremendously behind - often a version or two. Could this also be fixed? I therefore obtain my UnCiv via Obtainium from GitHub.

> I have a similar problem after upgrading from 4.7.2 to 4.7.3 (f-droid): ![Screenshot_20230626_105538_Unciv](https://user-images.githubusercontent.com/26285588/248741988-dc5ab23e-8f3e-4797-a5a5-9ad11444049e.png)
> 
> Were there any major changes from 4.7.2 to 4.7.3?

My problem occurred from 4.7.3 to 4.7.4. Yours one version earlier.

**Comment by yairm210** [comment]
F-droid has its own release cycle that we cannot affect...

**Comment by yairm210** [comment]
@marek22k please inform us if a redownload solves the issue
If so I consider this a non issue

**Comment by marek22k** [comment]
> @marek22k please inform us if a redownload solves the issue If so I consider this a non issue

Yes, that solved the problem.

**Comment by CodeKatta** [comment]
> I'd say not at all similar - since the number that should be controlling that message hasn't changed for a while (... has it? ... Nope: https://github.com/yairm210/Unciv/pull/8138, december), that makes me curious. Got that save somewhere?
Oops, I was wrong - that message is also used for any actual corruption to the save data. A copy of that save would still be nice to investigate.

Well, the save data is most definitely not corrupted, at least not according to version 4.7.2 (and earlier). Previous saves which were perfectly fine don't work with 4.7.3/4 either. I tested that on a Windows computer where I installed all three versions (4.7.2/3/4): saves that are rejected by 4.7.3/4 are loaded by 4.7.2 just fine.
Since it was an older game I started some time ago and I had archived in a separate folder I was curious if the really early saves (around turn 0+) are rejected as well and to my surprise they were loaded without any complaints.
Fortunately I hadn't deleted most save files yet, so I could find out where that break occurred: from turn 512 to 513. I can imagine it has something to do with the recruited spy, everything else looked ordinary enough to not cause any problems.
This is the save file from the end of turn 512: [Turn_512.txt](https://github.com/yairm210/Unciv/files/11882432/Turn_512.txt)
and this one is from the start of turn 513: [Turn_513.txt](https://github.com/yairm210/Unciv/files/11882447/Turn_513.txt)

**Comment by CodeKatta** [comment]
> Thank you @CodeKatta for the learning experience. It may sound like I'm making fun of you, but no, that is a valuable lesson.

You're welcome. I'm happy if I can help improve the game.

**Comment by CodeKatta** [comment]
> Somehow, that doesn't compute. Gaining spies without that option was closed in https://github.com/yairm210/Unciv/pull/7661 or 4.2.5. And the property hasn't changed between 4.7.2, even though the surrounding code changed.

That game was created somewhat over one year ago (with version 4.1.4-patch1) and I played it every now and then with several interruptions. Turns 512 and 513 were saved with version 4.2.4.747. Here are the original files:
[The Netherlands (0_512_513 turns).7z.zip](https://github.com/yairm210/Unciv/files/11885835/The.Netherlands.0_512_513.turns.7z.zip)
And I don't remember turning anything pertaining to espionage on or off. I was quite surprised myself to get a spy in the first place.

After a few months where I didn't play Unciv I had to load and save the most recent save file with version 4.5.1 so it got updated to the newest changes and the discovered tiles are displayed correctly. But even without this workaround (i.e. the original files) the problem is still the same (512 loads, 513 gets rejected).
