### ISSUE TITLE
RFC: Status quo / possibilities when a unit has more than one FoundCity unique

### ISSUE THREAD

**Issue by SomeTroglodyte** [yairm210/Unciv#9996]
This is relevant only to weird mods... Imagine one where a Settler can gain a Promotion through - say, a Fountain-of-Youth-alike. That promotion grants `Founds a new city <[3] times> <after which this unit is consumed>`. The idea of course - make the unit better...

Status quo: The second Unique is ignored. That Settler can still only found once.
Expectation: The second Unique is of "higher quality" somehow and should take precedence.

Cause: The `firstOrNull` in `getFoundCityAction`, UnitActions.L183, goes by whatever order MapUnit.getMatchingUniques decides (UniqueMap addition order which is baseUnit, type, promotions)

Possible approaches:
* Leave as is and drop a wiki hint somewhere
* Fix by making that a maxByOrNull over a quality - complicated as that should take usagesLeft into account, and that a mod may decide the unit survives after using up the founding action - now if there is a 3 times + survival and another for 3 times + death - gets complicated a little, right?
* Semi-Fix by nailing down the assumption promotions should always improve -> simply change UniqueMap addition order

Side comments:
* MapUnit.updateUniques allocates and discards an ArrayList - sounds needless to me, or is there a reason?
* Create improvement instantly works differently - there'll be more than one Action on the menu instead.
* Looks like some conditional check styles repeat quite often - enough to warrant some more helpers like hasConditional(UniqueType)?

**Comment by SeventhM** [comment]
I'm not sure how important it is to police mod makers on what shows up or what doesn't. While this may work fine for something like UnitActionConsumeUnit, how would this work if the mod maker has both one for that and one that uses movement instead? What if we add unit action conditionals?  That seems like something that could end up as a can of worms fast
I can see centralizing some of the code for actions to all function the same (or at least similarly), and maybe some optimization regarding actions to group up ones that aren't hyper specific. But otherwise, I think maybe the better solution might be to just show each one and request mod makers to address the layout themselves

**Comment by yairm210** [comment]
I am also against this. The new system supports adding additional 'charges', the old does not, we shouldn't retrofit to allow combinations of the two

**Comment by yairm210** [comment]
I don't think they do, though.
The root of the problem is that getMaxUsages() doesn't consider 'by consuming this unit' to be a *one time thing*, thus when you ask 'how many times can it X' it says just the extra amount.
What we should be doing is treating "<by consuming this unit>" THE SAME AS "<once> <after which this unit is consumed>", in both getMaxUsages AND getSideEffectString AND activateSideEffects.

Not sure what the best course of action would be though - just replace all instances of A with B and C would work, but not exactly clear, but then again I can't think of another cleaner solution right now

**Comment by SeventhM** [comment]
Can close?

**Comment by yairm210** [comment]
Yes
A base game can specify "can found once after which is consumed" if it wants to enable mods to add founding charges
